### ISSUE TITLE
Should Bucket.copy_blob be moved over to Blob?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1007]
/cc @tseaver

**Comment by tseaver** [comment]
My inclination is to treat copy and rename operations as more closely associated with "containers" than with "items".

**Comment by dhermes** [comment]
So then we should move `Blob.rename` to `Bucket`?

**Comment by dhermes** [comment]
@tseaver Bump

**Comment by tseaver** [comment]
I'd be fine with having `Blob.rename` move to `Bucket.rename_blob`.
