### ISSUE TITLE
Datastore overview page seems to be empty... ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1012]
Page Name: datastore-overview
Release: 0.7.0

https://googlecloudplatform.github.io/gcloud-python/latest/datastore-overview.html

Could we maybe walk users through the typical use cases?

**Comment by dhermes** [comment]
This was kind of resolved in #1025 but in essence #1037 covers what wasn't already done, so "merging" the two together.
