### ISSUE TITLE
Move all datetime handling into a shared core module

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1024]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1021#discussion_r35710351

We have (essentially) a novel approach to `datetime` in every sub-package, so we should get unified.

- From https://github.com/GoogleCloudPlatform/gcloud-python/pull/1044/files#r36545736: Hmm, maybe `_EPOCH` should be moved up to `gcloud._helpers`.

**Comment by dhermes** [comment]
@tseaver I'm going to take a crack at this.

**Comment by tseaver** [comment]
@dhermes OK, cool.
