### ISSUE TITLE
How do I create a Nearline / DRA bucket in Cloud Storage?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1030]
Page Name: storage-buckets
Release: 0.7.0

http://googlecloudplatform.github.io/gcloud-python/latest/storage-buckets.html#gcloud.storage.bucket.Bucket.create doesn't make this all that clear.

**Comment by dhermes** [comment]
Thanks for filing. It looks like we only support `storageClass` (and just as read-only property) on `Blob`:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/2928bfcd1a481e634ae35aa92941e4e5f129e4bd/gcloud/storage/blob.py#L756-L768

But that doesn't seem to be the right place, right?

**Comment by dhermes** [comment]
Scratch that, we also allow a read-only property on `Bucket`:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/2928bfcd1a481e634ae35aa92941e4e5f129e4bd/gcloud/storage/bucket.py#L635-L647

I still wonder why it's on `Blob`.
