### ISSUE TITLE
Exception when running demo.initialize()

### ISSUE THREAD

**Issue by clement** [GoogleCloudPlatform/gcloud-python#1048]
File ".../env/local/lib/python2.7/site-packages/gcloud/datastore/demo/__init__.py", line 26, in initialize
        datastore.set_default_dataset_id(DATASET_ID)
    AttributeError: 'module' object has no attribute 'set_default_dataset_id'

When running with:

    GCLOUD_TESTS_PROJECT_ID=X \
    GCLOUD_TESTS_DATASET_ID=X \
    GOOGLE_APPLICATION_CREDENTIALS=foobar.json \
    python -m gcloud.datastore.demo

on version 0.7.0

**Comment by dhermes** [comment]
@clement Thanks a lot for filing! You inspired to file #1049

Looking into it. It's still broken at `HEAD` (I just checked).

**Comment by dhermes** [comment]
@clement This won't be fixed until we cut a new release. But that may be very soon. (/cc @tseaver)
