### ISSUE TITLE
Start implementing setIamPolicy, getIamPolicy, and testIamPermissions

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1073]
I thought we already had an issue filed, must have mismembered.

See GoogleCloudPlatform/gcloud-node#758 and GoogleCloudPlatform/gcloud-node#767

@tseaver Care to take a stab at it?

**Comment by tseaver** [comment]
[Narrative docs](https://cloud.google.com/pubsub/access_control?hl=en)

[Policy resource definition](https://cloud.google.com/pubsub/reference/rest/Shared.Types/Policy)

Topic methods:

- https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/getIamPolicy
- https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/setIamPolicy
- https://cloud.google.com/pubsub/reference/rest/v1/projects.topics/testIamPermissions

Subscription methods:

- https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/getIamPolicy
- https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/setIamPolicy
- https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/testIamPermissions

**Comment by dhermes** [comment]
@tseaver Are you planning on doing this or just added docs as a resource?

**Comment by tseaver** [comment]
I'm still planning on it.

**Comment by dhermes** [comment]
Great to hear

**Comment by dhermes** [comment]
@tseaver Still planning on it?

**Comment by tseaver** [comment]
Dropped off my radar, I'm afraid.

**Comment by dhermes** [comment]
Coming back on the radar or no?

**Comment by tseaver** [comment]
Depends on priorities, really.  @jgeewax, how important would you rate this feature?

**Comment by tseaver** [comment]
I will tackle this issue today:  it is a prerequisite for using topics as logging sink destinations.

**Comment by dhermes** [comment]
Good to hear. ISTM this probably belongs in `oauth2client`. WDYT?

**Comment by tseaver** [comment]
I'm confused:  those operations are about changing security settings on the API subject-domain resources (projects / topics / subscriptions.)  I don't see anything related to `oauth2client`.

**Comment by dhermes** [comment]
I am unfamiliar with how they work so take my previous comment with a grain of salt

**Comment by tseaver** [comment]
These methods are basically attacking the same problem as `BucketACL`/`ObjectACL` in Cloud Storage, or `Dataset.access_grants` in BigQuery.

**Comment by jonparrott** [comment]
Right on, @tseaver. These methods essentially API-level ACLs.

**Comment by dhermes** [comment]
SGTm
