### ISSUE TITLE
Pubsub example on front page fails if topic does not already exist

### ISSUE THREAD

**Issue by Michael0x2a** [GoogleCloudPlatform/gcloud-python#1082]
The pubsub example throws an exception if the specified topic does not already exist. Example:

```python
>>> from gcloud import pubsub
>>> client = pubsub.Client(project=MY_PROJECT_ID)
>>> topic = client.topic('my-new-custom-topic')
>>> topic.publish('Ping!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/topic.py", line 186, in publish
    method='POST', path='%s:publish' % (self.path,), data=data)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/connection.py", line 419, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.NotFound: 404 Resource not found (resource=my-custom-topic). (POST https://pubsub.googleapis.com/v1/projects/lee-cloud/topics/my-custom-topic:publish)
```

The code sample will resume working if you create the topic and re-run the sample, but it would be nice if the code sample included a line or two demonstrating how to create a topic if it doesn't exist.

**Comment by dhermes** [comment]
What page is this from?

**Comment by Michael0x2a** [comment]
Whoops, sorry -- at the bottom of https://cloud.google.com/python/ if you click "Publish messages and subscribe to Pub/Sub topics".

**Comment by jonparrott** [comment]
Assign this to me, Danny. I guess we need to call out specifically that
users should create their topic beforehand.

(fwiw, I don't like these samples on the python landing page...)

**Comment by dhermes** [comment]
@jonparrott I can't assign to someone outside the org. Are you not a part of GoogleCloudPlatform? If not, why not?

**Comment by jonparrott** [comment]
I am, but our repos are divided into teams. I'm not part of the team that's
on this repo (perhaps I should be?)

**Comment by dhermes** [comment]
What are the implications? We can chat on Hangouts if it's easier / less public.

**Comment by jonparrott** [comment]
Nothing that I'm aware of. Summoning @elibixby who has admin rights to GoogleCloudPlatform.

**Comment by elibixby** [comment]
Unfortunately right a team has a level of permissions, a set of repos and a set of members, and everyone  on the team has the same level of permissions for all the repos of the team.... It's a really bad permissions model, and we're moving to the new one Sept 22nd, until then, make your team choice accordingly =)

**Comment by jonparrott** [comment]
I'm tracking this via an internal bug now, as it's unclear whether we should instruct new users to create projects, enable billing, etc, or just remove these code samples.

**Comment by dhermes** [comment]
Shall I close this issue?

**Comment by jonparrott** [comment]
Sure - it's not an issue with this library.
