### ISSUE TITLE
[Documentation Issue] Order in the dropdown of languages isn't in alphabetical order

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1091]
Page Name: index
Release: b4a8d75

The others (Node + Ruby) have the language list in alphabetical order. Can we do likewise?

![dropdown](https://cloud.githubusercontent.com/assets/112928/9494024/a79b5392-4bd1-11e5-880f-0e0a03f9a1c4.png)

**Comment by dhermes** [comment]
Made even worse by the fact that our landing page does it in alphabetical order:

![screen_shot_031](https://cloud.githubusercontent.com/assets/520669/9495439/62b34408-4bc0-11e5-80fd-9a7f0542c9be.png)
