### ISSUE TITLE
Investigate novel bigquery system test failures

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1104]
1.  Job state not DONE

    ```python
    ======================================================================
    FAIL: test_load_table_from_storage_then_dump_table (bigquery.TestBigQuery)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/bigquery.py", line 304, in test_load_table_from_storage_then_dump_table
        self.assertTrue(job.state in ('DONE', 'done'))
    AssertionError: False is not true
    ```

    From: 

    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/77509799
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/78073572
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/95718525
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/95827336
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/97283623
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/98448630
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/100920167
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/100929401

1.  Dataset not cleaned up from previous failed run (or concurrent run)

    From:

    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/77772358
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/78113108
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/79729612
    1.  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/97489872

1.  Eventual consistency

    ```python
    ======================================================================
    FAIL: test_load_table_then_dump_table (bigquery.TestBigQuery)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/bigquery.py", line 239, in test_load_table_then_dump_table
        sorted(ROWS, key=by_age))
    AssertionError: Lists differ: [] != [('Bhettye Rhubble', 27), ('Wylma Phlyntst[57 chars] 33)]
    Second list contains 4 additional elements.
    First extra element 0:
    ('Bhettye Rhubble', 27)
    - []
    + [('Bhettye Rhubble', 27),
    +  ('Wylma Phlyntstone', 29),
    +  ('Phred Phlyntstone', 32),
    +  ('Bharney Rhubble', 33)]
    ```

    From https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/78498010

**Comment by dhermes** [comment]
@tseaver Concurrent runs make BQ tests fail hard since they can't re-create the dataset. Can we make the dataset name scoped to the millisecond (or microsecond) so there won't be name collisions?

**Comment by dhermes** [comment]
@tseaver https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/79729612 (the most recent merge) had an issue with the fixed name of the dataset used. I just deleted it by hand from the Cloud Console.

**Comment by tseaver** [comment]
@dhermes #1131 should address the name-clash on dataset IDs.

**Comment by tseaver** [comment]
I'm going to call this one done: #1131 handled the dataset ID uniqueness issue, and  the remaining timeout / backoff issues are tracked in #1391 / #1619.

**Comment by tseaver** [comment]
#2050 tidies up the ad-hockery added earlier for these cases.
