### ISSUE TITLE
Shorten URL for gcloud-java link

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-python#1115]
gcloud-java is in the midst of cleaning up it's gh-pages branch, and part of that is making the URL shorter. The link on python's website should be modified to http://googlecloudplatform.github.io/gcloud-java/ (removing "site/latest/").

**Comment by dhermes** [comment]
This was fixed by #1116 and #1117, right? If not, please re-open @ajkannan
