### ISSUE TITLE
Big query TIMESTAMP field off by factor of 1000

### ISSUE THREAD

**Issue by arterrey** [GoogleCloudPlatform/gcloud-python#1126]
Using master branch. In BigQuery TIMESTAMP fields are off by a factor of 1000 when using fetch_data. 

See my in-line comment - https://github.com/GoogleCloudPlatform/gcloud-python/commit/41e64395661a31af8352fb2358e5c95ff5437830#diff-c56e349a3e511bfabb4e8dfcfe686bc8R739

**Comment by dhermes** [comment]
Sorry just saw this. Closing in favor of #1125 (a bit more detail there)
