### ISSUE TITLE
Demo "Publish messages and subscribe to Pub/Sub topics" doesn't work 

### ISSUE THREAD

**Issue by jpvic** [GoogleCloudPlatform/gcloud-python#1127]
The 3th demo doesn't work on "https://cloud.google.com/python/"

from gcloud import pubsub

client = pubsub.Client(project='your-project-id')
topic = client.topic('your-topic-name')

topic.publish('Ping!')

subscription = topic.subscription('your-subscription-name')

messages = subcription.pull()

for ackid, message in messages:
    print message

subscription.acknowledge([ackid for ackid, _ in messages])

1.
messages = subcription.pull()
==> typo : subscription.pull()

2.
the example ends with :+1:     raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
It tried a json object, but then it asks for a string...

**Comment by dhermes** [comment]
@jonparrott

**Comment by jpvic** [comment]
thank you for quick response. although it is short.. ;-)

**Comment by dhermes** [comment]
@jpvic Sorry, that demo is owned by @jonparrott, so I was making him aware of this issue.

**Comment by jonparrott** [comment]
Still can't assign issues to me? :P 

Typo is an easy fix, I'll investigate the other issue.

**Comment by dhermes** [comment]
Still can't. But don't you have a separate repo for these samples?

**Comment by jonparrott** [comment]
Not the ones on the homepage. I'm still trying to get them removed altogether as that page does not provide enough context for users to successfully run the samples.

**Comment by dhermes** [comment]
OK. Is there a repo you could move this issue to (so you could be the assignee)?

**Comment by jonparrott** [comment]
Yes - [getting-started-python](https://github.com/GoogleCloudPlatform/getting-started-python).

**Comment by dhermes** [comment]
Closing out in favor GoogleCloudPlatform/getting-started-python#6
