### ISSUE TITLE
Should we hide old releases?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1132]
When visiting https://pypi.python.org/pypi/gcloud or when clicking the `gcloud` part of `Package Index > gcloud > 0.7.1`:

![screen_shot_008](https://cloud.githubusercontent.com/assets/520669/9800854/3ce5ca6a-57c4-11e5-9358-75f7b94fa335.png)

many users expect to see a list of all versions.

----

We currently have this disabled (i.e. "Auto-hide old releases"):

![screen_shot_007](https://cloud.githubusercontent.com/assets/520669/9800862/484f35c6-57c4-11e5-982f-8bdf09cb2e12.png)

----

The alternative though is that the https://pypi.python.org/pypi/gcloud page would just give a list of all releases rather than the latest one. For [example][1]

![screen_shot_009](https://cloud.githubusercontent.com/assets/520669/9801168/4ab270c4-57c6-11e5-9c79-e3473c5cbdfe.png)

[1]: https://pypi.python.org/pypi/protobuf

**Comment by jgeewax** [comment]
I think maybe it's safe to keep old 0.x versions hidden... But we should definitely discuss again at 1.0+

**Comment by tseaver** [comment]
My experience is exactly the opposite:  users want to see only the latest version (the one which would be installed by default).  FWIW, "hide releases" is a web UI-only thing:  the `/simple/` views used by pip/setuptools still show all published releases, allowing `pip install gcloud==0.7.0`, etc.

**Comment by dhermes** [comment]
https://pypi.python.org/simple/gcloud/ is the view you're referencing?

Seems there is nothing to do, already working as intended.
