### ISSUE TITLE
Should we map the '/projects/get' API

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1136]
See https://cloud.google.com/dns/api/v1/projects/get

The resource consists of read-only information (quotas, mostly) about the project within DNS.

One strategy might be to add a `quotas` method to the client which fetched and returned the `quotas` sub-mapping for the project.

**Comment by dhermes** [comment]
If it's simple to do, I see no reason not to. If it is a lot of work, we can revisit.

**Comment by tseaver** [comment]
The `Client.quotas` method does expose all the relevant information.
