### ISSUE TITLE
Make sure gcloud-auth doc isn't too datastore specific

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1142]
From @tseaver in: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1137/files#r39682019

> Dunno -- maybe it just needs to note that the other API clients are all similar (actually, `datastore` is the oddball, compared to `storage/pubsub/bigquery/dns`).

**Comment by dhermes** [comment]
@tseaver The only mention of `datastore` is at the beginning in the "Client-Provided Authentication" section:

![screen shot 2015-09-20 at 10 11 02 am](https://cloud.githubusercontent.com/assets/520669/9981928/ed73b2e4-5f7f-11e5-8e70-1be8da54354f.png)

Nothing else even mentions a sub-package (though we do later mention all the services and required scopes).

----

I can change it if you like, what do you think would work better?

I **know** I've got to send a PR against this doc since discovered that we've got broken links since
https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authorization/enable-apis.png
has become
https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/enable-apis.png
(and similar for the other 2 or 3 such images we use in this doc).

(I caused this since I asked the node guys and `gcloud-common` to say authentication instead of authorization.)

**Comment by dhermes** [comment]
@tseaver Bump

**Comment by tseaver** [comment]
Works for me.  I must have been bleary-eyed.

**Comment by dhermes** [comment]
Closing now. (Only left it open until I remembered to do the work in #1166)
