### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address for IPython Notebook Tornado Setup

### ISSUE THREAD

**Issue by hoteit** [GoogleCloudPlatform/gcloud-python#1151]
I can't get Tornado web service to run with IPython Notebook on one of the cloud instances. I tried changing ports and I keep getting the error OSError: [Errno 99] Cannot assign requested address from File "/var/www/machinelearning/env/lib/python3.4/site-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
Note that I am running IPython in virtual env using Python3

**Comment by tseaver** [comment]
I don't think your issue can have anything to do with `gcloud-python`, which provides client-side wrappers for access to Google Cloud APIs:  this project is not related to running Python processes on GCE nodes (although it might eventually expand to include *configuring* those nodes).

@dhermes can you suggest the correct place to report the issue?

**Comment by dhermes** [comment]
@hoteit Who were you trying to reach?

**Comment by hoteit** [comment]
I solved it. Please close ticket

On Wed, Sep 23, 2015, 16:11 Danny Hermes <notifications@github.com> wrote:

> Closed #1151
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/1151>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/1151#event-417459023>
> .
>
-- 

Tarek Hoteit

214-494-9691
t@tarek.computer
https://tarek.computer

**Comment by dhermes** [comment]
Already closed. Cheers!
