### ISSUE TITLE
Where do we report bugs with Cloud Search?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1163]
For instance, the [docs for the indexes resource](https://cloud.google.com/search/reference/rest/v1/projects/indexes) indicate that there is no way to `get` the resource for a given index ID:  the only API choice is `list`.

**Comment by tseaver** [comment]
I have another issue:  the [docs for `v1.projects.indexes.search`](https://cloud.google.com/search/reference/rest/v1/projects/indexes/search) show the `nextPageToken` as a member of `SearchResult`, which is the entity for a single document returned within the response;  it should be a top-level member of the response, instead (like `matchedCount`).

**Comment by yyr2015** [comment]
"get index" is not supported in current version of Cloud Search, but it will be available in next release.

The nextPageToken is associated with each document so that you may start listing the result from any document for next search. If you want a page-by-page listing, you may use the nextPageToken for the last document in this page.

**Comment by dhermes** [comment]
@tseaver Should this issue remain open? I'm **assuming** no but if I am wrong, please re-open.

**Comment by tseaver** [comment]
The meta-issue (where to report problems with the API) is still unresolved, AFAIK.

**Comment by dhermes** [comment]
@jgeewax Can we try to reach a resolution here?

**Comment by yyr2015** [comment]
Please send an email to cloudsearch-support@google.com for any question or suggestion. Thank you!

**Comment by dhermes** [comment]
Thanks. @tseaver Closing this out, we can refer back even after closing.
