### ISSUE TITLE
Whitelisting our projects for the Search API

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1181]
@jgeewax When beginning work on `gcloud.search` (2015-10-01), I requested that my project be whitelisted for the Search API via the [form](https://docs.google.com/a/google.com/forms/d/1TshVfwJBP8UoKN-cpjIo4yB6TIiBYrMuxTQQ8LQfPyk/viewform).  Today, working on a system test for the API, I see the following:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud/search/document.py", line 321, in exists
    client.connection.api_request(method='GET', path=self.path)
  File "gcloud/connection.py", line 337, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.Forbidden: 403 The caller does not have permission (GET https://cloudsearch.googleapis.com/v1/projects/citric-celerity-697/indexes/system-tests/documents/aaa)
```
I do not see "Cloud Search" as an available API from my developer console.  We need to get expedited access:  I just re-submitted the form with @jgeewax as the "project owner".

**Comment by jgeewax** [comment]
Which project IDs do you need ? Just precise-truck-742 ?

**Comment by tseaver** [comment]
@jgeewax Mine is `citric-celerity-697`.  I'm sure @dhermes will need his, along with the project used when running system tests on Travis.

**Comment by dhermes** [comment]
`omega-moonlight-697`

**Comment by jgeewax** [comment]
OK, requesting whitelisting for all 3 projects. Will update this list once it's done.

**Comment by dhermes** [comment]
FYI @tseaver to access using your personal account follow http://gcloud-python.readthedocs.org/en/latest/gcloud-auth.html#user-accounts-3-legged-oauth-2-0-with-a-refresh-token

Most importantly, download the `gcloud` CLI tool and run

```bash
$ gcloud auth login
```

then we'll grab the user credentials.

You probably have `GOOGLE_APPLICATION_CREDENTIALS` set. I did. So I ran

```python
import os
os.environ.pop('GOOGLE_APPLICATION_CREDENTIALS')
from gcloud.search import client
c = client.Client(project='foo')
print c.connection.credentials.to_json()  # To verify it is a user account
print c.list_indexes()
```

This actually caused a `KeyError`. I got `{}` as the response but the [code][1] assumes the `indexes` key is present.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/7574b4667bb70e07776f82acd58554f7bb834e73/gcloud/search/client.py#L93

**Comment by dhermes** [comment]
Closing because I am assuming we are whitelisted. @tseaver or @jgeewax re-open if this is false.

**Comment by tseaver** [comment]
Project-based access is still not working.

**Comment by dhermes** [comment]
@jgeewax we can close this out right? API removed in #1750

**Comment by jgeewax** [comment]
Yep. This is fine.
