### ISSUE TITLE
blob.acl.reload(): 403 Insufficient Permission 

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/gcloud-python#1195]
I cannot explain this error.
```Python
>>> client = storage.Client('project') # project edited
>>> bucket = client.get_bucket('cdn.project') # likewise
>>> blob = bucket.blob('file.txt')
>>> blob.content_type = 'text/plain'
>>> blob.upload_from_string('text')
>>> blob.reload()
>>> blob.acl.reload()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/storage/acl.py", line 383, in reload
    found = client.connection.api_request(method='GET', path=path)
  File "/home/user/.local/lib/python2.7/site-packages/gcloud/connection.py", line 337, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.Forbidden: 403 Insufficient Permission (GET https://www.googleapis.com/storage/v1/b/cdn.project/o/file.txt/acl)
```
With the same account, ```gsutil acl get gs://cdn.project/file.txt``` works fine.

**Comment by dhermes** [comment]
How are you confirming it is the same account?

**Comment by pdknsk** [comment]
How can I confirm it? There's only one account set-up through ```gcloud```, which both ```gsutil``` and ```gcloud-python``` infer their credentials from.

**Comment by dhermes** [comment]
```python
import json
client = storage.Client('project')
print type(client.connection.credentials)
```

If you've got a service account as your credentials you should verify it's the right one. If you've got a user account (which can come from `gcloud`) then you can check which user account by inspecting an access token at https://developers.google.com/apis-explorer/#p/oauth2/v2/oauth2.tokeninfo (You won't have an access token until your client makes a request, but once it does you can get it via `client.connection.credentials.access_token`.)

**Comment by pdknsk** [comment]
It's a user account, with the following rights.
```
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/cloud-platform
https://www.googleapis.com/auth/appengine.admin
https://www.googleapis.com/auth/compute
https://www.googleapis.com/auth/plus.me
```
I have a suspicion what might be causing the problem.
```Python
>>> for scope in client.connection.SCOPE:
...   print scope
... 
https://www.googleapis.com/auth/devstorage.full_control
https://www.googleapis.com/auth/devstorage.read_only
https://www.googleapis.com/auth/devstorage.read_write
```
[According to the docs](https://cloud.google.com/storage/docs/authentication#oauth-scopes), ```cloud-platform``` is equivalent to ```devstorage.full_control```.

**Comment by dhermes** [comment]
First check the credentials to make sure it was the correct user. Then we can investigate if the scopes are not correct. As you pointed out, the `devstorage.*` scopes should be sufficient.

**Comment by pdknsk** [comment]
Yes it's the correct user.

**Comment by dhermes** [comment]
OK then. That is unfortunate / interesting as an issue.

For user accounts, the scopes [on `Connection`][1] don't matter. It's the original scopes used when the user refresh token was minted. So that (theoretically) means it should work the same from CLI and from the library. The mystery gets murkier.

Can you inspect an access token with the APIs explorer link I sent to check which scopes it has attached to it?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f430770a4fe681c2941d229618e585c2a261941d/gcloud/storage/connection.py#L40-L43

**Comment by pdknsk** [comment]
Yes that's what I did and posted! :)

**Comment by dhermes** [comment]
Ah I see. More mystery. Have you added the logging flags to `gcloud` CLI to see what is being sent when you make a request?

**Comment by pdknsk** [comment]
I think you mean ```gsutil``` and I didn't know it had such extensive debug output. What I've confirmed from ```Bearer``` set by ```gsutil``` and ```client.connection.credentials.access_token``` used by ```gcloud-python``` is that both use the same account.

The link seems to be different. ```gsutil``` uses the following link.
```
https://www.googleapis.com/storage/v1/b/cdn.project/o/file.txt?fields=name%2Cacl&alt=json&projection=full
```
And has this ```selfLink``` in the response object.
```
https://www.googleapis.com/storage/v1/b/cdn.project/o/file.txt/acl/user-0123456789abcdef
```

**Comment by dhermes** [comment]
I meant `gcloud`, I was under the impression that `gsutil` had been folded into the `gcloud` CLI, but it seems I was wrong.

The `selfLink` is probably in the ACL itself rather than in the object. The `/b/.../o/...` paths are for getting objects directly.

What other headers seem to be different? I can send you a patch to check what is being sent from `gcloud-python` as well.

**Comment by pdknsk** [comment]
Please do!

**Comment by dhermes** [comment]
So I am just about to teach and this isn't exactly a patch, but just modify the [`Connection._do_request`][1] method. Either print out the values in 

```python
        return self.http.request(uri=url, method=method, headers=headers,
                                 body=data)
```

or add a statement like

```python
import ipdb
ipdb.set_trace()
```

and inspect the objects manually.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f430770a4fe681c2941d229618e585c2a261941d/gcloud/connection.py#L261-L262

**Comment by jonparrott** [comment]
I'm about to reproduce this and I've filed an internal bug. I'll keep this updated.

In the meantime, it seems that using service account credentials should work.

**Comment by pdknsk** [comment]
First of all I printed out the exact error message as returned in the ```www-authenticate``` response header.

```
Bearer realm="https://accounts.google.com/", error=insufficient_scope, scope="https://www.googleapis.com/auth/devstorage.full_control"
```

The request with ```gsutil```.
```
GET: https://www.googleapis.com/storage/v1/b/cdn.project/o/file.txt?fields=name%2Cacl&alt=json&projection=full
Headers: {'accept': 'application/json', 'accept-encoding': 'gzip, deflate', 'content-length': '0', 'user-agent': 'apitools gsutil/4.15 Python/2.7.6 (linux2) Cloud SDK Command Line Tool 0.9.83'}
```
And with ```gcloud-python```.
```
GET: https://www.googleapis.com/storage/v1/b/cdn.project/o/file.txt/acl
Headers: {'Content-Length': 0, 'Accept-Encoding': 'gzip', 'User-Agent': 'gcloud-python/0.8.0'}
```

**Comment by dhermes** [comment]
Thanks @pdknsk and @jonparrott! Sorry this issue came up @pdknsk!

@jonparrott what is the difference between the two requests and how can we mitigate? It's especially strange to me because I thought we were using an identical refresh token that `gsutil` is using.

**Comment by jonparrott** [comment]
Honestly, I don't know. I have the internal stack trace from the API client request that basically indicates that the `devstorage.full_control internal` scope isn't satisfied by `cloud-platform`. No idea why `gsutil` works.

**Comment by tseaver** [comment]
Could it be that we are querying the ACL resource directly, while `gsutil` is fetching it via a `full` query on the bucket / object instead?  E.g., `blob.acl.reload()` ends up making a `GET` request to `/storage/v1/b/<bucketname>/o/<objecctname>/acl`, rather than to `/storage/v1/b/<bucketname>/o/<objecctname>`.

**Comment by jonparrott** [comment]
Maybe, either way, the API should respect the `cloud-platform` scope and allow the token to be used to change ACLs on storage blobs.

**Comment by pdknsk** [comment]
It's definitely an internal scope error. I tried the Explorer with scope ```devstorage.full_control``` granted – works, but not with ```cloud-platform```.

https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls/list

This wouldn't be a problem if the user account could somehow acquire that scope, but it can't because ```gcloud``` doesn't want it.

**Comment by jonparrott** [comment]
Thanks for thoroughly testing all of this, @pdknsk. Let me know if I can do anything to help you get up and running while we wait for the bug to be fixed.

**Comment by pdknsk** [comment]
I think I was mistaken with the last sentence of my previous comment. ```gcloud``` does request and get that scope. I can see in the account security under *Connected Apps* that **Google Cloud SDK** has many scopes listed, among them this one: *Manage your data and permissions in Google Cloud Storage*. I have confirmed through API Explorer that this is ```devstorage.full_control```.

**Comment by dhermes** [comment]
Thanks a lot for this guys

**Comment by saxenanurag** [comment]
What I did was assign allUsers 'reader' access using the web console. This helped me to use the storage api link to access objects outside of the application. 

Would it be possible to get something similar to get_serving_url in app engine (https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.images#google.appengine.api.images.get_serving_url) using this library as well? Should I file this as a different issue?
Thanks.

**Comment by dhermes** [comment]
Please file a new issue.

**Comment by saxenanurag** [comment]
Filed as #1295

**Comment by pdknsk** [comment]
This is fixed on the backend. I confirmed with ```gcloud``` and in the Explorer.

**Comment by tseaver** [comment]
@pdknsk thanks for the follow-up!

**Comment by ye** [comment]
I am running into this issue still today.

```bash
In [1]: from google.cloud import storage

In [2]: client = storage.Client()
Making request: GET http://169.254.169.254
Making request: GET http://metadata.google.internal/computeMetadata/v1/project/project-id
Making request: GET http://169.254.169.254
Making request: GET http://metadata.google.internal/computeMetadata/v1/project/project-id

In [3]: client
Out[3]: <google.cloud.storage.client.Client at 0x7f1aed7e1f60>

In [4]: bucket = client.get_bucket('3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0')
Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true
Making request: GET http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/920123456789-compute@developer.gserviceaccount.com/token

In [5]: bucket
Out[5]: <Bucket: 3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0>

In [6]: blob = bucket.blob('test-file')

In [7]: blob 
Out[7]: <Blob: 3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0, test-file>

In [8]: blob.content_type = 'text/plain'

In [9]: blob.upload_from_string('foobar')

In [10]: blob
Out[10]: <Blob: 3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0, test-file>

In [11]: blob.acl.save_predefined('projectPrivate')
---------------------------------------------------------------------------
Forbidden                                 Traceback (most recent call last)
<ipython-input-11-273451c05731> in <module>()
----> 1 blob.acl.save_predefined('projectPrivate')

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in save_predefined(self, predefined, client)
    496             raise ValueError("Invalid predefined ACL: %s" % (predefined,))
    497 
--> 498         self._save(None, predefined, client)
    499 
    500     def clear(self, client=None):

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in _save(self, acl, predefined, client)
    449             path=path,
    450             data={self._URL_PATH_ELEM: list(acl)},
--> 451             query_params=query_params)
    452         self.entities.clear()
    453         for entry in result.get(self._URL_PATH_ELEM, ()):

/usr/local/lib/python3.5/site-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    333         if not 200 <= response.status < 300:
    334             raise make_exception(response, content,
--> 335                                  error_info=method + ' ' + url)
    336 
    337         string_or_bytes = (six.binary_type, six.text_type)

Forbidden: 403 Insufficient Permission (PATCH https://www.googleapis.com/storage/v1/b/3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0/o/test-file?projection=full&predefinedAcl=projectPrivate)

In [16]: blob.acl       
Out[16]: <google.cloud.storage.acl.ObjectACL at 0x7f1aec93a2e8>

In [17]: blob.acl.all()
---------------------------------------------------------------------------
Forbidden                                 Traceback (most recent call last)
<ipython-input-17-eb070d80f676> in <module>()
----> 1 blob.acl.all()

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in all(self)
    364         :returns: An entity representing all users.
    365         """
--> 366         return self.entity('allUsers')
    367 
    368     def all_authenticated(self):

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in entity(self, entity_type, identifier)
    319         """
    320         entity = _ACLEntity(entity_type=entity_type, identifier=identifier)
--> 321         if self.has_entity(entity):
    322             entity = self.get_entity(entity)
    323         else:

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in has_entity(self, entity)
    270         :returns: True of the entity exists in the ACL.
    271         """
--> 272         self._ensure_loaded()
    273         return str(entity) in self.entities
    274 

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in _ensure_loaded(self)
    213         """Load if not already loaded."""
    214         if not self.loaded:
--> 215             self.reload()
    216 
    217     def reset(self):

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in reload(self, client)
    416         self.entities.clear()
    417 
--> 418         found = client._connection.api_request(method='GET', path=path)
    419         self.loaded = True
    420         for entry in found.get('items', ()):

/usr/local/lib/python3.5/site-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    333         if not 200 <= response.status < 300:
    334             raise make_exception(response, content,
--> 335                                  error_info=method + ' ' + url)
    336 
    337         string_or_bytes = (six.binary_type, six.text_type)

Forbidden: 403 Insufficient Permission (GET https://www.googleapis.com/storage/v1/b/3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0/o/test-file/acl)

In [18]: blob.acl.reload()
---------------------------------------------------------------------------
Forbidden                                 Traceback (most recent call last)
<ipython-input-18-284fd543edf4> in <module>()
----> 1 blob.acl.reload()

/usr/local/lib/python3.5/site-packages/google/cloud/storage/acl.py in reload(self, client)
    416         self.entities.clear()
    417 
--> 418         found = client._connection.api_request(method='GET', path=path)
    419         self.loaded = True
    420         for entry in found.get('items', ()):

/usr/local/lib/python3.5/site-packages/google/cloud/_http.py in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    333         if not 200 <= response.status < 300:
    334             raise make_exception(response, content,
--> 335                                  error_info=method + ' ' + url)
    336 
    337         string_or_bytes = (six.binary_type, six.text_type)

Forbidden: 403 Insufficient Permission (GET https://www.googleapis.com/storage/v1/b/3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0/o/test-file/acl)


$ gsutil acl get gs://3e31f033-bc2c-4aa4-a2b7-bb0c550ea3f0/test-file
[
  {
    "entity": "project-owners-920123456789",
    "projectTeam": {
      "projectNumber": "920123456789",
      "team": "owners"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-editors-920123456789",
    "projectTeam": {
      "projectNumber": "920123456789",
      "team": "editors"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-viewers-920123456789",
    "projectTeam": {
      "projectNumber": "920123456789",
      "team": "viewers"
    },
    "role": "READER"
  },
  {
    "entity": "user-00b4903a97b759d775f7fad56bd472a7b7418f0a13de0e27fa8ae72f86d8c8a2",
    "entityId": "00b4903a97b759d775f7fad56bd472a7b7418f0a13de0e27fa8ae72f86d8c8a2",
    "role": "OWNER"
  }
]

```

Is this a new issue or perhaps my default service account's scope wasn't setup properly? If so, how do I fix it?
