### ISSUE TITLE
[Documentation Issue] Reference manual lacks the spec of Pub/Sub Message class

### ISSUE THREAD

**Issue by miyakawataku** [GoogleCloudPlatform/gcloud-python#1199]
Page Name: index
Release: 0.8.0

The reference manual lacks the specification of Pub/Sub Message class.

http://googlecloudplatform.github.io/gcloud-python/stable/pubsub-usage.html

**Comment by tseaver** [comment]
Thanks for the report!  I will look into this issue today.

**Comment by dhermes** [comment]
Resolved in #1211
