### ISSUE TITLE
Support distinct projection queries?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1202]
Related to #304 (https://github.com/GoogleCloudPlatform/gcloud-python/issues/304#issuecomment-150268858)

and 

http://stackoverflow.com/questions/33283759/how-to-do-a-gql-query-using-gcloud-python

How do we do the equivalent of GQL: `SELECT DISTINCT p FROM Kind` ?

/cc @Fkawala

**Comment by jgeewax** [comment]
@pcostell : Can the API even allow this type of thing?

**Comment by tseaver** [comment]
Datastore queries [take a `projection` parameter](https://github.com/GoogleCloudPlatform/gcloud-python/blob/95ec91645c08f37b27960ceb6efd7ec7d96e172d/gcloud/datastore/query.py#L52), which is a list of the fields to be returned.  AFAICT, the API don't expose any way to do any "summary" operations (`DISTINCT`, `COUNT`, `SUM`, etc.) except to pull the values back and munge them client-side.

**Comment by pcostell** [comment]
Sorry OOO so short reply:
Yes it can. In `v1beta2` you can use `group_by`, in `v1beta3` you can use `distinct_on`.

`SELECT DISTINCT p FROM Kind` == `SELECT p FROM KIND GROUP BY p`.

Aggregation ops aren't supported because they would require full scans of the data to answer. `DISTINCT` however can be implemented efficiently.

**Comment by Fkawala** [comment]
@pcostell so the parameter `group_by` of object `Query` does what I expect, and there is not any interest (speed / efficiency ?) to use GQL `SELECT DISTINCT` ? Thanks.

**Comment by pcostell** [comment]
@Fkawala -- yes, using `group_by` on all your projection properties is the exact same as using `SELECT DISTINCT` IN GQL. (In fact that is how GQL `DISTINCT` is implemented.

**Comment by dhermes** [comment]
@pcostell I'm closing this out. It seems support already exists. LMK if I'm mistaken.
