### ISSUE TITLE
Allow users to choose transaction isolation level?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1204]
I believe we currently only support the default transaction isolation level for Datastore (`snapshot`). Could we figure out a way to allow people to choose a `serializable` transaction?

See https://cloud.google.com/datastore/docs/apis/v1beta2/datasets/beginTransaction

**Comment by tseaver** [comment]
[`Connection.begin_transaction`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/2ef163918511f149415d32c32b74b6c9a23cb526/gcloud/datastore/connection.py#L270) already takes a `serializable` argument:  we just need to plumb that through to [`Transaction.__init__`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/2ef163918511f149415d32c32b74b6c9a23cb526/gcloud/datastore/transaction.py#L103)/[`Transaction.begin`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/2ef163918511f149415d32c32b74b6c9a23cb526/gcloud/datastore/transaction.py#L129).

**Comment by tseaver** [comment]
... and [`Client.transaction`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/2ef163918511f149415d32c32b74b6c9a23cb526/gcloud/datastore/transaction.py#L129).
