### ISSUE TITLE
[Documentation Issue] gcloud.pubsub.message.Message isn't documented!

### ISSUE THREAD

**Issue by ddopson** [GoogleCloudPlatform/gcloud-python#1211]
Internal Username: ddopson@google

Page Name: pubsub-subscription
Release: 0.8.0

The documentation for the `pull` method says that it returns instances of `gcloud.pubsub.message.Message`.  That type doesn't link anywhere and I can't find any documentation of the `Message` type.  This makes it really hard to use the API.

**Comment by ddopson** [comment]
This is a 404: https://cloud.google.com/pubsub/reference/rest/google/pubsub/v1beta2/PubsubMessage

(linked in the comments in /gcloud/pubsub/message.py)

**Comment by dhermes** [comment]
@tseaver PTAL

Thanks @ddopson!

**Comment by dhermes** [comment]
Seems a few of the other links (e.g. https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/subscriptions) are also 404. @tmatsuo Did the docs move?

**Comment by dhermes** [comment]
@tseaver `$ git grep v1beta2` gives a bunch of "old" links from before we moved from `v1` to `v1beta2` (I think?).

It seems the translation is

```
    https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/topics/get
--> https://cloud.google.com/pubsub/reference/rest/v1     /projects.topics/get
```

Also one copy-pasta (again, not 100%):
```
gcloud/resource_manager/project.py:        https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/projects/get
```

**Comment by dhermes** [comment]
Sent #1215 to at least get `Message` documented but am holding off on closing this until we can fix all the 404's. Don't have enough bandwidth (literally slow internet) to deal with right now.

@ddopson Once #1215 gets merged you can see the "latest" docs at https://googlecloudplatform.github.io/gcloud-python/latest/ (the latest release will be at `stable` instead of `latest`).

**Comment by ddopson** [comment]
Yay!  Always happy to spend time reporting issues when they get looked at and fixed. :-)

Thanks!

**Comment by dhermes** [comment]
Sorry it took to long to resolve. Thanks for being observant!
