### ISSUE TITLE
Merge gcloud_bigtable as gcloud.bigtable

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1212]
/cc @dhermes 

Ideally, the way this would work is:

```
$ pip install gcloud  # This should work even if I don't have gRPC
$ python
>>> from gcloud import bigtable
Exception: Bigtable requires that you have gRPC installed.
  Follow the instructions here: http://github.com/GoogleCloudPlatform/gcloud-python/docs/install-grpc.md
```

Instructions would say something like:

> First, install gRPC core.
> - For Debian, ...
> - For Ubuntu, ...
> - For Mac, ...
> - For Windows, ...
> - For some other OS, ...
> 
> After that, you need the Python gRPC package:
> ```
> $ pip install grpc
> ```
>
> Once that's done, you should be able to run `from gcloud import bigtable` :)
>
> If you're still having problems, try running `python -m gcloud.check_grpc` to diagnose the issue.

The `check_grpc` script would give us info on the user's set-up so we can help figure out what's broken...

```
$ pip install gcloud
$ python -m gcloud.check_grpc
Python: [details about Python]
Platform: [some details about the platform]
gcloud-python: [...]
libssl: [...]
gRPC core: [...]
gRPC Python package: [...]
```

---

Stuff we still need to do:

- [ ] Write gRPC installation instructions (or include ones from the gRPC repo) specific to gcloud-python
- [ ] Travis needs to be able to run our system tests (requires gRPC on the test server)

**Comment by dhermes** [comment]
@jgeewax Did you forget about the discussion about this in #1159?

**Comment by jgeewax** [comment]
Totally related, however the goal hasn't changed, right?

```
$ sudo apt-get install grpcio
$ pip install gcloud grpc
$ python
>>> from gcloud import bigtable
>>> # Happiness
```

The layout of the distribution (#1159) is the implementation detail, right?

**Comment by dhermes** [comment]
True that. Good call. Thanks for bringing me back down to earth. We really should revive the conversation in #1159.

**Comment by jgeewax** [comment]
It sounds to me that resolving #1159 is a big task, and not something we can do all that quickly, however we have some folks really pushing to make gcloud-python look (somewhat) like how this issue describes it before the end of the year.

@dhermes : Can you help me understand:

1. What happens if we do #1159 later, and focus on this issue for today
1. What steps we need to do to accomplish *this* issue (without doing #1159)

**Comment by dhermes** [comment]
We can totally do #1159 later and merge it in now (it still needs to be reviewed somewhere). Still have #1154 in flux ready to continue the merge in if we decide to go that route.

**Comment by dhermes** [comment]
This is in progress now

**Comment by jgeewax** [comment]
Just FYI, I'm seeing the following installation work on Ubuntu, haven't tested on Mac yet:

```sh
$ sudo apt-get install -y python-pip
$ sudo pip install -U six
$ sudo pip install https://testpypi.python.org/packages/source/g/grpcio/grpcio-0.13.0rc2.tar.gz#md5=40bb88e3184dc4fba0da6939d8756041
```

It's a pre-release, but if we can call it "good" then this means we can add gRPC as a dependency, right?

**Comment by dhermes** [comment]
Once it's on PyPI, I'd say yes (but haven't verified).

**Comment by dhermes** [comment]
I just installed it but haven't verified it works yet (the 0.13 code is different from the beta code which was different from the alpha code).

**Comment by vinays** [comment]
@dhermes do you have a rough estimate of when will gcloud upgrade to grpcio==0.13 ? Is there an open issue for it that I can subscribe?

**Comment by dhermes** [comment]
Will take another stab at it today. I tried before and was stymied by the fact that the `grpc_python_plugin` is not install-able anywhere. Building from source isn't too bad for a one-off though.

**Comment by dhermes** [comment]
@vinays FYI #1532 is out.

**Comment by dhermes** [comment]
The merge is done, everything from here is just clean-up.
