### ISSUE TITLE
Add note that Windows users will need Microsoft Visual C++ 9.0 compiler

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1218]
When I'm installing gcloud, I need to compile stuff for the crypto libraries.

As a result, the install fails and I get a message telling me to go to aka.ms/vcpython27 which links to http://www.microsoft.com/en-us/download/details.aspx?id=44266

After I install that, everything works great.

**Comment by dhermes** [comment]
@jgeewax As in #1124 we may be able to dodge this by distributing an MSI built by AppVeyor

**Comment by jgeewax** [comment]
Yep, I think that's probably a good plan. Just wanted to put this down in an issue. Let's leave this open until we get the MSI all set.

**Comment by dhermes** [comment]
SGTM

**Comment by dhermes** [comment]
This is no longer true since we now depend on pyOpenSSL. (Still need #1124 to be done)
