### ISSUE TITLE
Refactor apitools legacy 'handle_http_exceptions' for sanity.

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1223]
The [apitools code which handles the various errors being raised when making a request](https://github.com/tseaver/gcloud-python/blob/streaming-strip_unused_features/gcloud/streaming/http_wrapper.py#L225-L276) is seriously awkward, and likely a bug magnet.

**Comment by dhermes** [comment]
As [mentioned][1] in #1210, this should resolve the bare exception clauses as well.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1210/files#r45370100
