### ISSUE TITLE
Strip excess custom exceptions from 'gcloud.streaming'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1227]
Many (all, maybe) of the custom exception types in `gcloud.streaming.exceptions` are providing no value, and could be replaced with either standard exceptions (`ValueError`, `TypeError`, etc.), or one of our existing types mapping particular HTTP response codes.

Strip out as many of the custom types as seems feasible, and move the remainder to `gcloud.exceptions`.

**Comment by dhermes** [comment]
:+1:
