### ISSUE TITLE
Make sure examples in bigquery-usage are up to date.

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1259]
For example, there is a string

```python
results = client.run_sync_query(query, timeout_ms=1000)
```

but `run_sync_query` [does not have][1] `timeout_ms` as an optional argument.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/13f8693d6bd135ec4a9e6289ce46f2e89bc185fc/gcloud/bigquery/client.py#L173

**Comment by dhermes** [comment]
Obviously related to #212, but maybe not worth digging deep on that?

**Comment by dhermes** [comment]
@tseaver Re-opening this after #1392, #1397, #1398 and #1399 were filed. Can you do another pass over `bigquery-usage`?

**Comment by tseaver** [comment]
#1469 addressed the remaining open issues.
