### ISSUE TITLE
Explore adding support for Task Queues

### ISSUE THREAD

**Issue by lucemia** [GoogleCloudPlatform/gcloud-python#128]
it will be nice to support pull queue in gcloud-python

detail at: [appengine pull queue](https://developers.google.com/appengine/docs/python/taskqueue/rest/)

**Comment by jgeewax** [comment]
This API is still in Alpha -- and is likely to change, so we're going to punt on this until things start to solidify a bit for their REST API.

**Comment by dhermes** [comment]
@jgeewax It seems like the Task Queues API is Pub/Sub but locked inside of App Engine.

**Comment by jgeewax** [comment]
Yes I think we should close this out for now. We may expose the Task Queues API outside of GAE, but unlikely to do so in the short term. Until it's available from outside of App Engine, there's not a whole lot we can (or should) do.
