### ISSUE TITLE
[Documentation Issue] Authentication page needs to be updated to reflect the new Credentials UI

### ISSUE THREAD

**Issue by vsubramani** [GoogleCloudPlatform/gcloud-python#1286]
Page Name: gcloud-auth
Release: 0.8.0

The Credentials UI in Google Developers Console has been updated. Some of the things to be updated:

-The nav hierarchy has changed. The phrases are different, but still recognizable with the old hierarchy.
-New credentials wizard has been added to help guide the users to the right credential type.

Please update the Getting Started -> Authentication in gcloud-python to reflect these changes.

**Comment by dhermes** [comment]
If you're talking about the images on
http://googlecloudplatform.github.io/gcloud-python/0.8.0/gcloud-auth.html
http://googlecloudplatform.github.io/gcloud-python/latest/gcloud-auth.html
they are hosted in `gcloud-common` ([e.g.][1])

@stephenplusplus are there changes pending in that repo?

[1]: https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-common/master/authentication/enable-apis.png

**Comment by stephenplusplus** [comment]
They've already been updated to match the new console.

Related: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1018, https://github.com/GoogleCloudPlatform/gcloud-common/pull/37

**Comment by dhermes** [comment]
That's what I thought, thanks!
