### ISSUE TITLE
Review Bigtable Table.rename() "not implemented" status when Bigtable API is updated

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1289]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1283#issuecomment-164774587 for discussion

**Comment by sduskis** [comment]
RenameTable was removed in v2.  While it existed in v1, it was never actually implemented.  Good catch.

**Comment by tseaver** [comment]
V1 never actually provided a working implementation;  V2 removes the API altogether.  #1908 removes `Table.rename` on the `bigtable-v2` branch.
