### ISSUE TITLE
Should we compare Entity._meanings in __eq__

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1313]
/cc @tseaver @pcostell

**Comment by tseaver** [comment]
AFAICT, two fields with identical values but different meanings should compare unequal.

**Comment by dhermes** [comment]
OK cool. Will wait on @pcostell before implementing.

**Comment by pcostell** [comment]
Agree here. But I think entity equality should also take into consideration exclude_from_indexes.

Borrowing from @Alfus:

In this case I would suggest that equality/comparison depend on the library implementation. 'smart' equal functions are usually problematic in the long run, so if the object holding the value also holds the meaning, I think meaning should be considered (i.e. equal should mean identical objects). If the object also holds 'exclude_from_indexes', that should also be considered (for example, comparing two entities should take this into consideration).

**Comment by dhermes** [comment]
Thanks. Will implement and ping you on the PR.
