### ISSUE TITLE
How to index Blob property in datastore?

### ISSUE THREAD

**Issue by vinays** [GoogleCloudPlatform/gcloud-python#1332]
Is there a way to index a Blob property (with size < 1500 bytes)? I know about exclude_from_indexes attribute on Entity to remove the properties that would indexed by default. I am looking for a way to white-list properties that are unindexed by default like Blob Property.

In NDB you can do it by setting indexed=True on the property. Is there an equivalent in gcloud/datastore

**Comment by dhermes** [comment]
In `gcloud-python` everything is indexed by default, so you only need to explicitly say when not to. The behavior is not the same as `ndb` since there are no `Property` classes to encapsulate settings.

Maybe I'm misunderstanding. Do you have a specific example code snippet in mind?

**Comment by vinays** [comment]
You are right. It was a bug in my implementation. Thanks for quick response.

**Comment by dhermes** [comment]
Sure thing!
