### ISSUE TITLE
The pubsub library should support detecting and using the Pub/Sub emulator

### ISSUE THREAD

**Issue by hbchai** [GoogleCloudPlatform/gcloud-python#1333]
The Pub/Sub emulator can be run, and the `PUBSUB_HOSTPORT` environment variable exported, with:

```
gcloud beta emulators pubsub start &
$(gcloud beta emulators pubsub env-init)
```

The pubsub libraries should detect this environment variable and connect to the emulator when it is available, similar to how it works for the Datastore emulator.

**Comment by hbchai** [comment]
Moved to gcloud-common: https://github.com/GoogleCloudPlatform/gcloud-common/issues/48

**Comment by dhermes** [comment]
Thanks!
