### ISSUE TITLE
Storage: upload_* does not send properties (need an extra patch)

### ISSUE THREAD

**Issue by sagarrakshe** [GoogleCloudPlatform/gcloud-python#1351]
Not able to set `cache-control` while uploading blobs. I tried this.

    foo_blob = bucket.blob('sample.txt')
    foo_blob.cache_control = 3600
    foo_blob.content_type = 'text/plain'
    foo_blob.upload_from_string('Sample Text')

 But after uploading the property `foo_blob.cache_control` gets set to `None` again.

**Comment by dhermes** [comment]
@sagarrakshe This is actually a bug in `upload_from_string`. For now, you'll want to call `foo_blob.patch()` after uploading to actually patch the properties. We're hoping to address it soon now that @tseaver has brought in `gcloud.streaming`.

**Comment by dhermes** [comment]
Just realized this already exists as #1185. @sagarrakshe Please subscribe to that issue to follow progress on a fix.

**Comment by sagarrakshe** [comment]
Thanks.
