### ISSUE TITLE
[Documentation Issue] Datastore docs don't seem to reference client pattern?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1378]
Page Name: datastore-keys
Release: 0.8.0

Looks like a lot of our snippet documentation is out of date since the client pattern changes. Can we go through and "assume" there's a client at the start of each method, and write docs that fit there? Or re-do the snippets so that they work?

/cc @dhermes : I know we have a separate issue for testing the snippets as doctests (and it was stalled due to ... mocking concerns among other things). Figure this is worth a look.

**Comment by dhermes** [comment]
For posterity, the referred to issue is #212

**Comment by dhermes** [comment]
Also relevant is the discussion in #1141.

**Comment by dhermes** [comment]
I think this was settled by #1352, but am double-checking.
