### ISSUE TITLE
Create snippets for Cloud Datastore page

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-python#1379]
The Datastore docs page has a whole new set of snippets for the "getting started" guide and for the concepts snippets.

Can we implement all the necessary snippets (~50) in the [docs github](https://github.com/GoogleCloudPlatform/python-docs-samples)?

Whoever plans on owning this can ping me via email and I can give you all the necessary instructions / access to the staging docs.

**Comment by dhermes** [comment]
@waprin and @jonparrott own that

**Comment by dhermes** [comment]
@jonparrott Care to chime in?

**Comment by jonparrott** [comment]
Following up via email. Shouldn't be a problem.

**Comment by dhermes** [comment]
@jonparrott Closing this out since it seems handled. If you think it needs to be tracked here, feel free to re-open. If you add an issue to https://github.com/GoogleCloudPlatform/getting-started-python or elsewhere feel free to link to it here?
