### ISSUE TITLE
[Documentation Issue] deprecated method

### ISSUE THREAD

**Issue by icrtiou** [GoogleCloudPlatform/gcloud-python#1380]
Page Name: bigquery-usage
Release: 0.8.0

In the documentation of bigquery usage -> insert data (sync)

```python
job = table.load_from_file(
    file_obj, source_format='CSV', skip_leading_rows=1,
    write_disposition='truncate')
```

According to your table doc, the method `load_from_file` is not supported anymore.

**Comment by dhermes** [comment]
In the [latest][1] docs, `load_from_file` has been removed. Thanks.

(We need to just cut a new release already.)

[1]: http://googlecloudplatform.github.io/gcloud-python/latest/bigquery-usage.html

**Comment by icrtiou** [comment]
thank you. I'll stick to latest from now on.

**Comment by dhermes** [comment]
Unfortunately `latest` is unreleased, so comparing it to `stable` just gives an idea of what will be coming. The alternative is that you could install from `HEAD` but we don't require (or even really recommend) doing that. Though some people still do.

**Comment by icrtiou** [comment]
ok, got it.
