### ISSUE TITLE
[Documentation Issue] Client.jobs() not implemented in BigQuery

### ISSUE THREAD

**Issue by evmin** [GoogleCloudPlatform/gcloud-python#1392]
Page Name: bigquery-usage
Release: ffe5869

```python
jobs = client.jobs()  # API request
```

Error:

```python
AttributeError: 'Client' object has no attribute 'jobs'
```

**Comment by dhermes** [comment]
@evmin Thanks a lot for filing this!

**Comment by evmin** [comment]
@dhermes - No issues!

Pardon me asking, but checking the bigquery client code from the 0.8.0 version I do not see any method resembling job listing. 

How do I get the job list?
What would be the right forum to ask this sort of questions?

Thank you!

**Comment by dhermes** [comment]
@evmin It has not been implemented yet. @tseaver Has handled the BigQuery implementation so he can say more.

This is the right forum to ask this sort of question, since the question is a "bug" issue in our docs.

**Comment by evmin** [comment]
Thank you.

The reason I have asked about the forum was that I have another question - in regards of the positioning of this SDK vs the older libs (both Java and Python). Should I be aiming at using this SDK going forward?
It is much easier to deal with I admit.

**Comment by dhermes** [comment]
1. Short answer, yes. For APIs that we support, using this library is the "best" way to use them in Python.
1. Is [`google-api-python-client`][1] the older lib you are referring to?
1. From our [README][2], "If you need support for other Google APIs, check out the Google APIs Python Client library."
1. This project is just the `gcloud-python` library, not the `gcloud` SDK.

[1]: https://github.com/google/google-api-python-client
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/ffe5869aa7c31bd82483e4d52adacbf83cf0fd69/README.rst

**Comment by ollikaven** [comment]
@dhermes Are you planning to support other APIs in the future?

**Comment by dhermes** [comment]
Yes, though they'll be cloud APIs.

@jgeewax Would it be worth having a roadmap doc?

**Comment by jgeewax** [comment]
I think that's tricky... I'd love to share future plans and all that, but I hesitate to share commitments externally when it's very possible that things could change rapidly. 

If lots of people are asking for this, I think we should consider it more strongly... Is this a common question? Do we have any ballpark on how many people are hesitating on using gcloud-python due to a lack of a roadmap doc?

**Comment by tseaver** [comment]
cf965c4e8b82818bbc4aa4e8524ed3dee905e64b changed `docs/bigquery-usage.rst` to show using the implemented `Client.list_jobs` method.
