### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by ollikaven** [GoogleCloudPlatform/gcloud-python#1397]
Page Name: bigquery-usage
Release: 0.8.0

The example here is outdated https://googlecloudplatform.github.io/gcloud-python/stable/bigquery-usage.html#exporting-data-async. The example gives error: AttributeError: 'Table' object has no attribute 'export_to_storage'

The first comment in stackoverflow also mentions that 'export_to_storage' never existed - it's only ever referenced in the documentation. 

http://stackoverflow.com/questions/34791901/exporting-bigquery-table-to-gcs-using-gcloud-python

**Comment by dhermes** [comment]
It's been updated in the `latest` docs:
https://googlecloudplatform.github.io/gcloud-python/latest/bigquery-usage.html#exporting-data-async

Thanks for reporting!

Let me know if there is still something that needs to resolve and we can re-open. We hope to cut a release soon to get this code pushed to PyPI.

**Comment by ollikaven** [comment]
Thanks for the reply.

The new documentation is missing setting the dataset and will give an error when setting a table: NameError: name 'dataset' is not defined

Also it prints nothing on line: job.job_id and job.type gives an error:

>>> job.job_id
>>> job.type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ExtractTableToStorageJob' object has no attribute 'type'

**Comment by dhermes** [comment]
1. I filed an issue for the `job.type` issue
1. `dataset` is not defined because the snippet never defines a dataset. You can proceed as with other snippets in the doc: `dataset = client.dataset('dataset_name')`.
1. `job_id` is also used incorrectly in that doc, filed #1399 as well
