### ISSUE TITLE
Job.job_id is populated before job creation in bigquery-usage

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1399]
The [`job_id`][1] property uses the `_properties` returned from the server. It seems the original intent was a `uuid.uuid4()` on instance creation.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/ffe5869aa7c31bd82483e4d52adacbf83cf0fd69/gcloud/bigquery/job.py#L150-L156

**Comment by tseaver** [comment]
#1469 removes the `job_id` property altogether:  it is redundant to the user-supplied `name`.

**Comment by dhermes** [comment]
:+1: That PR removes it from the docs, but not from the object, is that correct?

**Comment by tseaver** [comment]
I meant to remove it from the object as well.  (looks)  Nope, missed that it was being covered indirectly via the client.
