### ISSUE TITLE
Drop support for Python 3.3, add support for Python 3.5

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1410]
Python 3.3 is no longer cool (according to [Django][1] project)

[1]: https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django

**Comment by jgeewax** [comment]
It also might be worthwhile to codify this the same way that Django has...?

**Comment by dhermes** [comment]
We currently cite reasons for which versions we use in `CONTRIBUTING` and I was planning on updating that. Is that what you mean?
