### ISSUE TITLE
BigQuery dataset.list_tables() fails when the dataset is empty

### ISSUE THREAD

**Issue by evmin** [GoogleCloudPlatform/gcloud-python#1419]
Good day.

Getting this exception when the BigQuery dataset contains no tables:

```python
  File "/Library/Python/2.7/site-packages/gcloud/bigquery/dataset.py", line 507, in list_tables
    for resource in resp['tables']]
KeyError: 'tables'
```

Mac OS X El Capitan. gcloud 0.8.0

**Comment by dhermes** [comment]
Thanks @evmin!

**Comment by dhermes** [comment]
I reproduced with

```python
>>> from gcloud import bigquery
>>> client = bigquery.Client()
>>> dataset_name = 'foo_bar_baz'
>>> dataset = client.dataset(dataset_name)
>>> if dataset.exists():
...     raise ValueError('Expected a new dataset')
...
>>> dataset.create()
>>> dataset.exists()
True
>>> all_tables, token = dataset.list_tables()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud/bigquery/dataset.py", line 553, in list_tables
    for resource in resp['tables']]
KeyError: 'tables'
>>> dataset.delete()
>>>
```

at 2323e1a110d240545bf2950e18e5ccefb75d01f1

**Comment by tseaver** [comment]
What is the content of `resp` at that point?  The [API docs](https://cloud.google.com/bigquery/docs/reference/v2/tables/list#tables) don't indicate that the `tables` key is optional.  We can defend against it, but shouldn't have to, IMHO.

**Comment by dhermes** [comment]
@tseaver I sent out a fix for this already.

**Comment by tseaver** [comment]
Oops, my bad.

**Comment by dhermes** [comment]
@tseaver Here is the full payload

```json
{
  "etag": "\"AMpOK...\"", 
  "kind": "bigquery#tableList", 
  "totalItems": 0
}
```

Anything issue there before I merge the fix?

**Comment by tseaver** [comment]
Nope, I was just "arguing with the ref":  like it would have hurt the back-end to send the extra 13 bytes. :(

**Comment by dhermes** [comment]
Gotcha.
