### ISSUE TITLE
Make master a protected branch

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1423]
https://help.github.com/articles/configuring-protected-branches/

@jgeewax WDYT of this?

**Comment by jgeewax** [comment]
Yep, I think it's a good call. To be honest all of our repo's should have master protected. Want to move over to gcloud-common for wider discussion?

**Comment by dhermes** [comment]
Filed https://github.com/GoogleCloudPlatform/gcloud-common/issues/53

**Comment by dhermes** [comment]
I set `master` as protected

![screen_shot_002](https://cloud.githubusercontent.com/assets/520669/12666006/5ea7fa4c-c5f1-11e5-
8df5-8a0b8e484bcd.png)

but held of on setting a [status][1].

[1]: https://developer.github.com/v3/repos/statuses/
