### ISSUE TITLE
resource manager CAN be used with service account credentials

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-python#1426]
Not implemented errors on constructing clients from service accounts are inaccurate. Cloud Resource Manager CAN be called with service accounts. Those methods should be implemented.

**Comment by dhermes** [comment]
@elibixby Thanks for the update. When the original implementation (#1083) was done, only user accounts worked. Verifying now and then will send a PR.

**Comment by dhermes** [comment]
Confirmed. This also opens it up so that we can write system tests. Any suggestions for things that should be tested?

**Comment by elibixby** [comment]
Yeah. It didn't when I originally tried it either. I've been building on
top of it and following changes, just haven't updated veneer which I should
have contributed too ;-)

A couple other notes:

1. projects().get() will no longer give 404 for missing projects (in fact I
confirmed with Elysium team that they have no plans to support any sort of
"exists" method)
Instead, perhaps create project should take some sort of "template" object
that you can stick a random value in to get a valid project id?

2. Service accounts need to be whitelisted to create projects for now.

Stay tuned for more updates when org nodes come down the pipes.

**Comment by elibixby** [comment]
To update, projects().get() now gives 403 for all projects a user does not
have access to. There was concern from the Elysium team of users scanning
the entire project space, and project id is PII evidently.
