### ISSUE TITLE
Missing content type option for signed blob URL

### ISSUE THREAD

**Issue by savvykang-bnnjack** [GoogleCloudPlatform/gcloud-python#1429]
I need to explicitly specify a content type for signed URL, but I found `Blob.generate_signed_url` method does not expect keyword argument for content type.

The function `gcloud.credentials.generate_signed_url` optionally expects content type. Can we fix this mismatching?

**Comment by dhermes** [comment]
Thanks for filing! I just added some arguments in #1409 and didn't notice that it wasn't there!

**Comment by savvykang-bnnjack** [comment]
@dhermes super fast follow-up, thanks!

**Comment by savvykang-bnnjack** [comment]
@dhermes I just read your commit and looks awesome. When will 0.9.0 release be rolled out?

**Comment by dhermes** [comment]
Hopefully today.

**Comment by cyluss** [comment]
Following up with personal GitHub account.
