### ISSUE TITLE
test_upload_from_file_w_bound_client_multipart fails on Windows

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1434]
Introduced in #1318

**Comment by tseaver** [comment]
@dhermes The [AppVeyor page for the failure](https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.55.master) shows just a couple of flickering blue dots (both FF and Chrome).

**Comment by dhermes** [comment]
My [original comment][1] points to a [broken build][2].

```
```
AssertionError: Lists differ: ['full_name,age,joined', '', 'Phred Phlynt[185 chars]27,'] != [u'full_name,age,joined', u'', u'Phred Phl[199 chars] u'']
 
Second list contains 1 additional elements.
First extra element 9:
 
 
- ['full_name,age,joined',
+ [u'full_name,age,joined',
?  +
 
-  '',
+  u'',
?  +
 
-  'Phred Phlyntstone,32,2015-07-24 19:53:19.006000+00:00',
+  u'Phred Phlyntstone,32,2015-07-24 19:53:19.006000+00:00',
?  +
 
-  '',
+  u'',
?  +
 
-  'Bharney Rhubble,33,2015-07-24 19:53:20.006000+00:00',
+  u'Bharney Rhubble,33,2015-07-24 19:53:20.006000+00:00',
?  +
 
-  '',
+  u'',
?  +
 
-  'Wylma Phlyntstone,29,2015-07-24 19:53:21.006000+00:00',
+  u'Wylma Phlyntstone,29,2015-07-24 19:53:21.006000+00:00',
?  +
 
-  '',
+  u'',
?  +
 
-  'Bhettye Rhubble,27,']
?                       ^
 
+  u'Bhettye Rhubble,27,',
?  +                     ^
 
+  u'']
 
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1318#issuecomment-176942213
[2]: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.54.master

**Comment by tseaver** [comment]
Thanks for copying that in:  I cannot see anything on the earlier AppVeyor build page, either (maybe a permissions issue?)

**Comment by tseaver** [comment]
Can you post the name / line # of the failing testcase?

**Comment by dhermes** [comment]
Not sure why you can't see it, I checked in an incognito Window and see it just is

The name of the failing test is `test_upload_from_file_w_bound_client_multipart` (in the name of this issue, and in my original comment).

```python
======================================================================
FAIL: test_upload_from_file_w_bound_client_multipart (gcloud.bigquery.test_table.TestTable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gcloud-python\gcloud\bigquery\test_table.py", line 1403, in test_upload_from_file_w_bound_client_multipart
    self.assertEqual(payload_lines, body_lines)
```

**Comment by cyluss** [comment]
There are two different problems in this test case.

1. Currently the test case decodes request body into unicode, then comparing with the result from standard library mime parser. According to the Appveyor output and local test running, parser payloads seem to have different data type among different platforms. This affects Python 2.x.
2. There is a trailing newline in the request body while parser payload is not. This affects both Python 2.x and Python 3.x.

**Comment by cyluss** [comment]
My questions are:
1. Is it reasonable to validate HTTP request using email document parser?
2. Will adding external library for validating HTTP request format help this situation?

**Comment by dhermes** [comment]
Thanks for tackling this! The reason we use the email parser is because multi-part HTTP requests conform to formats supported in that library. We don't need another library to handle a trailing newline.
