### ISSUE TITLE
gcloud.datastore.demo seems broken

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1443]
Outside of the datastore demo throwing errors, it looks like we added a license header to it, which doesn't get ignored by our demo runner (and definitely confused me).

If we're going to keep these, can we fix them up?
If not, can we delete them?

**Comment by dhermes** [comment]
- License headers added in #416
- #1049 is an aspirational goal
- I'm in favor of deleting since @jonparrott and @waprin are providing high quality tested snippets

**Comment by dhermes** [comment]
@jgeewax I just ran both demos and they work fine. Are you sure you were running them from the latest `master`?

FWIW I'm still in favor of deleting (even though they work fine). LMK what you think.
