### ISSUE TITLE
Project inference is broken under Python 3.5.1

### ISSUE THREAD

**Issue by jlowin** [GoogleCloudPlatform/gcloud-python#1470]
Project inference takes place in [_determine_default_project()](https://github.com/GoogleCloudPlatform/gcloud-python/blob/91be6938b26ba9198082f457ae37fba81b8f5ea0/gcloud/_helpers.py#L189), which hands off to [_compute_engine_id()](https://github.com/GoogleCloudPlatform/gcloud-python/blob/91be6938b26ba9198082f457ae37fba81b8f5ea0/gcloud/_helpers.py#L151). That returns the correct value -- but as `bytes`. The `Client` class checks if the project value is a `str` (using `six.string_types`) and raises an error because it is not (that code is [here](https://github.com/GoogleCloudPlatform/gcloud-python/blob/91be6938b26ba9198082f457ae37fba81b8f5ea0/gcloud/client.py#L144)).

**Comment by dhermes** [comment]
Really appreciate the bugs @jlowin!

**Comment by jlowin** [comment]
Happy to help :)

**Comment by dhermes** [comment]
@jlowin Working on a fix now. Sorry for the delay!
