### ISSUE TITLE
list_subscriptions does not work properly

### ISSUE THREAD

**Issue by bitcpf** [GoogleCloudPlatform/gcloud-python#1485]
`list_subscriptions()` works but `list_subscriptions(topic_name = 'topic_name')` does not work properly

```python
>>> from gcloud import pubsub
>>> client = pubsub.Client(project = 'my_project')
>>> client.list_subscriptions(topic_name = 'my_topic')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/client.py", line 131, in list_subscriptions
    for resource in resp['subscriptions']]
  File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/subscription.py", line 68, in from_api_repr
    topic_path = resource['topic']
TypeError: string indices must be integers
```

**Comment by tseaver** [comment]
ATM, `topic_name` is the third positional argument:  you need to call it as a named parameter:

```python
client.list_subscriptions(topic_name='topic_name')
```

@jgeewax, @dhermes I'm reading this issue as a request to make `topic_name` the first positional argument.  Opinions?

**Comment by dhermes** [comment]
:+1:

**Comment by bitcpf** [comment]
Sorry, what I really want to say is I wrote the command as:

subscription, next_page_tokens = client.list_subscriptions(topic_name = 'topic_name')

It does not work. And the issue is this line:
        subscriptions = [Subscription.from_api_repr(resource, self,
                                                    topics=topics)
                         for resource in resp.get('subscriptions', ())]

The code pass an empty value of resource (maybe) to subscriptions.

**Comment by dhermes** [comment]
@tseaver Have you reproduced?

**Comment by dhermes** [comment]
@tseaver I reproduced:

```python
>>> import gcloud.pubsub
>>> from gcloud import _helpers
>>> from gcloud.environment_vars import TESTS_PROJECT
>>> _helpers.PROJECT = TESTS_PROJECT
>>> C = gcloud.pubsub.Client()
>>> C.project
'FOOOBAR'
>>> C.list_subscriptions()
([], None)
>>> C.list_topics()
([], None)
>>> T = C.topic('hi-mom')
>>> T.create()
>>> S = T.subscription('this-is-mine')
>>> S.create()
>>> C.list_topics()
([<gcloud.pubsub.topic.Topic object at 0x7f7c21812310>], None)
>>> C.list_subscriptions()
([<gcloud.pubsub.subscription.Subscription object at 0x7f7c21812390>], None)
>>> C.list_subscriptions(topic_name=T.name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud/pubsub/client.py", line 131, in list_subscriptions
    for resource in resp.get('subscriptions', ())]
  File "gcloud/pubsub/subscription.py", line 71, in from_api_repr
    topic_path = resource['topic']
TypeError: string indices must be integers
```

**Comment by dhermes** [comment]
```python
In [16]: %debug
> .../gcloud-python/gcloud/pubsub/subscription.py(71)from_api_repr()
     69         if topics is None:
     70             topics = {}
---> 71         topic_path = resource['topic']
     72         topic = topics.get(topic_path)
     73         if topic is None:

ipdb> resource
u'projects/omega-moonlight-697/subscriptions/this-is-mine'
```

**Comment by dhermes** [comment]
This is in contrast to what the output looks like without the topic name:

```json
{
  "subscriptions": [
    {
      "topic": "projects/omega-moonlight-697/topics/hi-mom", 
      "ackDeadlineSeconds": 10, 
      "pushConfig": {}, 
      "name": "projects/omega-moonlight-697/subscriptions/this-is-mine"
    }
  ]
}
```

**Comment by tseaver** [comment]
OK, I see the issue:  [`projects.subscriptions/list'](https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions/list) is documented to return the full `Subscriptions` resource, whereas [`projects.topics.subscriptions/list`](https://cloud.google.com/pubsub/reference/rest/v1/projects.topics.subscriptions/list) is documented to return only a list of subscription URLs.

The API design choice here is utterly bogus, but we have to work around it.

**Comment by tseaver** [comment]
Given the disparity, I would prefer to handle topic-based subscriptions by adding a `list_subscriptions` method to the `Topic` class.

**Comment by tseaver** [comment]
@bitcpf Thanks for the report!

**Comment by dhermes** [comment]
:+1: with separate methods @tseaver

**Comment by tseaver** [comment]
@dhermes see #1580 for the implementaion.
