### ISSUE TITLE
Add support for batch requests in gcloud.storage

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#15]
Or wait for the new primitive client that simplifies this.

**Comment by tseaver** [comment]
OK, here's a plan:

- [ ] Move `datastore.batch._Batches` (which is just a thread-local stack) up to `gcloud._localstack`. #622
- [ ] Add `storage.batch.Batch`, paralleling `datastore.batch.Batch`, and exposing the same methods as `storage.connection.Connection`.  This class will "store up" the mutations and generate the `multipart/mixed` payload defined in [Sending Batch Requests](https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch).  As with the `datastore` variant, this `Batch` should be usable as a context manager, as well as in "imperative" mode (where it will need to be passed into the buckets as their connection?)
- [ ] Update `storage.api` to look first for an active batch, falling back to the implied default connection Likewise, `Bucket.__init__()` should pick up the active batch, but fall back (per #621).

**Comment by dhermes** [comment]
SGTM.

**Comment by tseaver** [comment]
@dhermes, I'll hold off on the third point until your work on #632 clarifies (I think we would be stepping all over each other there).

**Comment by dhermes** [comment]
OK cool. I sent the first PR of the oncoming flood (I haven't written the flood yet, I just know it's coming).

**Comment by dhermes** [comment]
@tseaver I [checked][1] and verified that `GET` requests can be sent as part of batch requests.

In order to accommodate this, we'd need to create a container object (maybe called `Future`, as in `ndb`) that we could hold onto and then populate when the batch returns.

For example:

```python
>>> future_bucket = batch.get_bucket('BOGUS.NAME')
>>> future_bucket
<FutureBucket>
>>> future_bucket.get()
Traceback (most recent call last):
...
ValueError: Not ready yet.
>>>
>>> batch.finish()
>>> bucket = future_bucket.get()
>>> bucket
<Bucket: BOGUS.NAME>
```

[1]: https://gist.github.com/dhermes/223cbd802cb3e6f3d7c2
