### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by MartinSahlen** [GoogleCloudPlatform/gcloud-python#1520]
Page Name: _modules/gcloud/bigquery/client
Release: 0.10.1

There is a discrepancy between the docs (https://googlecloudplatform.github.io/gcloud-python/stable/bigquery-usage.html) and the current implementation. The SchemaField class constructer uses the keyword argument __field_type__, not __type__ as the documentation currently states.

**Comment by dhermes** [comment]
Thanks for the heads up!

**Comment by MartinSahlen** [comment]
Nice! You also caught the int -> integer error as well. Its always fun when youre testing stuff and copy paste from the docs break. Thanks for fixing it so fast!

**Comment by dhermes** [comment]
Thanks for reporting. It's no fun to use broken docs. We've been meaning to use `doctest` to make sure they are always current (#212) and hopefully will get there soon.
