### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by deesix** [GoogleCloudPlatform/gcloud-python#1544]
Page Name: bigquery-usage
Release: 0.10.1

The code snippet for creating a schema is incorrect:

...     SchemaField(name='full_name', type='string', mode='required'),

Should be 

...     SchemaField(name='full_name', field_type='string', mode='required'),

**Comment by dhermes** [comment]
Thanks for filing! It's great to have people chime in on broken docs.

Was filed as #1520 and #1521 fixes it!
