### ISSUE TITLE
What should be done about non-atomicity of Table.counter_set()

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1549]
See #1541 for discussion.

There is a [note][1] from the HappyBase source code

> Note that application code should *never* store a incremented or decremented counter value directly; use the atomic `Table.counter_inc` and `Table.counter_dec` methods for that.

and we just went one step further and just made `Table.counter_set()` a not implemented method (it raises `NotImplementedError` when called).

[1]: https://github.com/wbolster/happybase/blob/9cbd718c10a3089f234f1eac1236b631e1f8e7cd/happybase/table.py#L531-L534

**Comment by tseaver** [comment]
Similar to #1524?

**Comment by dhermes** [comment]
Nope. This is an issue of a single request not being transactional while that one is the issue of having to send `N + 1` requests at once to match an HBase / Thrift feature.

**Comment by tseaver** [comment]
@dhermes Could we map `happybase.table.Table.counter_set` onto a `CheckAndMutateRow` request, where the predicate checked that there was no value alraeady set?  We would leave `false_mutations` empty in that case.

**Comment by dhermes** [comment]
We should verify that that would actually be atomic though. I'd guess the "check" and "mutate" don't actually happen atomically (would be a high cost to pay for every `CheckAndMutateRow` made).

**Comment by tseaver** [comment]
The [docs for the `Bigtable` data interface](https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.Bigtable) say:

```
rpc CheckAndMutateRow(CheckAndMutateRowRequest) returns (CheckAndMutateRowResponse)

Mutates a row atomically based on the output of a predicate Reader filter.
```

**Comment by dhermes** [comment]
@tseaver It could mean that the set of mutations are either all applied or none, not implying anything about the atomicity of the "check and mutate" as a single operation.

@mbrukman @tswast can you weigh in?

**Comment by mbrukman** [comment]
It's unclear to me how `Table.counter_set()` would map to a `CheckAndMutate`—it only accepts a row, column, and value, but not the previous value, so there's nothing to check against, unless I'm missing something. What would we check against as the previous value?

The use case that it presumably addresses is to enable a user to reset a counter to 0, or initialize the state from some non-zero value if they're migrating data from elsewhere and want to start from a known state, rather than increment their way up to it.

**Comment by garye** [comment]
I took it back over on #1989, see if you think that makes sense.
