### ISSUE TITLE
Downloading factory blob fails because media_link isn't available

### ISSUE THREAD

**Issue by jlowin** [GoogleCloudPlatform/gcloud-python#1555]
Creating a blob like this loads the blob's properties, so downloading works (if it exists) since the download_url is available:
```python
blob = client.bucket(bucket_name).get_blob(blob_name)
blob.download_as_string() # works
```
But this doesn't load properties, so the download fails (even in the blob is valid):
```python
blob = client.bucket(bucket_name).blob(blob_name) # note .blob() instead of .get_blob()
blob.download_as_string() # fail, no URI
```

**Comment by jgeewax** [comment]
Yea, this makes sense. We should fetch the metadata if it's not there already.
