### ISSUE TITLE
Add a "Using the API" section for Datastore docs

### ISSUE THREAD

**Issue by gtaylor** [GoogleCloudPlatform/gcloud-python#1558]
I'm interested in potentially using this API, but I haven't had time to code dive and figure out the typical usage patterns. It looks like there are some unit tests, but it'd be great for me and my team to have a quick reference.

**Comment by dhermes** [comment]
Thanks @gtaylor! This is "covered" by #1037. I **really** need to get to this.

@jonparrott Can we chat about how to make this work nicely with the new snippets? Are the snippets `v1beta3` specific? We can make the doc in the `datastore-v1beta3` branch as well.

**Comment by dhermes** [comment]
@gtaylor In the meanwhile

- @jonparrott's very helpful [snippets][1] should be good (they are also on the cloud.google.com docs, but I'm not sure where)
- the [system tests][2] will be more useful
- the hard-to-maintain demo removed in #1486 can give an idea

[1]: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/edcff8082a2c62b4e1866b28795f3dac92f8baaf/datastore/api/snippets.py
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/63aa65c51c00102cf48a88a96e16ce0cbf365170/system_tests/datastore.py

**Comment by jonparrott** [comment]
The snippets work on both `v1beta2` and `v1beta3`. The docs were just published:

https://cloud.google.com/datastore/docs/datastore-api-tutorial

**Comment by gtaylor** [comment]
Thanks for the tip, @dhermes . That's very helpful!
