### ISSUE TITLE
Should we add batch-like support for writing logs

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1565]
[The `entries.write` API](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/entries/write) allows sending multiple log entries per API request.  Should we map this as a "batch" around a logger, similar to `pubsub.topic.Batch`?

**Comment by tseaver** [comment]
The [`LogEntryOperation` field](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/LogEntry#LogEntryOperation) provides a way to group entries corresponding to a single, logical operation.  These might best be handled with a batch-like feature (see #1566).

**Comment by dhermes** [comment]
:+1: Does it get sent with multi-part like storage batching?

**Comment by tseaver** [comment]
For `entries.write`, the `entries` field of the payload is a list.

For operations, I'm not even sure that they have to go in the same request:  it [appears](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/LogEntry#LogEntryOperation) that the back-end will group them based on `id` and `producer`, and use the `first` and `last` fields to figure out boundaries.

**Comment by tseaver** [comment]
Tracking the `operation` question on #1676.  `Batch` added in #1665.
