### ISSUE TITLE
bucket location is not supported 

### ISSUE THREAD

**Issue by sebastiancodes** [GoogleCloudPlatform/gcloud-python#1575]
Setting the location when creating a new bucket doesn't work:

    #!/usr/bin/env python3
    from gcloud import storage    
    client = storage.Client(project='foo')
    bucket = Bucket(client=client, name="bar")
    bucket.location = "EU"
    bucket.create()

The bucket is always created with the default US location .
Patching the properties before creating the bucket doesn't work either:
   
`bucket._patch_property('LocationConstraint', "EU")`

**Comment by tseaver** [comment]
Thanks for the report!  I checked, and none of the user-settable properties were being passed through to the 'bucket.create' API.  #1579 should address the issue.

**Comment by dhermes** [comment]
D'oh! Nice find @tseaver

**Comment by dhermes** [comment]
Thanks for filing @sebastiancodes too!
