### ISSUE TITLE
gcloud-python 0.7.1 protobuf issue

### ISSUE THREAD

**Issue by Solyony** [GoogleCloudPlatform/gcloud-python#1576]
There is issue with protobuf release from gcloud 0.7.1
https://github.com/GoogleCloudPlatform/gcloud-python/blob/0.7.1/setup.py#L18

Version removed from pypi: https://pypi.python.org/pypi/protobuf

**Comment by tseaver** [comment]
Thanks for reporting the issue.  Unfortunately, there isn't much we (`gcloud-python`) can do about it, as PyPI won't allow re-uploads of a release.  I have [reported it as a protobuf issue](https://github.com/google/protobuf/issues/1303), but doubt they will be able or willing to fix it either.

**Comment by dhermes** [comment]
Also, if you need help upgrading to `0.11.0`, we're happy to help. We put 0.7.1 "in the graveyard" the moment 0.8.0 was released (October 7, 2015).
