### ISSUE TITLE
Where are the allowed log entry protobuf types documented?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1577]
The [`LogEntry` API docs](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/LogEntry#FIELDS.proto_payload) say:

    The log entry payload, represented as a protocol buffer. You can only use protoPayload values that belong to a set of approved types.

    An object containing fields of an arbitrary type. An additional field "@type" contains a URI identifying the type. Example: { "id": 1234, "@type": "types.example.com/standard/id" }.

Where are the allowed protobuf types documented, and the corresponding URIs?

**Comment by tseaver** [comment]
The [discovery docs](https://www.googleapis.com/discovery/v1/apis/logging/v2beta1/rest) don't provide any more information about the allowed types.

**Comment by dhermes** [comment]
:+1:

**Comment by tseaver** [comment]
Absent any way to type-check the inputs, I'm thinking we just punt on allowing users to create entries with `protoPayload` set:  we will still parse those created via other services (#1578).

**Comment by dhermes** [comment]
Yeah punt until we hear from real users. @jgeewax WDYT?

**Comment by jgeewax** [comment]
That's one option.

Another is that we can do zero client-side checking, send the protobuf as it is. If it's an invalid type it'll get rejected, right ? That might be the better way to go as different versions of the API might allow new types...

**Comment by tseaver** [comment]
OK, I guess we just use `google.protobuf.json_format.MessageToJson` to render whatever message is passed, and then re-parse it using `json.loads`.

I will also add a helper which parses/merges the JSON `protoPayload` into a user-supplied protobuf messge object using `google.protobuf.json_format.Parse`, after dumping the value via `json.dumps`.

**Comment by tseaver** [comment]
I wish `google.protobuf.json_format._AnyMessageToJsonObject` [wasn't private](https://github.com/google/protobuf/blob/9240acd179708c3a2ab79508af6fd68efa6f883a/python/google/protobuf/json_format.py#L207) -- it looks like exactly what I need.

**Comment by jgeewax** [comment]
https://github.com/google/protobuf/issues/1351

**Comment by tseaver** [comment]
Via #1661.
