### ISSUE TITLE
Options for configuring 'LogSink.destination'.

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1591]
When I drafted the [logging usage doc](https://raw.githubusercontent.com/GoogleCloudPlatform/gcloud-python/logging-api/docs/logging-usage.rst), I assumed that users would want to pass in a string identifying the bucket, bigquery dataset, or pubsub topic, to which log entries would be exported, and I guessed at three properties, `storage_bucket`, `bigquery_dataset`, and `pubsub_topic`, which would consume and validate those strings.

Now, while working on the implementation, I believe that it might be better to have a `destination` property, whose setter would be willing to take any of:

- a string (it would do no validation, but just store it).
- a `Bucket` instance
- a `Dataset` instance
- a `Topic` instance.

In the case of the last three, the `destination` property setter would synthesize the appropriate destination string and store it.

We would then be able to accept a `destination` argument to `Sink.__init__` and `Client.sink`, which would just rely on the `destination` property setter.

Thoughts?

**Comment by dhermes** [comment]
I like it, but I am a bit worried about package inter-dependence. WDYT?

**Comment by tseaver** [comment]
I guess we could weaken that by checking `type(destination).__name__`, but I'm not sure that would be a win.

We could just punt and require the user to pass in a propertly-formatted destination URI, pointing them to the [exporting logs docs](https://cloud.google.com/logging/docs/api/tasks/exporting-logs).

**Comment by dhermes** [comment]
Yeah or we could do nested imports. But they make me sad.

**Comment by tseaver** [comment]
As of #1596, we have punted, and require the user to pass in a correctly-formatted destination string.  I am leaving this issue open for reconsideration after merging the `logging-api` branch today or tomorrow.

**Comment by dhermes** [comment]
@tseaver This has gone stale. Worth keeping open?

**Comment by tseaver** [comment]
Superseded by #2127.
