### ISSUE TITLE
Call for comments: Python 2.6 support will be dropped August 1, 2016

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1607]
Anyone who thinks they still need Python 2.6, please speak up here. (Sorry there isn't a better channel.)

Relates to #995 

/cc @tseaver @jgeewax

**Comment by jgeewax** [comment]
I am :+1: to dropping support for Python 2.6.... If they aren't making security fixes, it's kind of irresponsible for us to continue enabling it....

**Comment by tseaver** [comment]
I'm [already on record as in favor of dropping 2.6 support](https://github.com/GoogleCloudPlatform/gcloud-python/issues/995#issuecomment-122983016).

**Comment by tseaver** [comment]
Oops, that should've been #1927.

**Comment by dhermes** [comment]
D'oh!

**Comment by dhermes** [comment]
Oops @tseaver meant to comment here

Can you help cut the final 2.6 release and update the docs / README / etc?

Today is DERP-recation day!

**Comment by tseaver** [comment]
Sorry -- I got stuck with contractors today. I'll tackle a release this evening.

**Comment by tseaver** [comment]
0.18.0 release PR is #2048.

**Comment by dhermes** [comment]
@tseaver OK to close this out it remains to remove 2.6 [from `setup.py`][1]?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/891e4a8a2baf5604cbf0a767d0842e3d2130b960/setup.py#L56

**Comment by dhermes** [comment]
Or do we also remove the `datetime.total_seconds()` hack for 2.6?

**Comment by dhermes** [comment]
And do we also need a warning in `gcloud.__init__`?
