### ISSUE TITLE
Adopt common timeout/retry/backoff strategy for system tests.

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1619]
From https://github.com/GoogleCloudPlatform/gcloud-python/pull/1609#discussion_r56220537

We have a number of sporadic system test failures (#1085, #1089, #1100, #1104) due to "eventual consistency" in the tested APIs.  We have adopted a set of ad-hoc (and obviously not 100% reliable) strategies for working around the delays involved.

The point of this issue is to  adopt a consistent policy / mechanism across all system tests for addressing delays caused by eventual consistency.

@jonparrott can you comment here, collecting your thoughts expressed elsewhere?

**Comment by jonparrott** [comment]
In python-docs-samples we're using a combination of [flaky](https://pypi.python.org/pypi/flaky/3.0.3) and not running flaky tests on travis (we have a jenkins instance).

**Comment by tseaver** [comment]
#1391 is related.

**Comment by dhermes** [comment]
I have an [old branch][1] around from #535 when I made the first stab at this.

[1]: https://github.com/dhermes/gcloud-python/tree/retired-PR-535-retry-flaky-regression-cases

**Comment by tseaver** [comment]
Maybe one of the following libraries would be useful:

- https://pypi.python.org/pypi/retrying
- https://pypi.python.org/pypi/backoff

**Comment by daspecster** [comment]
So now, in the systems-tests path we have `retry.py`.

```python
from retry import Retry

@Retry(SomeException, tries=3, delay=30)
def method_to_retry():
    ...
```

**Comment by tseaver** [comment]
I added classes to handle two other cases in #2050:

- Retry until method result passes a predicate.
- Retry until method's `__self__` passes a predicate.

**Comment by dhermes** [comment]
@tseaver What about this issue? And the novel failures?

**Comment by tseaver** [comment]
I think we should create separate issues for the failures we still see, and resolve them one by one as we add backoff/retry  for them.  E.g., today's [BQ failure](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/151011041#L609) should be its own issue, rather than reopening #1104.  Likewise todays [happybase failure](https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/151011041#L609) should be a separate issue.

**Comment by dhermes** [comment]
@tseaver 500, 502 and 503 are just unavoidable for a general service. `gcloud-node` just retries them [by default][1]

[1]: https://github.com/GoogleCloudPlatform/gcloud-node/blob/2613bccdc1d211f07b85fe72fdb2464ecc00ad0b/packages/common/src/util.js#L280

**Comment by tseaver** [comment]
@dhermes #2075 tracks the BQ failure.  #2076 tracks the Happybase one.  I assigned the first to me, and the second to you, somewhat arbitrarily.
