### ISSUE TITLE
gcloud._helpers._compute_engine_id should return a str (Python 3)

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-python#1625]
From https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/92:

I stumbled upon this while deploying my app for the first time on GKE/GCE.

I had to explicitly specify `project` when creating a client: `gcloud.datastore.Client(project="my-project")`, otherwise I just got an `gcloud.exceptions.ServiceUnavailable: 503 Backend Error`.

First I thought the problem would be that autodetecting the project-id didn't work, but `gcloud.datastore.Client(credentials=credentials, project=project)` returns my project-id, be it as `bytes` instead of `str`.

I quickly verified that using `bytes` as a project-id does not work, i.e. `gcloud.datastore.Client(project=b"my-project")` resulted in that neat `503 Backend Error`.

**Comment by dhermes** [comment]
Thanks. This has come up before (I'll try to track down where). I wish there was an easy way to run system tests on GCE and GAE.

**Comment by dhermes** [comment]
#1470 was when it came up. "Fixed" in #1505

**Comment by dhermes** [comment]
@pcostell What version are you using? It seems like this should be all fixed in `datastore-v1beta3` branch

**Comment by pcostell** [comment]
sorry I copied this from the Datastore issue tracker. @flunderpero, can you share what gcloud version you are using?

**Comment by dhermes** [comment]
DERP. Sorry I didn't even notice that

**Comment by flunderpero** [comment]
I'm using gcloud 0.11.0 installed from PyPi.

**Comment by dhermes** [comment]
Thanks. Right now the [datastore `Client`][1] doesn't use the [project mix-in][3]. I "imagined" that the [`Client` in the `datastore-v1beta3` branch][2] did "the right thing", but that hasn't been updated either.

Thanks for poking me into noticing this change was needed!

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/98edc644049779927c981fe69eb76d7066540f0c/gcloud/datastore/client.py#L158
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f9e4efc3feea3174e203f3aa8b3bb05a0b4d73ee/gcloud/datastore/client.py#L144
[3]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/98edc644049779927c981fe69eb76d7066540f0c/gcloud/client.py#L127
