### ISSUE TITLE
No JSON object could be decoded when calling index.list_documents()

### ISSUE THREAD

**Issue by nlokare** [GoogleCloudPlatform/gcloud-python#1643]
Hi,

Just to clarify, is the gcloud/Cloud Search API the equivalent to App Engine's https://cloud.google.com/appengine/training/fts_intro/? I can't find any documentation specifying this, but I assumed so.

If so, I keep getting `Value Error: No JSON object could be decoded` whenever I call the `list_indexes()` or `list_documents()` methods. 

If not, is there an equivalent library I should be using to build app engine search indexes from a Google compute cloud application?

Thanks

**Comment by tseaver** [comment]
Thanks for the report!  `gcloud.search` is a wrapper for the [Google Cloud Search API](https://cloud.google.com/search/), which is still in alpha state:  you need to be [whitelisted](https://docs.google.com/a/google.com/forms/d/1TshVfwJBP8UoKN-cpjIo4yB6TIiBYrMuxTQQ8LQfPyk/viewform) to use the service.

The bug in the wrapper is that it should handle non-JSON error responses better.

**Comment by tseaver** [comment]
Unfortunately, the early-access program is closed. :(

**Comment by dhermes** [comment]
This was filed in #1438 / #1506 and "fixed" in #1508.

@nlokare What version of the library are you using?

**Comment by nlokare** [comment]
@dhermes I am using version 0.9.0

**Comment by dhermes** [comment]
Ahhh I see. This fix was in the [`0.10.1` release][1].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/0.10.1

**Comment by tseaver** [comment]
Note that @nlokare is out of luck even if he upgrades, unless he was already on the whitelist for the Cloud Search alpha:  that signup has closed.

**Comment by nlokare** [comment]
@dhermes @tseaver Thanks for the updates. Do you happen to know when the whitelist will be open again?

**Comment by dhermes** [comment]
We don't have visibility into that. I sent an email to one of the engineers on the API and hope to hear back. Sorry we don't know more.

**Comment by nlokare** [comment]
@dhermes Thanks. Appreciate it. Just fyi, the online docs don't indicate that the search API is currently in alpha.

**Comment by dhermes** [comment]
The only docs are https://cloud.google.com/search/, which 404 if you aren't on the whitelist. This is distinct from the GAE feature: https://cloud.google.com/appengine/training/fts_intro/ (at least as far as I know it is, I definitely know the docs are distinct).

**Comment by nlokare** [comment]
@dhermes I am referring to these docs https://googlecloudplatform.github.io/gcloud-python/0.9.0/search-usage.html

**Comment by dhermes** [comment]
Ahh I see. That is something we **can** fix! Thanks.
