### ISSUE TITLE
Should 'topics.testIamPermissions' be wrapped as 'check_iam_permissions'?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1648]
See: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1642#discussion_r57048424 and ff.

Likewise `subscriptions.testIamPermission`.

@jgeewax if you decide so, please assign the issue to me;  otherwise, just close it.

**Comment by jgeewax** [comment]
I'm a fan of `check` unless we have an awesome reason not to...
