### ISSUE TITLE
Error Calling DNS#QOUTAS

### ISSUE THREAD

**Issue by ojengwa** [GoogleCloudPlatform/gcloud-python#1650]
When I tried to call the [`dns.qoutas` method][1], I got the following errors. 
```
...
.../.virtualenvs/panda/lib/python2.7/site-packages/gcloud/dns/client.py", line 59, in quotas
    return dict([(key, int(value))
ValueError: invalid literal for int() with base 10: 'dns#quota'
```

On introspection, it turns out that the error stems from the attempt to cast the `values` within the `quota` dictionary as an integer, specifically this call: `int(value)` where some of the values are not strings. Except it breaks the client somewhere else, I don't see how what purpose the casting serves in the first place.  
Here's a snippet of the return value from the function call:
```
{u'quota': {u'kind': u'dns#quota', ...},...}
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/dbb22a7fddcf12228bba7b191774f2c4a2adfe35/gcloud/dns/client.py#L59

**Comment by dhermes** [comment]
Thanks for the report! @tseaver We should get system tests up and running for DNS soon, it'll help catch stuff like this. We've got a domain we can use now (let's chat via email).

**Comment by ojengwa** [comment]
I will close this issue.
