### ISSUE TITLE
[Documentation Issue] Resource Record Sets

### ISSUE THREAD

**Issue by ojengwa** [GoogleCloudPlatform/gcloud-python#1653]
Page Name: dns-usage
Release: 0.11.0

From the documentation, the accepted usage for the dns.Client#zone method is similar to this: 
 ```
zone = client.zone('acme-co')
````

I tried same and I got this error:
```
...
TypeError: zone() takes exactly 3 arguments (2 given)
```

On introspection, I observed that the signature for the dns.Client#zone method is `def zone(self, name, dns_name):`. It seems so far that a lot of the API docs/lib is broken...

Any reasons why, please?

**Comment by tseaver** [comment]
Apologies for the discrepancy.  The API implementation got stalled by the difficulty of getting system testing wired up (it requires having an actual DNS zone to work with).  Cleaning up the docs to match the implementation as it evolved got stalled, I'm afraid.
