### ISSUE TITLE
blob.acl.save_predefined() only works for private

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/gcloud-python#1659]
[From the documentation.](https://googlecloudplatform.github.io/gcloud-python/stable/storage-acl.html#gcloud.storage.acl.ACL.save_predefined)

> Must be one of the keys in [_PREDEFINED_ACLS](https://github.com/tseaver/gcloud-python/blob/1a210341811aff3b4185f830b07e87b22c1ef73d/gcloud/storage/acl.py#L171)

```Python
    _PREDEFINED_ACLS = frozenset([
        "private",
        "project-private",
        "public-read",
        "public-read-write",
        "authenticated-read",
        "bucket-owner-read",
        "bucket-owner-full-control",
    ])
```

Let's try.
```Python
>>> blob.acl.save_predefined('public-read')
...
gcloud.exceptions.BadRequest: 400 Invalid string value: 'public-read'. Allowed values: [authenticatedread, bucketownerfullcontrol, bucketownerread, private, projectprivate, publicread]
>>> blob.acl.save_predefined('publicread')
...
ValueError: Invalid predefined ACL: publicread
```
Coincidentally, the [tests](https://github.com/tseaver/gcloud-python/blob/1a210341811aff3b4185f830b07e87b22c1ef73d/gcloud/storage/test_acl.py#L633) only try *private*.

**Comment by pdknsk** [comment]
I have confirmed that editing ```_PREDEFINED_ACLS``` to use the suggested values makes it work. The bug is that it uses the XML API names rather than the JSON API names. I think both should be valid in ```gcloud-python```, as ```gsutil``` uses the former.

PS. ```public-read-write``` only applies to buckets, so isn't listed in the allowed values.

**Comment by tseaver** [comment]
Thanks for investigating!  Can you confirm my reading:  *we* have the bug, because the values enumerated in `gcloud.storage.acl` are the XML API spellings, which aren't valid for use against the JSON API?

Begging the question, of course, of why the two APIs use different spelings for those constants. :(

**Comment by pdknsk** [comment]
Yes, that's the bug. I think both should be valid in ```gcloud-python``` though, as the XML API names are more commonly mentioned in docs and otherwise. And ```gsutil``` uses those names too, as mentioned. They could be easily mapped to each other.

**Comment by tseaver** [comment]
Can you point me to the docs for the JSON predefined ACL constants?  The [ones I worked from](https://cloud.google.com/storage/docs/access-control#predefined-acl) weren't obviously tied to the XML API.

**Comment by tseaver** [comment]
Oh, never mind:  I see that the first column is the JSON spellings.
