### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by sirtux** [GoogleCloudPlatform/gcloud-python#1662]
Page Name: dns-usage
Release: 0.11.0

On https://googlecloudplatform.github.io/gcloud-python/stable/dns-usage.html#resource-record-sets,

there is an example:

`[(record.name, record.type, record.ttl, record.rrdatas) for record in records]`

the correct version would be:

`[(record.name, record.record_type, record.ttl, record.rrdatas) for record in records]`

as record doesn't have a attribute type, but record_type.

**Comment by dhermes** [comment]
Thanks for filing!
