### ISSUE TITLE
Storage blob.patch() returns 400 error on GCE only

### ISSUE THREAD

**Issue by ndenny** [GoogleCloudPlatform/gcloud-python#1670]
This may be related to #1185 - I'm seeing the following code work on my dev machine, but it's failing on GCE / Python 2.7.9 / gcloud 0.11.0:

```
from gcloud import storage
client = storage.Client()
bucket = client.bucket('my-bucket-name')
blob = bucket.blob('test.txt')
blob.upload_from_string('Hello world')
blob.metadata = {'luke': 'skywalker'}
blob.patch()
```

I get the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gcloud/storage/_helpers.py", line 124, in patch
    query_params={'projection': 'full'}, _target_object=self)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/connection.py", line 343, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.BadRequest: 400 Invalid argument. (PATCH https://www.googleapis.com/storage/v1/b/my-bucket-name/o/test.txt?projection=full)
```

**Comment by dhermes** [comment]
Strange that it would fail on one machine and not another, since it seems the error is about the payload. What OS are you using on GCE? I seem to recall your local dev machine is OS X?

**Comment by ndenny** [comment]
Dev machine - Mac OS X:
Darwin 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
GCE - fairly sure this is a "default" Debian setup:
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
Machine type: n1-standard-1 (1 vCPU, 3.75 GB memory)
CPU platform: Intel Ivy Bridge
Zone: us-central1-f

**Comment by jonparrott** [comment]
Is this the same problem of the `cloud-platform` scope not being treated the same as `dev_access.full_control` and not letting you do PATCH requests?

@ndenny can you confirm which scopes your instance has?

**Comment by ndenny** [comment]
I created the instance a while ago now... it's reporting this:
```
      "scopes": [
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
        "https://www.googleapis.com/auth/devstorage.read_write",
        "https://www.googleapis.com/auth/datastore",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring.write",
        "https://www.googleapis.com/auth/pubsub"
      ]
```

**Comment by jonparrott** [comment]
Gotcha. Can you try creating a new instance with the `cloud-platform` scope and trying again? Failing that, try creating one with `devstorage.full_control`?

**Comment by ndenny** [comment]
Update: including `devstorage.full_control` has worked and solves the problem. 
I was using the web console to create the instance, don't see a way to include cloud-platform, will look into using a command-line instead.

**Comment by jonparrott** [comment]
Cool, I guess that answers that. I'm going to go ahead and close this issue, but feel free to let us know if there's anything else we can do to help.

[IAM](https://cloud.google.com/iam/) is in the process of rolling out and will eventually supercede the need for scopes.

**Comment by ndenny** [comment]
Glad we found a solution. Just for completeness, adding `cloud-platform` also fixed the issue.

**Comment by dhermes** [comment]
Thanks for the follow up!
