### ISSUE TITLE
Strategy for dual-mode APIs (REST + gRPC)

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1696]
For the APIs which support both REST and gRPC, how should we expose the choice?  One option would be to have a different `Connection` class for each endpoint:  if it works, then after instantiating the desired client, calling code would in theory be happy without caring again which one was chosen.  Thoughts?

Because the `datastore` API is protobufs-over-REST, its `Connection` class already has a bunch of domain-specific API calls already, which would make this plan simpler.  the `Connection` classes for `pubsub` and `logging` expose only `make_api_request`, which won't be much help.

**Comment by tseaver** [comment]
Toward #851.

**Comment by dhermes** [comment]
I imagined it the first way. I think we're better off factoring all the API calls back into `Connection` for `pubsub` and `logging` and then trying something like:

```python
try:
    from gcloud.foo.grpc_connection import GRPCConnection as Connection
except ImportError:
    from gcloud.foo.connection import Connection
```

**Comment by tseaver** [comment]
I think we might need to make an explicit choice possible (maybe driven via an environment variable?) to permit system testing both ways.

**Comment by dhermes** [comment]
IIRC all of those clients are defined with

```python
_connection_class = Connection
```

so for tests at least we could monkey patch the class (though I'm not against an override).

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/3596353bfbd9d1f01373c7cf1596a60edf2cd9c7/gcloud/pubsub/client.py#L45

**Comment by tseaver** [comment]
Pubsub gRPC:

- [Docs](https://cloud.google.com/pubsub/grpc-overview)
- [Proto-generated Python library](https://pypi.python.org/pypi/grpc-google-pubsub-v1)

Logging gRPC:

- I can't find any docs for Logging + gRPC
- [Proto-generated Python library](https://pypi.python.org/pypi/grpc-google-logging-v2)

**Comment by tseaver** [comment]
Because the generated code for the gRPC services is organized around stubs, with no notion of a connection, I've updated #1700 to move the API-request-calling methods into three separate helper classes (one for the publisher-specific APIs, one for the subscriber specific APIs, and one for the IAM policy-specific APIs).  The user-facing methods gain access to these helpers via properties on the client, which instantiates them on demand, wrapping them around its connection.

I'm currently planning that the client will detect whether `grpc` is importable, and test the environment for a flag to disable it:  if the import fails, or the flag is present, it will create instances of the three helpers defined in #1700.  Otherwise, I will add three classes which wrap around the generated-code stubs and implement the same interface as the corresponding JSON-over-HTTPS helpers.

**Comment by dhermes** [comment]
SGTM

**Comment by tseaver** [comment]
All three APIs now use gRPC if available, and fall back to JSON-over-HTTP.
