### ISSUE TITLE
v1beta3 and emulator use

### ISSUE THREAD

**Issue by hir3npatel** [GoogleCloudPlatform/gcloud-python#1707]
The docs in this link do not make it clear on how to use the library against the local emulator, with out any creds needed. https://cloud.google.com/datastore/docs/datastore-api-tutorial

The service object can be instantiated without creds for emulator use:
c = datastore.Client(project='test', http=httplib2.Http())

The lib I assume requires the latest version of the emulator to work, it should be noted somewhere in the docs too, I did a "gcloud components install gcd-emulator" to get the latest version.

Lastly, with all the above in place, the lib does not work with the emulator, it calls a url that the emulator does not recognise and therefore complains. I had to make this adjustment to have the lib and emulator working together:

Change  https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/connection.py line 49 
from:
API_URL_TEMPLATE = ('{api_base}/{api_version}/projects'
to:
API_URL_TEMPLATE = ('{api_base}/datastore/{api_version}/projects'

With this change, the library and latest emulator worked together without creds, as expected.

I am not sure if this is a general issue with the lib, or if I am using it incorrectly to need this, or if the emulator is the issue and it should be fixed there?

**Comment by dhermes** [comment]
Thanks for the heads up. I'm looking into this right now.

**Comment by pcostell** [comment]
You should be able to use the existence of the `DATASTORE_EMULATOR_HOST` variable to indicate that the emulator should be used. However the emulator still is (a little) broken because of the extra `datastore` required in the path name. I'm hoping to fix this in a future emulator release, but you may want to address it in the library faster.

**Comment by dhermes** [comment]
I can just add a hack to put it [on the base URL][1] when GCD is detected. @pcostell do you think it's worth it? How long will it be before that fix makes it into `gcd.sh` (seems like it could be a one-liner fix?).

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/8da951d4b693bf227f1b29c9ca57a09beeb4bb4b/gcloud/datastore/connection.py#L59-L60

**Comment by pcostell** [comment]
I'm not sure we want to fix it in the existing gcd.sh tool because it is wrapped together with the `v1beta2` emulator. I'd like to fix it in the `grpc`-based emulator which I'm working on adding proto-over-http  and JSON support to now.

**Comment by dhermes** [comment]
That won't help us until we support gRPC. I'll send the PR to modify the path and assign you to review.

**Comment by pcostell** [comment]
Sounds good (note it will help once proto-over-http support is added to the new emulator as you'll then be able to use the new emulator in the current setup OR via gRPC).

**Comment by dhermes** [comment]
Ha OK. Thanks. PR sent.
