### ISSUE TITLE
How to handle an optional package dependency in tests?

### ISSUE THREAD

**Issue by rimey** [GoogleCloudPlatform/gcloud-python#1710]
#1691 adds `gcloud.monitoring` for accessing the Google Monitoring API. The initial focus is on querying of metric data.

The primary way in which users will want to get metric data is as a [pandas](http://pandas.pydata.org/pandas-docs/stable/) `DataFrame`, and the `Query` class offers an `as_dataframe()` method for this purpose.

However, `pandas` is a large package with dependencies on yet other packages. I would not recommend `gcloud-python` taking a dependency on it.

We have taken the approach of importing `pandas` dynamically in `as_dataframe()`. The documentation explains that use of this method requires that you have `pandas` installed. This works perfectly.

Tests are still an issue, however. The unit tests for `as_dataframe()` naturally require `pandas`, which is not currently present in the test environment.

How should we handle this?

**Comment by tseaver** [comment]
Maybe something like:

```python
import sys

try:
     import pandas
except ImportError:
    HAVE_PANDAS = False
else:
    HAVE_PANDAS = True
from unittest2 import TestCase, skipUnless

class TestWithMaybePandas(TestCase):
    @skipUnless(HAVE_PANDAS, 'No pandas')
    def test_something_using_pandas(self):
          # whatever
```

Ideally you would add a `tox` environment (but maybe not one of the defaults) which added `pandas` to the dependencies, so that those tests could be exercised.

**Comment by rimey** [comment]
Done. PTAL.

What do we do about the test coverage analysis?

**Comment by dhermes** [comment]
We may just have you add a no-cover pragma.

**Comment by rimey** [comment]
I added a py27-pandas tox environment, and I added no-cover pragmas.

Thank you, @tseaver and @dhermes, for the advice.
