### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'gcloud' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by glushkovrealweb** [GoogleCloudPlatform/gcloud-python#1711]
why this code return error?use python 2.7
 
![default](https://cloud.githubusercontent.com/assets/12747250/14413423/e060bdfc-ff81-11e5-93de-1f69d4ffa53b.png)

**Comment by tseaver** [comment]
`gcloud` expects to be installed as a top-level package in the `site-packages` directory of your Python or virtualenv.  You shouldn't be importing it from `lib.gcloud`.
