### ISSUE TITLE
dns.Client.zone lacks a description parameter.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-python#1721]
The `description` parameter is required to the API call to `manageZones.create`, however, this parameter is not exposed in `Client.zone`. This leads to the awkward pattern:

```python
zone = client.zone('zone-name', dns_name='example.com.')
zone.description = 'My zone'
zone.create()
```

Where it should be:

```python
zone = client.zone('zone-name', dns_name='example.com.', description='My zone')
zone.create()
```

**Comment by jgeewax** [comment]
It seems weird that description is required... I don't think it should be required in the client, could we make the "default description" == dns_name on the client side unless someone specifically sets a description?

**Comment by jonparrott** [comment]
hmm. Idk. It may be an API-level bug, as the description isn't strictly required in the UI.
