### ISSUE TITLE
Query with projection on datetime entity doesn't deserialize to datetime

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-python#1770]
If you do a query and the projection has a datetime field, for instance:

```python
entity = client.entity(client.key('example'))
entity['created'] = datetime.datetime.utcnow()

query = client.query(kind='example')
query.projection = ['created']
results = list(query.fetch())
```

The `results[0]['created']` will be a timestamp instead of a datetime object.

**Comment by tseaver** [comment]
For the query results, instead of returning what should be a `timestamp_value`, the back-end is returning an `integer_value` with `meaning` of 18):

```python
>>> result_pbs[0]
[key {
  partition_id {
    project_id: "citric-celerity-697"
  }
  path {
    kind: "issue-1770"
    id: 5754903989321728
  }
}
properties {
  key: "created"
  value {
    integer_value: 1462299971643047
    meaning: 18
  }
}
]
```

which differs from the protobuf returned via a normal `get`:

```python
>>> epbs
[key {
  partition_id {
    project_id: "citric-celerity-697"
  }
  path {
    kind: "issue-1770"
    id: 5754903989321728
  }
}
properties {
  key: "created"
  value {
    timestamp_value {
      seconds: 1462299971
      nanos: 643047000
    }
  }
}
]
```

That smells like a back-end bug to me.

**Comment by jonparrott** [comment]
Oh noes.

/cc @jgeewax @pcostell

**Comment by tseaver** [comment]
Extra datapoint:  the result from the same query *without* the projection return the expected `timestamp_value` property.

**Comment by pcostell** [comment]
This is WAI (or WADNAI if you prefer -- Working as Designed, not as intended). `timestamp_value` is stored as a a fixed-point number in Cloud Datastore. You can see this in the [sort order specification](https://cloud.google.com/datastore/docs/concepts/entities#properties_and_value_types), Integers and Date/times are listed together in the sort order.

In the indexes, the property value is stored without additional information, in this case the indication that this is a datetime. In Cloud Datastore, projection queries aren't just field masks -- they indicate to the system that it should only perform an index scan and not do the full entity lookup. This means it won't have the opportunity to lookup the additional information.

We hope to be able to fix this eventually, but it has a large impact on backwards compatibility.

**Comment by jonparrott** [comment]
Wow, that's kind of a really bad experience for using projection queries.

**Comment by pcostell** [comment]
The price we have to pay for backwards compatibility I'm afraid.

**Comment by tseaver** [comment]
AFAICT, there is nothing `gcloud-python` can do to fix this issue.  @jonparrott / @pcostell feel free to reopen if you have a suggestion.

**Comment by dhermes** [comment]
@pcostell Any suggestions for what to do for users? It seems that [18 is for `INDEX_VALUE`][1] which is pretty generic.

https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/datastore/entity_pb.py?r=530#1151

**Comment by dhermes** [comment]
@pcostell Any suggestions for what to do for users? It seems that [18 is for `INDEX_VALUE`][1] which is pretty generic.

[1]: https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/datastore/entity_pb.py?r=530#1151

**Comment by pcostell** [comment]
I'm not sure there is anything to do. The 18 just signifies that this came from a projection query. It's useful if the user tries to store that property again we can reject it (to prevent data loss from reading a subset of your data then overwriting the real data).

**Comment by dhermes** [comment]
OK. Le sad face.

**Comment by pdknsk** [comment]
I just ran into this and agree it's bad. At the least you'd expect a warning about it in the docs. Even when it's not too difficult to guess what's happening when it returns `long` rather than `datetime.datetime`.
