### ISSUE TITLE
Client.from_service_account_json raises a TypeError

### ISSUE THREAD

**Issue by Morreski** [GoogleCloudPlatform/gcloud-python#1771]
When executing:
```python
client = Client.from_service_account_json('./key.json')
```

A TypeError is raised from *oauth2client* because the method `create_scoped` from `oauth2client.service_account.ServiceAccountCredentials` is called with `scopes=None` although this parameter expects an iterable.

Maybe the `SCOPE` variable in connection.py (line 69) should be an empty set instead of a None object ? I don't know what would be the side effects of such a change.

**Comment by dhermes** [comment]
@Morreski Can you provide a snippet of `gcloud-python` that uses a null value for scopes?

**Comment by Morreski** [comment]
Well NVM this ticket this was a fail, just spotted i had an error in my imports, that made me instantiate the base client class instead of pubsub client class...

**Comment by dhermes** [comment]
Good deal! Thanks for taking the time to report it!
