### ISSUE TITLE
Datastore v1beta3 client and 403 forbidden

### ISSUE THREAD

**Issue by hir3npatel** [GoogleCloudPlatform/gcloud-python#1778]
Is anyone seeing this issue in production, or is it just me:

Forbidden: 403 Request had insufficient authentication scopes.

I am using the gcloud-python (version 0.13.0) library (datastore v1beta3). The client is a container in a pod within GKE. I do not set any environ params, and simply initiate the client with:
datastore_client = datastore.Client() #uses project default creds

The trace when running a query is:

Forbidden: 403 Request had insufficient authentication scopes.
at _request():98 (connection.py:98 in /usr/local/lib/python2.7/dist-packages/gcloud/datastore)
at _rpc():121 (connection.py:121 in /usr/local/lib/python2.7/dist-packages/gcloud/datastore)
at run_query():275 (connection.py:275 in /usr/local/lib/python2.7/dist-packages/gcloud/datastore)
at next_page():424 (query.py:424 in /usr/local/lib/python2.7/dist-packages/gcloud/datastore)

From my understanding, the oauth2client which the datastore lib uses, should be getting default project creds from the GCE production environment. The type of error (insufficient scopes) leads me to think the issue is not that the lib cannot find or use gce creds, but that the scopes being requested is not what datastore expects.

Anyone seeing this issue too? I'm wondering if it's a general issue related to scopes or something in my project setup and affecting just me.

**Comment by hir3npatel** [comment]
I noticed that the old googledatastore library has these scopes:
SCOPE = ('https://www.googleapis.com/auth/datastore '
         'https://www.googleapis.com/auth/userinfo.email')

While this library (gcloud/datastore/connection.py) has:
SCOPE = ('https://www.googleapis.com/auth/datastore',)

**Comment by hir3npatel** [comment]
Adding the userinfo.email scope did not work, same error. This library used to work fine a few weeks ago, and the scopes have not changed since, so I can't figure out what the issue is.

**Comment by hir3npatel** [comment]
works for me with a service account, something about the default setup in the project that is causing the issue for me, anyway it is not the library then.

**Comment by tseaver** [comment]
> works for me with a service account

I'm glad you were able to get your app working.  

>  something about the default setup in the project that is causing the issue for me, anyway it is not the library then.

I will close this issue, then.  Please comment here if you think there is something that should change in `gcloud-python` to address the problem.

**Comment by dhermes** [comment]
@hir3npatel `https://www.googleapis.com/auth/userinfo.email` was dropped because it was required in `v1beta2` but is no longer required in `v1beta3`.

**Comment by hir3npatel** [comment]
Thanks for the replies, the issue is something in my project setup I guess. I'll stick to using a service account. Just to clarify, is the GCE method of auth supposed to work with GKE? (since GKE runs on GCE).

This links says that on GCE auth should "just work", which was the case for me a few weeks back, but isn't now. (I have since deleted and recreated a new cluster on GKE though)
https://gcloud-python.readthedocs.io/en/latest/gcloud-auth.html#overview

**Comment by dhermes** [comment]
I'm not familiar with GKE. The "just work" in GCE is enabled by the metadata service. Do containers have access to the metadata service for the underlying instance they run on? /cc @jonparrott

**Comment by dhermes** [comment]
https://github.com/kubernetes/kubernetes/issues/8512 may give some insight on this

**Comment by hir3npatel** [comment]
8512 seems like an old issue (2015 Q1-ish), I had a look through thanks. The reason I suspected the library is that a) it worked a few weeks ago on a previous cluster, so the break surprised me; and b) I got an error related to oauth2 scope. I did not set any environ vars on the container, so no project-id or the like, so it appears to me like the library is managing to get some of those details (I don't know from where) but clearly isn't getting everything it needs for successful auth.
If there is anything I can do or provide from that container to help find the issue let me know, but as you say it is probably a GKE thing rather than the library.

**Comment by hir3npatel** [comment]
If I query the metadata service from inside the container, I do get valid responses:

curl "http://metadata.google.internal/computeMetadata/v1/project/attributes/" -H "Metadat
a-Flavor: Google"
gke-testcluster-8dd32ad5-cidr
google-compute-default-region
google-compute-default-zone
sshKeys
stackdriver-agent-key

**Comment by dhermes** [comment]
Peeking at the [`oauth2client` implementation][1], the token is minted via a [request to][2] http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token with the header `Metadata-Flavor=Google`.

[1]: https://github.com/google/oauth2client/blob/e99a4ac3c5d3c2944680ea180b71a0d144d6128b/oauth2client/contrib/gce.py
[2]: https://github.com/google/oauth2client/blob/e99a4ac3c5d3c2944680ea180b71a0d144d6128b/oauth2client/contrib/gce.py#L128-L129

**Comment by hir3npatel** [comment]
Thanks for looking, if I run that query in the container, I get a valid response:
{"access_token":"mylongtoken","expires_in":900,"token_type":"Bearer"}

If my token is stale, the oauth lib will refresh it yes? Either that or my token is not granting me access to datastore?

**Comment by dhermes** [comment]
Yes, but if the token is stale, the service will return a 401. Your 403 indicates that you don't have access.

Check out the [tokeninfo][1] to see if your instance (and hence your token) is authorized with the scopes you need.

[1]: https://developers.google.com/apis-explorer/#p/oauth2/v2/oauth2.tokeninfo

**Comment by hir3npatel** [comment]
Cool, once again thanks for all the info around this, apologies for the red herring (it is not an issue in the library).

**Comment by hir3npatel** [comment]
I found the issue, I created the cluster with:
gcloud container clusters create [cluster]

I missed the --scopes option to specify that my cluster will use datastore :(

Thanks again for the responses and help.

**Comment by dhermes** [comment]
Good deal!

**Comment by jonparrott** [comment]
Sorry to be late to the thread, but I'm glad you figured it out @hir3npatel. It can be really easy to miss the scopes setting when creating a cluster.

**Comment by hir3npatel** [comment]
No worries @jonparrott 
Indeed. When creating the cluster using the UI, it prompts asking which other services you might need with the cluster, and selecting datastore at that stage is why it worked for me previously. I had created the cluster using the UI previously, but this time used gcloud. Thanks for all the help guys.

**Comment by jgeewax** [comment]
Can we add this to the FAQ or Auth page of the docs? (Might belong in gcloud-common...)

**Comment by dhermes** [comment]
@jgeewax it already is in our docs: http://googlecloudplatform.github.io/gcloud-python/0.13.0/gcloud-auth.html#using-google-compute-engine
