### ISSUE TITLE
Timestamp nanos parsing broken for '2016-05-09T18:49:00.655319Z'

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1783]
```
ERROR: test_log_text (logging_.TestLogging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/logging_.py", line 79, in test_log_text
    entries, _ = logger.list_entries()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/logging/logger.py", line 317, in list_entries
    page_size=page_size, page_token=page_token)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/logging/client.py", line 141, in list_entries
    for resource in resp.get('entries', ())]
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/logging/client.py", line 141, in <listcomp>
    for resource in resp.get('entries', ())]
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/logging/client.py", line 79, in _entry_from_resource
    return TextEntry.from_api_repr(resource, self, loggers)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/logging/entries.py", line 92, in from_api_repr
    timestamp = _rfc3339_nanos_to_datetime(timestamp)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/_helpers.py", line 344, in _rfc3339_nanos_to_datetime
    dt_str, _RFC3339_NANOS.pattern))
ValueError: Timestamp: '2016-05-09T18:49:00.655319Z', does not match pattern: '\n    (?P<no_fraction>\n        \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}  # YYYY-MM-DDTHH:MM:SS\n    )\n    \\.                                       # decimal point\n    (?P<nanos>\\d{9})                         # nanoseconds\n    Z                                        # Zulu\n'
```

From https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/128927443

I haven't traced down the codepath just yet.

**Comment by tseaver** [comment]
Rotten tomotoes for the back-end team.  "Nanosecond precision" strongly requires that the trailing zeroes be present:  that is the very *definition* of precision.

**Comment by dhermes** [comment]
It's likely that they are optimizing for payload size; if that's the case they get an A in that category.

WDYT of changing the [nanos check][1] to `(?P<nanos>\d{6-9})` and the using `zfill(9)`?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/22634abd342268f5f77b2637e9c13fb0a9492309/gcloud/_helpers.py#L48

**Comment by hir3npatel** [comment]
I still get this error when running a script from gke, trying to fetch logs. According to pip I have these installed: 

> gapic-google-logging-v2 (0.10.1)
> google-cloud-logging (0.20.0)
> grpc-google-logging-v2 (0.10.1)

> ValueError: Timestamp: u'2016-10-10T06:18:47Z', does not match pattern: '\n    (?P<no_fraction>\n        \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}  # YYYY-MM-DDTHH:MM:SS\n    )\n    \\.                                       # decimal point\n    (?P<nanos>\\d{1,9})                       # nanoseconds, maybe truncated\n    Z                                        # Zulu\n'

**Comment by dhermes** [comment]
@hir3npatel Can you provide more of a stacktrace?

**Comment by hir3npatel** [comment]
@dhermes thanks for being all over these bugs, you are very quick and responsive ;)

Sorry I should have provided more details, what I reported was a bit useless, apologies.

> Traceback (most recent call last):
>   File "test.py", line 17, in <module>
>     entries, token = client.list_entries(order_by=logging.ASCENDING, page_token=token, filter_=filterb)
>   File "/usr/lib/python2.7/site-packages/google/cloud/logging/client.py", line 202, in list_entries
>     for resource in resources]
>   File "/usr/lib/python2.7/site-packages/google/cloud/logging/client.py", line 153, in _entry_from_resource
>     return TextEntry.from_api_repr(resource, self, loggers)
>   File "/usr/lib/python2.7/site-packages/google/cloud/logging/entries.py", line 115, in from_api_repr
>     timestamp = _rfc3339_nanos_to_datetime(timestamp)
>   File "/usr/lib/python2.7/site-packages/google/cloud/_helpers.py", line 424, in _rfc3339_nanos_to_datetime
>     dt_str, _RFC3339_NANOS.pattern))
> ValueError: Timestamp: u'2016-10-10T06:18:47Z', does not match pattern: '\n    (?P<no_fraction>\n        \\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}  # YYYY-MM-DDTHH:MM:SS\n    )\n    \\.                                       # decimal point\n    (?P<nanos>\\d{1,9})                       # nanoseconds, maybe truncated\n    Z                                        # Zulu\n'

I have seen pull 1785, which was done in May. I think I'm using a logging lib that should have included that pull, I'm not sure though.

>  pip list |grep cloud-logging
> google-cloud-logging (0.20.0)

**Comment by hir3npatel** [comment]
Looking at the latest release and the tags here, it is a bit confusing. the 0.20.0 umbrella tag is perhaps not what the pip package is using. If I run a pip install --upgrade google.cloud on the host, to make sure I have the latest versions, and rerun that logging script, I get the same error.

For a full list of packages after the --upgrade google.cloud, this is what I have.

gapic-google-logging-v2 (0.10.1)
gapic-google-pubsub-v1 (0.10.1)
google-cloud (0.20.0)
google-cloud-bigquery (0.20.0)
google-cloud-bigtable (0.20.0)
google-cloud-core (0.20.0)
google-cloud-datastore (0.20.1)
google-cloud-dns (0.20.0)
google-cloud-error-reporting (0.20.0)
google-cloud-language (0.20.0)
google-cloud-logging (0.20.0)
google-cloud-monitoring (0.20.0)
google-cloud-pubsub (0.20.0)
google-cloud-resource-manager (0.20.0)
google-cloud-storage (0.20.0)
google-cloud-translate (0.20.0)
google-cloud-vision (0.20.0)
google-gax (0.14.1)
googleapis-common-protos (1.5.0)
grpc-google-iam-v1 (0.10.1)
grpc-google-logging-v2 (0.10.1)
grpc-google-pubsub-v1 (0.10.1)

**Comment by dhermes** [comment]
@tseaver it seems that `(?P<nanos>\d{1,9})` is insufficient to cover the `nanos = 0` case. This change is needed:

```diff
diff --git a/core/google/cloud/_helpers.py b/core/google/cloud/_helpers.py
index f4f6b43..5c85e22 100644
--- a/core/google/cloud/_helpers.py
+++ b/core/google/cloud/_helpers.py
@@ -53,8 +53,10 @@ _RFC3339_NANOS = re.compile(r"""
     (?P<no_fraction>
         \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}  # YYYY-MM-DDTHH:MM:SS
     )
-    \.                                       # decimal point
-    (?P<nanos>\d{1,9})                       # nanoseconds, maybe truncated
+    (                                        # Optional decimal part
+     \.                                      # decimal point
+     (?P<nanos>\d{1,9})                      # nanoseconds, maybe truncated
+    )
     Z                                        # Zulu
 """, re.VERBOSE)
 # NOTE: Catching this ImportError is a workaround for GAE not supporting the
```

Seem right?
