### ISSUE TITLE
API not respecting destination table

### ISSUE THREAD

**Issue by mattjo** [GoogleCloudPlatform/gcloud-python#1786]
Following the example at https://googlecloudplatform.github.io/gcloud-python/stable/bigquery-usage.html#querying-data-asynchronous the destination table does not appear to be respected

Reproduction steps and observed behavior: 

```python
QUERY = 'SELECT * FROM [dataset.babynames] where name = "Beth"'
dataset = client.dataset('dataset')
table = dataset.table(name='only_beth')
job = client.run_async_query('only_beth', QUERY)
job.destination_table = table
job.write_disposition = 'WRITE_EMPTY'
job.begin()
job.reload()
job.state
'DONE'
```
Job has `write_disposition`: `WRITE_TRUNCATE` and `destination table_id`: `"anon6f3505ba6efbcaaa685e4812bf5e132db2bb343a"`

--

Expected behavior: Job should have created a new table called beth_only and set write disposition to `WRITE_EMPTY`

**Comment by dhermes** [comment]
You never called `table.create()`, though I'm surprised that this code worked since the destination table didn't exist. @tseaver Can you take a look?

**Comment by ToddMorrill** [comment]
Table creation shouldn't be an issue according this: https://cloud.google.com/bigquery/docs/reference/v2/jobs

configuration.copy.createDisposition

Default is: "CREATE_IF_NEEDED: If the table does not exist, BigQuery creates the table."

**Comment by dhermes** [comment]
D'oh! My bad.

**Comment by tseaver** [comment]
@ToddMorrill I cannot reproduce here:  your example triggers an attribute error for `job.destination_table` (that attribute of the job was renamed back in December in commit ad5774448a8ac00493f8a1c7b8a39ffa021e0c53).

When I correct it to `job.destination`, and run the job, the data is saved as expected in the newly-created table.

**Comment by ToddMorrill** [comment]
Much appreciated, looks like it's just a matter of documentation. See here, where it is still being called "job.destination_table" https://googlecloudplatform.github.io/gcloud-python/stable/bigquery-usage.html
