### ISSUE TITLE
"Project was not passed" error, even though ran 

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/gcloud-python#1792]
I attempted  to follow the setup instructions and ran into an odd error. The instructions I was following are here: https://googlecloudplatform.github.io/gcloud-python/stable/gcloud-auth.html

Here is what I attempted:

1. `virtualenv ~/venv`
2. `source ~/venv/bin/activate`
3. `pip install gcloud`
4. `gcloud auth login`
5. `python`
```
>>> from gcloud import pubsub
>>> pubsub.Client()
```

Here's the error I received when I ran pubsub.Client()

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/local/lib/python2.7/site-packages/gcloud/client.py", line 184, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File ".../venv/local/lib/python2.7/site-packages/gcloud/client.py", line 143, in __init__
    raise EnvironmentError('Project was not passed and could not be '
EnvironmentError: Project was not passed and could not be determined from the environment.

```
I do appear to have valid credentials. `gcloud.credentials.get_credentials()` happily provides me with a perfectly good GoogleCredentials object which works fine with httplib2 if I invoke it directly.

**Comment by tseaver** [comment]
Thanks for the report!  In addition to credentials, we need to know what [project](http://googlecloudplatform.github.io/gcloud-python/stable/bigquery-usage.html#projects) to use:  a given set of credentials can have access to multiple projects.  On GCE / GAE, we can determine the project from the host setup.  On your own machine, you need to set an environment variable.  E.g.:

```bash
$ export GCLOUD_PROJECT=flaky-piecrust-227
```

Or you can pass the project to the `Client` constructor:

```python
>>> from gcloud import pubsub
>>> client = pubsub.Client('flaky-piecrust-227')
```

I think the "usage doc" sections should all link to a shared page explaining this requirement (similar to the [Authentication](http://googlecloudplatform.github.io/gcloud-python/stable/gcloud-auth.html) page).  @dhermes, @jgeewax WDYT?

**Comment by daspecster** [comment]
So I ran into this when I started and I was wonder why the project ID isn't picked up from the credentials file?

```javascript
{
  "type": "service_account",
  "project_id": "<PROJECT_ID>",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": ""
}
```


We recommend that you use separate credentials for different projects, so I would think it would be ok to pull it from there.

> you may want to use two separate accounts to simultaneously access data from different projects

https://googlecloudplatform.github.io/gcloud-python/stable/gcloud-auth.html#explicit-credentials

**Comment by dhermes** [comment]
Good call @daspecster, it's never occurred to us.

**Comment by daspecster** [comment]
@dhermes, Is this something that should happen in oauth2client?

**Comment by dhermes** [comment]
Not really. `oauth2client` is only concerned with auth.
