### ISSUE TITLE
Stop using undoc-members

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1800]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1772/files#r63362850

**Comment by dhermes** [comment]
AFAIK we use `undoc-members` to make sure all public methods / attributes are documented even if we forget to provide a docstring. @tseaver I'm not sure what issue you were trying to raise, could you elaborate?

**Comment by tseaver** [comment]
If we don't provide docs, it isn't part of the API, even if it happens not to start with an `_`.  This issue may be moot, as pylint may barf w/o a docstring.

**Comment by dhermes** [comment]
Yeah but the way we've built this library, everything that happens to not start with an `_` is **intended** to be public. So `undoc-members` is a protection against human error (like I said, if we forgot to provide a docstring).

**Comment by tseaver** [comment]
I would say that exposing the syntax/signature without explaining the semantics isn't helping the user:  it would be better to have `tox -e docs` barf due to lack of coverage.

**Comment by dhermes** [comment]
I'm totally fine with that.
