### ISSUE TITLE
Why are we pinned to grpcio == 0.13.1

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1801]
@tseaver Sorry I missed cbc24de1005e4abcca01d0c36184808a12b19485 in review of #1764, but what is the long-term plan to fix?

At the very least https://github.com/googleapis/googleapis/issues/17 should be re-opened.

/cc @tbetbetbe

**Comment by tseaver** [comment]
`grpcio` 0.14 removes deprecated members that `gax-google-pubsub-v1` still depends on (the issue you referenced).  @thobrla told me yesterday that there should be a new release today fixing that issue.

**Comment by thobrla** [comment]
FWIW, I don't recall discussing this topic yesterday.

**Comment by dhermes** [comment]
:grinning: I think @tseaver meant to type @tbetbetbe and GitHub autocomplete misguided him

**Comment by tseaver** [comment]
Yup, sorry for the noise.

**Comment by tseaver** [comment]
Closed via #1855.
