### ISSUE TITLE
BigQuery UDF is not usable?

### ISSUE THREAD

**Issue by takbab** [GoogleCloudPlatform/gcloud-python#1829]
Hi,
I want to use UDF in the query of BigQuery.
gcloud-python supports it?

**Comment by tseaver** [comment]
https://cloud.google.com/bigquery/user-defined-functions

**Comment by tseaver** [comment]
The `Jobs` resource in BigQuery V2 has a `configuration.query.userDefinedFunctionResources` field, which is marked "experimental" in the [BigQuery V2 proto](https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest). `gcloud-python` does not expose that feature at this point.

**Comment by dhermes** [comment]
But we could?

**Comment by tseaver** [comment]
Sure, we could add that support.

**Comment by simple-design** [comment]
Thank you for the reply.

i have got the current situation and will ask GCP support team why `configuration.query.userDefinedFunctionResources` is experimental.

Regards,

**Comment by dhermes** [comment]
@jgeewax WDYT?

**Comment by simple-design** [comment]
i could not get anything from GCP support team. They have the internal issue.

**Comment by tseaver** [comment]
@simple-design if you'd like to submit a PR which adds support for that field, we'd be glad to review it.

**Comment by tseaver** [comment]
Via #2007.
