### ISSUE TITLE
read-only permissions don't throw an exception on an attempted write

### ISSUE THREAD

**Issue by Taywee** [GoogleCloudPlatform/gcloud-python#1846]
When a user with read-only credentials on a bucket connects and attempts to write a blob, it silently exits as if it succeeded even though nothing was written.

This service account has only read permissions on the bucket referenced (project and bucket name have been changed for this example).

```python
credentials = ServiceAccountCredentials.from_json_keyfile_dict(credentials_dict)
client = storage.Client(credentials=credentials, project='testproject')
bucket = client.get_bucket('testbucket')
blob = bucket.blob('testblob')
blob.upload_from_string('this is a test blob\n')
```

Nothing gets uploaded, but the final function call exits with no indication of failure.

**Comment by dhermes** [comment]
@Taywee This sounds like either an error in the backend (I'd expect a 400 or 403) or an error in the credentials loaded. When you say "read-only credentials", you mean that your account only has read access to your bucket?

**Comment by Taywee** [comment]
Yes, that's what I mean.  Only read-access to the bucket.

**Comment by Taywee** [comment]
When I update the permissions so the service user has write-permissions, it writes the object, but when the service account has only read permissions on the bucket, the code execution gives no indication.

**Comment by dhermes** [comment]
It's not really about the code execution, the backend should reject the request if you really didn't have write permissions, then we'd throw an exception for a non-200 response. By default `read_write` is [one of the scopes][1] used when creating auth tokens, so if the account does have write access it will.

Maybe the writer/reader permissions on that account aren't quite what they seem?

You saying the `upload_from_string` call fails to upload and there is no indication of the failure. Have you checked after the fact that nothing got uploaded?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/92e9362f5246ecea1a9f96ea104353d3caf7623c/gcloud/storage/connection.py#L40-L42

**Comment by Taywee** [comment]
Yes.  I've checked.  It's certain that nothing gets uploaded, and after I switch the service account to allow write permissions, upload happens with no change to the python code.

**Comment by dhermes** [comment]
Interesting! I'd love to be able to reproduce to dig in deeper. Where in the cloud console have you set the read-only setting for your service account.

It seems [`Blob._check_response_error`][1] would catch the error if there was one?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/92e9362f5246ecea1a9f96ea104353d3caf7623c/gcloud/storage/blob.py#L352

**Comment by Taywee** [comment]
I set them in the bucket permissions.
![2016-06-08-102558_334x142_scrot](https://cloud.githubusercontent.com/assets/1069915/15902087/7ad532e6-2d63-11e6-8be7-2b89b6643495.png)
![2016-06-08-102606_768x644_scrot](https://cloud.githubusercontent.com/assets/1069915/15902088/7ad6e276-2d63-11e6-8581-7a74aaafc2ad.png)

The last entry is my service user there.

**Comment by dhermes** [comment]
I wonder what happens if your service account is also among owners and editors for your project. Can you [confirm what group it's in][1]?

[1]: https://console.cloud.google.com/iam-admin/iam/project

**Comment by Taywee** [comment]
Looks like the service account is in neither of those groups.

**Comment by dhermes** [comment]
Digging in now to reproduce.

**Comment by dhermes** [comment]
I can't reproduce. I'm getting 403 Forbidden when I try to `upload_from_string`.

I have it as a [reader on the bucket][1]

![screen_shot_001](https://cloud.githubusercontent.com/assets/520669/15940896/dd71c9a8-2e32-11e6-913f-18148bb4bf1c.png)

and it is a [viewer on the project][2]

![screen_shot_002](https://cloud.githubusercontent.com/assets/520669/15940928/f89255cc-2e32-11e6-9860-9b08c51866be.png)

[1]: https://console.cloud.google.com/storage/browser
[2]: https://console.cloud.google.com/iam-admin/iam/project

**Comment by Taywee** [comment]
Interesting.  I'll make a new user and flow through the process now to see if I can replicate the issue, providing all the steps here (I'm trying to keep it as readable as possible, sorry if it's messy).

#### I go into API Library, then Credentials, and do create service account key.

![2016-06-09-123114_1033x239_scrot](https://cloud.githubusercontent.com/assets/1069915/15941602/2a618afe-2e3e-11e6-942f-a88e8af0144e.png)
![2016-06-09-123140_910x744_scrot](https://cloud.githubusercontent.com/assets/1069915/15941603/2a6392e0-2e3e-11e6-999d-3197796eee41.png)

---

#### I create it as such, and download the file `absperfStandard-4e745b8c607d.json`. I then go into cloud storage and create a bucket `shoulddenybucket`, altering it so the user should have read-only permission:

![2016-06-09-123253_383x337_scrot](https://cloud.githubusercontent.com/assets/1069915/15941702/992730d8-2e3e-11e6-8a4f-d09070d27a5b.png)
![2016-06-09-123411_749x529_scrot](https://cloud.githubusercontent.com/assets/1069915/15941703/992935d6-2e3e-11e6-9824-0d55d33bc459.png)
![2016-06-09-123445_753x605_scrot](https://cloud.githubusercontent.com/assets/1069915/15941704/9935efa6-2e3e-11e6-8812-fe6906f6c2d1.png)
![2016-06-09-123529_494x298_scrot](https://cloud.githubusercontent.com/assets/1069915/15941723/aa5eb376-2e3e-11e6-936f-08e52cdc294f.png)

```python
>>> from gcloud import storage
>>> from oauth2client.service_account import ServiceAccountCredentials
>>> credentials = ServiceAccountCredentials.from_json_keyfile_name('absperfStandard-4e745b8c607d.json')
>>> client = storage.Client(credentials=credentials, project='absperfstandard')
>>> bucket = client.get_bucket('shoulddenybucket')
>>> blob = bucket.blob('fooblob')
>>> blob.upload_from_string('this is a test string')
>>> 
```

---

#### And `shoulddenybucket` is still empty after a refresh:

![2016-06-09-123956_911x277_scrot](https://cloud.githubusercontent.com/assets/1069915/15941882/5310bb7c-2e3f-11e6-8cb0-1bbcf2203459.png)

---

#### But changing the user to a writer on shoulddenybucket and executing the same code with the same `None` returned from the `upload_from_string` method call:

![2016-06-09-124046_735x529_scrot](https://cloud.githubusercontent.com/assets/1069915/15941946/8749e8dc-2e3f-11e6-8ac4-a2ed6d2c5bc4.png)
![2016-06-09-124138_929x285_scrot](https://cloud.githubusercontent.com/assets/1069915/15941947/874a2784-2e3f-11e6-83c0-7efdbbbc4ff8.png)

---

#### The blob is there, but neither time raised any kind of exception. Looking in IAM and searching for the user, I similarly see nothing:

![2016-06-09-124254_1464x396_scrot](https://cloud.githubusercontent.com/assets/1069915/15942014/d9a5d29e-2e3f-11e6-895a-553a7495370b.png)

**Comment by Taywee** [comment]
Also, changing the user back to read-only, and trying to overwrite the named blob `fooblob` still exits without an exception being thrown, but does not actually overwrite the file.

Removing the user from bucket permissions entirely gives an expected exception:

![2016-06-09-125624_746x560_scrot](https://cloud.githubusercontent.com/assets/1069915/15942442/9f690388-2e41-11e6-9be4-5918151a0cba.png)

```python
>>> from gcloud import storage
>>> from oauth2client.service_account import ServiceAccountCredentials
>>> credentials = ServiceAccountCredentials.from_json_keyfile_name('absperfStandard-4e745b8c607d.json')
>>> client = storage.Client(credentials=credentials, project='absperfstandard')
>>> bucket = client.get_bucket('shoulddenybucket')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/gcloud/storage/client.py", line 167, in get_bucket
    bucket.reload(client=self)
  File "/usr/lib64/python3.4/site-packages/gcloud/storage/_helpers.py", line 77, in reload
    _target_object=self)
  File "/usr/lib64/python3.4/site-packages/gcloud/connection.py", line 343, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.Forbidden: 403 Forbidden (GET https://www.googleapis.com/storage/v1/b/shoulddenybucket?projection=noAcl)
>>> 
```

**Comment by dhermes** [comment]
At the very beginning when you create the account, it is by default a project editor. Can you verify that?

**Comment by Taywee** [comment]
Where could I verify that?  I don't see it anywhere in the IAM list.

**Comment by dhermes** [comment]
I used https://console.cloud.google.com/iam-admin/iam/project to check it.

**Comment by Taywee** [comment]
It's not in there:

![2016-06-09-181205_1459x1455_scrot](https://cloud.githubusercontent.com/assets/1069915/15950662/164ae9e0-2e6e-11e6-9def-3368e0200802.png)

**Comment by dhermes** [comment]
OK. I'll try to create an account and remove it from the list of project editors / viewers / etc.

**Comment by dhermes** [comment]
Still can't reproduce, I'm getting 403 forbiddens.

@thobrla can you take a look?

**Comment by thobrla** [comment]
@dhermes is there a way to make gcloud-python dump the HTTP request / response?  I don't see anything obvious here, but as it stands have no indication of whether this is a client or service problem.

**Comment by dhermes** [comment]
Unfortunately no. I was hoping to reproduce so we didn't have to have @Taywee dig into the source.

@Taywee are you comfortable dropping into [the source][1] and adding a debug trace?

```python

        if upload.strategy == RESUMABLE_UPLOAD:
            http_response = upload.stream_file(use_chunks=True)
        else:
            http_response = make_api_request(connection.http, request,
                                             retries=num_retries)
        import pdb  # ADDED
        pdb.set_trace()  # ADDED

        self._check_response_error(request, http_response)
```

and poking the `request` and `http_response` objects to get an idea of what's in them?

You can find the location of the file via

```python
from gcloud.storage import blob
print(blob.__file__)
```

and if you installed with `sudo`, you'd need to use `sudo` to edit the file (alternatively you could install `gcloud` in a virtual env.)


[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f0c82ba860d8d4bb6f4888f3711f9b66c0c3672a/gcloud/storage/blob.py#L463-L467

**Comment by Taywee** [comment]
Ah, I found the issue.  My gcloud was out of date (was on version 0.11.0).  That version had no _check_response_error call.  I thought I had updated it before testing this.  That was entirely my my mistake.  It works as expected now.  Thanks for the help, and sorry for wasting your time.

**Comment by tseaver** [comment]
@Taywee no worries -- glad the latest release fixes the issue for you.

**Comment by dhermes** [comment]
Thanks @Taywee for the interaction throughout! Clearly it was a bug at one point in time!
