### ISSUE TITLE
Implement Bigtable v2 API

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1850]
@dhermes if you can do a braindump here of what you've learned, and then assign to me, that would be great.

**Comment by dhermes** [comment]
- Only the data API is in `v2`, the table and cluster admins are still `v1`
- The majority of the changes are in [`ReadRowsResponse`][1].
- `google/bigtable/v2/data.proto` is essentially equivalent to `google/bigtable/v1/bigtable_data.proto`
- `google/bigtable/v2/bigtable.proto` is essentially equivalent to `google/bigtable/v1/bigtable_service.proto` and `google/bigtable/v1/bigtable_service_messages.proto`
- [Some of][2] the inclusive / exclusive fields have changed, but that's somewhat easy to track
- There is a [new method][3] in the `v1` Table Admin API that we should implement

[1]: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/174be4cfe215dc1f0edcceb798ce82d94423f3e8/bigtable-protos/src/main/proto/google/bigtable/v2/bigtable.proto#L116-L190
[2]: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/174be4cfe215dc1f0edcceb798ce82d94423f3e8/bigtable-protos/src/main/proto/google/bigtable/v2/data.proto#L87-L102
[3]: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/174be4cfe215dc1f0edcceb798ce82d94423f3e8/bigtable-protos/src/main/proto/google/bigtable/admin/table/v1/bigtable_table_service.proto#L76-L78

**Comment by garye** [comment]
Some additional information:

- Every API is in v2, not just data. See https://github.com/GoogleCloudPlatform/cloud-bigtable-client/tree/master/bigtable-protos/src/main/proto/google/bigtable/admin/v2.
- `ReadRowsResponse` has changed quite a bit. Let's talk offline about the implementation and testing.
- You now connect with project/instance rather than project/zone/cluster. This change is pervasive.
- All column family operations are consolidated into `ModifyColumnFamilies`.
- GC rules can no longer be expressed as strings/expressions
- `MutateRows` returns a streaming response
- `ReadRowsRequest` allows repeating ranges/sets

**Comment by sduskis** [comment]
I'd guess that MutateRows, bulk delete, and "bulk read" (a set of random row keys) are not in the current python implementation, since they were not there from day one and we added them along the way.  They are useful, but not required functionality.

**Comment by sduskis** [comment]
We have a [java implementation](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/scanner/v2/RowMerger.java) and a [go implementation](https://team.git.corp.google.com/go-cloud/gocloud-exp/+/refs/changes/30/40630/8/bigtable/reader.go#) which process v2 ReadRowsResponse objects.  Hopefully, they can help give some insight into how to implement the new API.  There's also a [json file](https://team.git.corp.google.com/go-cloud/gocloud-exp/+/refs/changes/30/40630/8/bigtable/testdata/read-rows-acceptance-test.json) we use to drive automated tests; we can explain more about it offline.

**Comment by garye** [comment]
If we implement happybase's `Table.batch` then `MutateRows` would be helpful to leverage, but I agree with Solomon that it's not required.

**Comment by sduskis** [comment]
Yeah, the new MutateRows is pretty awesome.  It has a significant performance improvement over MutateRow. 

Anything related to v2 comes first due to time sensitivity.  We have a few performance improvement (MutateRows, multiple grpc channels) and reliability (retries) improvements that aren't as time sensitive.

**Comment by garye** [comment]
Here's a link to the go read rows implementation.
https://gist.github.com/garye/4b2ce32f8b6245e1024c7ce0a37b681d

**Comment by tseaver** [comment]
I've set up a [feature branch](https://github.com/GoogleCloudPlatform/gcloud-python/tree/bigtable-v2) for this project:  I intend to merge PRs to that branch, and then merge that branch to `master`.

**Comment by tseaver** [comment]
Reviewing open `gcloud-python` issues related to Bigtable:

- `Table.rename` returns a "not implemented" error (#1289).  Is that method actually implemented in V2?
- Generating code from the new `.proto` files is a pain (#1482).  Will there be a project published to PyPI containing that code (#1384).  E.g., see  [`grpc-google-logging-v2`](https://pypi.python.org/pypi/grpc-google-logging-v2`).

**Comment by sduskis** [comment]
RenameTable was removed in v2. While it existed in v1, it was never actually implemented. Good catch.

**Comment by lesv** [comment]
The protos should be at https://github.com/GoogleCloudPlatform/gcloud-python/pull/1895

**Comment by garye** [comment]
#1895  is bogus because it's targeted at master and breaks everything anyways, but at least look at the Makefile change. I fixed the makefile to find grpc_python_plugin wherever it is in your path but there's also a python script that runs and assumes a location, so I ended up copying grpc_python_plugin to the gcloud-python dir before running `make generate`.

**Comment by tseaver** [comment]
Tasks:

- [ ] Package proto-generated Python code for releaes to PyPI (see #1384).  If not feasible, regenerate using the `Makefile` and check in (see @garye's work on PR #1895).
- [ ] Update imports to reflect new generated module names.
- [ ] Update API endpoint configuration.
- [ ] Drop never-actually-impemented `Table.rename` (see #1289).
- [ ] Adjust `ColumnFamily` operations, collapsing three V1 endpoints into a single V2 endpoint.
- [ ] Adjust spelling for range boundaries: `open` -> `exclusive`, `closed` -> `inclusive`.
- [ ] Implement new `ReadRowResponse` semantics.  Consult[Go implementation](https://gist.github.com/garye/4b2ce32f8b6245e1024c7ce0a37b681d), [Java implementation](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/scanner/v2/RowMerger.java), and [JSON testcases](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core/src/test/resources/com/google/cloud/bigtable/grpc/scanner/v2/read-rows-acceptance-test.json).

**Comment by lesv** [comment]
@tswast FYI

**Comment by tswast** [comment]
Question for the eng team CCed on this thread. I see there are some more streaming APIs. Would it be possible to implement these APIs in the client as iterators (and stream the underlying results)?

https://github.com/GoogleCloudPlatform/gcloud-python/issues/1812

Right now for PartialRowsData, the client accumulates the results in a semi-hidden list.

**Comment by tseaver** [comment]
@sduskis 

>  There's also a json file we use to drive automated tests; we can explain more about it offline.

I'm trying to parse the `chunks` entries in that file via `ReadRowsResponse.CellChunk.FromString`, but that raises an exception:  am I holding it wrong?

**Comment by garye** [comment]
Sounds like it should work - what was the exception?

**Comment by tseaver** [comment]
This session is based on the new generation-from-protos stuff in PR #1903.

```python
>>> import json
>>> from gcloud.bigtable._generated_v2.bigtable_pb2 import ReadRowsResponse
>>> with open('gcloud/bigtable/read-rows-acceptance-test.json') as f:
...     test_json = json.load(f)
... 
>>> chunk_pb = test_json['tests'][0]['chunks'][0]
>>> ReadRowsResponse.CellChunk.FromString(chunk_pb)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 780, in FromString
    message.MergeFromString(s)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1080, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1106, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 799, in _SkipGroup
    new_pos = SkipField(buffer, pos, end, tag_bytes)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.
```

**Comment by tseaver** [comment]
FWIW `chunk_pb` looks like a normal protobuf to me:

```python
>>> chunk_pb
u'row_key: "RK"\nfamily_name: <\n  value: "A"\n>\nqualifier: <\n  value: "C"\n>\ntimestamp_micros: 100\nvalue: "value-VAL"\ncommit_row: false\n'
```

**Comment by garye** [comment]
I don't know the python protobuf APIs, but it looks like there are other
things like MergeFromString and
https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.text_format-module
that
might be an alternative?

**Comment by tseaver** [comment]
I missed that those chunks are rendered using `text_format`.  The following works to parse one:

```python
>>> from google.protobuf.text_format import Merge
>>> Merge(chunk-pb, chunk)
```

**Comment by garye** [comment]
Ah, sorry we should have mentioned. Glad it's working.

**Comment by tseaver** [comment]
@garye Am I meant to neglect the `google.bigtable.v2.instance.Instance.cluster` and related messages?

**Comment by garye** [comment]
@tseaver You mean for cluster administration?

**Comment by tseaver** [comment]
Yes -- am I supposed to be exposing the methods to manipulate clusters within an instance?

**Comment by sduskis** [comment]
We don't do that in go or Java.  I would think Happybase doesn't have a way to manage clusters in v1 or instances in v2, since HBase doesn't have any similar concepts.  If there isn't currently a way to do cluster management, we should not add new functionality.

**Comment by tseaver** [comment]
@sduskis I was just asking because `gcloud.python` exposed cluster managment APIs for V1:  if they aren't relevant for V2, cool (they are defined right next to the V2 instance management APIs, which is which is what made me ask).

**Comment by sduskis** [comment]
Thanks for clarifying.  I'd guess we need to expose operations that are similar to the way the GCP console operates.  There is a ClusterService for some operations like resizing a cluster or changing the display name.  I don't know enough about that.  I'll ping the group to find out more about this.

The bottom line is that we need parity with the existing functionality in gcloud.python through the new APIs.
