### ISSUE TITLE
Dataproc module

### ISSUE THREAD

**Issue by tshauck** [GoogleCloudPlatform/gcloud-python#1853]
Hi,

I wrote a python package called [Dataproctor](https://github.com/tshauck/Dataproctor) which wraps Dataproc's API and creates python objects which represent the API response, similarly to how this package works compared to the standard python client library.

When I wrote that I didn't know about this and since this doesn't yet work with Dataproc, if I ported this over to fit this project's guidelines, is this PR you'all would potentially accept?

Thanks

**Comment by jgeewax** [comment]
@tshauck : Wow -- that'd be fantastic. Definitely. And let me know if you need someone from the Dataproc team to help out with anything and I can connect you!

**Comment by tshauck** [comment]
@jgeewax Alright, great, thanks.  I'll get started and reach out and I'll reach out if (when 😄) I run into issues.

/cc @daspecster
