### ISSUE TITLE
Datastore transactions do not work without context manager

### ISSUE THREAD

**Issue by Bogdanp** [GoogleCloudPlatform/gcloud-python#1859]
[The docs][docs] state that you can use transactions without a context manager, but this is not exactly true because you need to resort to some private methods on `Client`:

* [this file][context] uses the context manager and produces correct output
* [this file][broken] uses transactions as described by the aforementioned docs and fails the assertion
* [this file][working] uses transactions along with calls to `client._push_batch` and `client._pop_batch` and produces correct output

The issue is evident in [`Client.get_multi`][get_multi] and [`Client.put_multi`][put_multi] where `transaction` and `current` are `None` unless a `Batch` or `Transaction` has been pushed to the `_batch_stack` and the only time that happens is when you [`__enter__`][enter] a `Batch`.

[docs]: https://googlecloudplatform.github.io/gcloud-python/stable/datastore-transactions.html#gcloud.datastore.transaction.Transaction
[context]: https://gist.github.com/Bogdanp/a86192d1a2a37dd48df5ebdbb39a49d1#file-context-py-L20
[broken]: https://gist.github.com/Bogdanp/a86192d1a2a37dd48df5ebdbb39a49d1#file-failing-py-L20
[working]: https://gist.github.com/Bogdanp/a86192d1a2a37dd48df5ebdbb39a49d1#file-passing-py-L20
[get_multi]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/client.py#L284
[put_multi]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/client.py#L336
[enter]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/batch.py#L273

**Comment by daspecster** [comment]
@Bogdanp thanks for finding this!

In the case where the assertions fail, is it both values or just one of them that isn't getting set when you `t.commit()`?

**Comment by Bogdanp** [comment]
Both values are updated. However, due to the fact that there is no [transaction id][tid] "in scope" for those get and put requests, the serializability of the operations is not enforced.

[tid]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/client.py#L292

Here's some sample output:

```fish
(tempenv-3357153745070) ~ [1]> env DATASTORE_DATASET="test" DATASTORE_PROJECT_ID="test" DATASTORE_HOST="http://127.0.0.1:9999" python failing_test.py 
60
40
Traceback (most recent call last):
  File "failing_test.py", line 54, in <module>
    assert a1["balance"] == 100 - n * 10
AssertionError
```

I just added a couple of print statements before the assertions in the failing example:

```python
    print a1["balance"]
    print a2["balance"]

    assert a1["balance"] == 100 - n * 10
    assert a2["balance"] == n * 10
```

**Comment by tseaver** [comment]
`Client.put_multi` is never called in your failing example:  the changes are all accumulated inside the transaction's `_commit_request` protobuf.  I think the error is that the transaction ID ([fetched during `Transaction.begin`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/835d2dc97e03941bc2004b6e819220a21f613c99/gcloud/datastore/transaction.py#L130)) is not being stored into that protobuf.

**Comment by tseaver** [comment]
I just tried to write a system test replicating your failing report, and found that it passes:

```python
    def test_transaction_via_imperative_begin_commit(self):
        BEFORE_1 = 100
        BEFORE_2 = 0
        TRANSFER_AMOUNT = 40
        key1 = Config.CLIENT.key('account', '123')
        account1 = datastore.Entity(key=key1)
        account1['balance'] = BEFORE_1
        key2 = Config.CLIENT.key('account', '234')
        account2 = datastore.Entity(key=key2)
        account2['balance'] = BEFORE_2
        Config.CLIENT.put_multi([account1, account2])

        def transfer_funds(client, from_key, to_key, amount):
            xact = client.transaction()
            xact.begin()
            from_account = client.get(from_key)
            to_account = client.get(to_key)
            from_account['balance'] -= amount
            to_account['balance'] += amount

            xact.put(from_account)
            xact.put(to_account)
            xact.commit()

        transfer_funds(Config.CLIENT, key1, key2, TRANSFER_AMOUNT)

        after1 = Config.CLIENT.get(key1)
        after2 = Config.CLIENT.get(key2)
        self.assertEqual(after1['balance'], BEFORE_1 - TRANSFER_AMOUNT)
        self.assertEqual(after2['balance'], BEFORE_2 + TRANSFER_AMOUNT)
```

One issue might be that`Client.get_multi` is not guaranteed to return the items in the order of the requested keys:  can you update your failing example to compensate (e.g., either use `Client.get` or else check the keys of the returned entities)?

**Comment by tseaver** [comment]
(Of course, my example is not threaded with multiple writers, so it is not really a good enough replica).

**Comment by Bogdanp** [comment]
[Here][gist]'s a failing example w/o any `get_multi` calls.

[gist]: https://gist.github.com/Bogdanp/60fbf9655258b969c526a401a33dbfbc

```fish
(tempenv-3357153745070) ~ [1]> env DATASTORE_DATASET="test" DATASTORE_PROJECT_ID="test" DATASTORE_HOST="http://127.0.0.1:9999" python failing_test.py 
60
40
Traceback (most recent call last):
  File "failing_test.py", line 56, in <module>
    assert a1["balance"] == 100 - n * 10
AssertionError
```

BTW, I picked this example specifically because it's what's being used in the [official docs][docs].

[docs]: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/datastore/api/snippets.py#L649

**Comment by Bogdanp** [comment]
Are you sure [this][get_multi] isn't the culprit? `transaction_id` ends up being `None` there unless `_push_batch` is called.

[get_multi]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/datastore/client.py#L292

**Comment by tseaver** [comment]
I was still investigating:  you are correct that `get`/`get_multi` do not provide any support for doing the reads in the context of an *explicit* transaction.  I have a PR in progress which will add that support.

**Comment by tseaver** [comment]
@Bogdanp Thanks for the detailed bug report!  I was able to get a version of your failing script passing on the branch for #1861 (after failing on master in exactly the way you describe here).
