### ISSUE TITLE
Read the Docs build failing

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1864]
https://readthedocs.org/projects/gcloud-python/builds/4108022/
https://readthedocs.org/projects/gcloud-python/builds/4108027/

**Comment by dhermes** [comment]
https://readthedocs.org/projects/gcloud-python/builds/4105578/
https://readthedocs.org/projects/gcloud-python/builds/4105025/

**Comment by daspecster** [comment]
@tseaver these all look like GRPCIO 0.14.0 issues.

Is this something from https://github.com/GoogleCloudPlatform/gcloud-python/issues/1814?

**Comment by bjwatson** [comment]
Yes, the dependency for the pubsub and logging APIs is now on GRPCIO 0.14.0. Looks like the build server needs it installed.

**Comment by daspecster** [comment]
Thanks @bjwatson! I think appveyor needs to clear its cache as well possibly? I haven't used appveyor before though.

**Comment by tseaver** [comment]
@bjwatson The RTD build failures show a huge bunch of compilation warnings trying to build `grpcio 0.14.0`:

```C
In file included from ./include/grpc/support/alloc.h:37:0,
                 from ./src/python/grpcio/grpc/_cython/imports.generated.h:869,
                 from ./src/python/grpcio/grpc/_cython/loader.h:37,
                 from ./src/python/grpcio/grpc/_cython/cygrpc.c:310:
./include/grpc/impl/codegen/alloc.h:68:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 GPRAPI gpr_allocation_functions gpr_get_allocation_functions();
 ^
...
third_party/zlib/gzwrite.c: In function 'gzclose_w':
third_party/zlib/gzwrite.c:573:5: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
     if (close(state->fd) == -1)
     ^
```

followed by:

```python
zip_safe flag not set; analyzing archive contents...
No eggs found in /tmp/easy_install-JdusyT/grpcio-0.14.0/egg-dist-tmp-TNTJot (setup script problem?)
error: The 'grpcio>=0.14.0' distribution was not found and is required by gcloud
```

Any clues to the source of the error?

**Comment by dhermes** [comment]
You could just fake the dep like [`oauth2client` does][1]. This is a recommended practice.

[1]: https://github.com/google/oauth2client/blob/c82816cf7a8a4a3b587b3690937069d502e609f3/docs/conf.py#L13-L15

**Comment by geigerj** [comment]
I don't know about the ultimate source of the error, but I've been seeing the same error message when trying to install packages that depend on grpcio. This seems to be independent of GAX.

I've filed an issue with gRPC here: https://github.com/grpc/grpc/issues/6939

**Comment by bjwatson** [comment]
I just published google-gax 0.12.0, which now depends on grpcio 0.14.0 or above. I also published new versions of gax-google-pubsub and gax-google-logging (0.7.9) to depend on google-gax 0.12.0.

Previously we had a conflict between the version of grpcio that google-gax and gax-google-* wanted.

I don't know if this fixes the issue described here, but it might.

**Comment by bjwatson** [comment]
@tseaver @daspecster See https://github.com/GoogleCloudPlatform/gcloud-python/pull/1866

**Comment by daspecster** [comment]
@bjwatson I just tried it locally with `python setup.py install --force` and I still got...
```
error: The 'grpcio>=0.14.0' distribution was not found and is required by google-gax, gcloud
```

**Comment by bjwatson** [comment]
Hmm... somehow readthedocs needs to be told to `pip install grpcio`. When @geigerj and I do that in our virtualenv's, it breaks like this, _unless_ we run `pip install grpcio` first.

**Comment by daspecster** [comment]
So as per @tseaver's suggestion in #1865, I exclude grpcio and I think it will work. I tested it [locally](https://github.com/GoogleCloudPlatform/gcloud-python/pull/1865#issuecomment-226647265) and it seemed to work.

I think we'll definitely have to figure it out with [Appveyor](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1863) though.

**Comment by bjwatson** [comment]
That's true... I guess it's not needed for the docs.

@geigerj filed https://github.com/grpc/grpc/issues/6939 to cover the grpcio issue. He was able to reproduce it with a very simple test case (without `google-gax` or `gcloud-python`).

**Comment by daspecster** [comment]
Let's move the grpcio conversation over to https://github.com/GoogleCloudPlatform/gcloud-python/issues/1863, unless we reopen this issue.

**Comment by daspecster** [comment]
Looks like it passed!
https://readthedocs.org/projects/gcloud-python/builds/4109895/

**Comment by tseaver** [comment]
Yay!
