### ISSUE TITLE
Have travis-ci run tox -e cover to catch code branch coverage misses

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-python#1872]
As is turns out, coveralls doesn't cover code branch misses very well.
We could have travis run `tox -e cover` to ensure that we have proper code coverage before publishing it to coveralls.

**Comment by dhermes** [comment]
There is a coveralls.io build target as wel

**Comment by daspecster** [comment]
It could go in there.
I was just thinking it made sense in the .travis.yml as part of the build process.

I'm good either way though.

**Comment by dhermes** [comment]
The point is that every PR already has a coverage check

**Comment by daspecster** [comment]
I think the issue is coveralls.io says that there's 100% coverage but `tox -e cover` says there's 99% coverage due to https://github.com/GoogleCloudPlatform/gcloud-python/pull/1870#issuecomment-227229477

**Comment by dhermes** [comment]
WAT! That sucks. Let's figure out what's wrong with coveralls.io instead of doing double duty. Do you need to be added as an admin?

**Comment by daspecster** [comment]
The sad truth appears to be here my friend https://github.com/lemurheavy/coveralls-public/issues/31

**Comment by dhermes** [comment]
Ouch. Based on that, let's switch to codecov.io?

**Comment by daspecster** [comment]
Looks promising!
#1876
