### ISSUE TITLE
Clarification in how to connect the credentials

### ISSUE THREAD

**Issue by designium** [GoogleCloudPlatform/gcloud-python#1896]
Hi,

I've just tried the gcloud-ruby and I'm trying to replicate what I learned there to python.

In the ruby example:

    require "gcloud"

    gcloud = Gcloud.new "PROJECT_ID",
                    "JSON_KEY_WITH_THE_CREDENTIALS"

    vision = gcloud.vision

I'm having big trouble in create the Gcloud object in gcloud-python. Where do I insert the credentials I have?

Based on the current documentations from github and the narrative example, it seems that's already done and I don't know how to do this basic connection.

**Comment by daspecster** [comment]
Hey @designium!
For vision specifically, we haven't implemented that yet.

If you're asking about other services you can simply do something like...
```python
from gcloud import bigquery
client = bigquery.Client.from_service_account_json('/path/to/creds.json')
```

Your project ID should be picked up from the JSON file, or you could set the `GCLOUD_PROJECT` environment variable which will override the id that is in `creds.json`.

```python
from gcloud import bigquery
import os
os.environ['GCLOUD_PROJECT'] = 'my-project-id'
client = bigquery.Client.from_service_account_json('/path/to/creds.json')
```

Let me know if that helps or if you have more questions!

**Comment by designium** [comment]
Thanks for the reply! It wasn't clear if the Gcloud Vision was available for python.
