### ISSUE TITLE
[Documentation Issue] Anchor links have the text hidden underneath the top banner.

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/gcloud-python#1897]
Page Name: all of them
Release: 0.16.0

Clicking an anchor link makes the text jump to the top (good), but then it's hidden by the top banner (bad).

This is especially a problem for small methods like [ColumnFamily.create()](https://googlecloudplatform.github.io/gcloud-python/stable/bigtable-column-family.html#gcloud.bigtable.column_family.ColumnFamily.create).

This is in the Chrome web browser, but I imagine the other browsers have this same problem. My recommendation would to remove the "fixed" positioning of the banner. It should not cover the text.

**Comment by daspecster** [comment]
Thanks @tswast!
This is actually due to the fixed header. I'll see if I can do a quick fix.
