### ISSUE TITLE
Logging is missing from the ReadMe

### ISSUE THREAD

**Issue by rok987** [GoogleCloudPlatform/gcloud-python#1898]
It seems like we have a wrapper for the Logging API in Python. Therefore we should add the following to the ReadMe (just like for the other APIs):

- a link at the top of the ReadMe to the Logging API section
- a Logging API section with descriptions and links to the documentation
- an example of how to use the Logging API

**Comment by daspecster** [comment]
Thanks @rok987! I'll see if I can get that added.
