### ISSUE TITLE
Add validate parameter to gcloud.storage.connection.get_bucket()

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#19]
But make it default to False (http://www.appneta.com/blog/s3-list-get-bucket-default/)

**Comment by jgeewax** [comment]
This is definitely not a blocker for a 1.0 release of gcloud.storage

/cc @tseaver

**Comment by dhermes** [comment]
I made an [argument][1] in #357 that this should be closed:

> Yes the "get all keys" / "get all objects" concept is not something that really applies
> to a mature application (one with more than a few thousand objects). As for the
> people "just getting started", the two HTTP requests won't be such a big deal. What's
> more, we shouldn't be encouraging people to get a list of "all objects" locally; they should
> only use what they need (e.g. for serving a request for a signed-in user).

I'm closing it out with that in mind. @jgeewax @tseaver if you disagree please re-open and let's discuss.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/357#issuecomment-72238344

**Comment by jgeewax** [comment]
I'm fine with closing this out -- but want to clarify that I'm -1 to removing a `get_all_objects` method (or a way to iterate over the keyspace).

**Comment by dhermes** [comment]
Sure thing, we want to keep it around (via `_BlobIterator`).
