### ISSUE TITLE
Support streaming uploads of file-like objects

### ISSUE THREAD

**Issue by linar-jether** [GoogleCloudPlatform/gcloud-python#1909]
How can we upload a file-like object (such as an http response, with an unknown content-length) without writing the file to disk or storing the entire file in-memory?

Seems like the `upload_from_file` option accepts a file-like object but enforces the `size` parameter (which isn't available in case of streaming uploads).

**Comment by daspecster** [comment]
@linar-jether, quickly searching around it appears to be a question with some tough answers.

One possible solution could be to chunk the stream that you're collecting into StringIO objects(which can be used like files and you could set the length to your own specs) and then pass those to `upload_from_file`. That will use a limited amount of member as long as you can upload as fast as the data is streaming in.

See: https://docs.python.org/2/library/stringio.html

**Comment by linar-jether** [comment]
Did you mean composite objects? is there support for this in the library?

**Comment by linar-jether** [comment]
Tried to fix the upload_from_file method to support streaming for file-like objects without a defined size

**Comment by daspecster** [comment]
@linar-jether, not composite objects, just trying to find a workaround.

**Comment by tseaver** [comment]
Via #1914
