### ISSUE TITLE
Consider re-enabling GAX bundling for 'Topic.publish'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1911]
... once a fix is relased for https://github.com/googleapis/gax-python/issues/113

/cc @bjwatson, @geigerj.

**Comment by geigerj** [comment]
I've closed that issue; you should now be able to re-enable bundling.

**Comment by bjwatson** [comment]
@tseaver You should be able to do this now that I published `0.7.11` of https://pypi.python.org/pypi/gax-google-pubsub-v1

**Comment by tseaver** [comment]
FTR, I think we don't want bundling, as we need to stay semantically-compatible with the JSON-over-HTTP version of the API helper.

**Comment by dhermes** [comment]
@tseaver Is it worth adding a sibling method that allows bundling to take advantage of the nice HTTP/2 / gRPC features?

**Comment by tseaver** [comment]
@dhermes I thought about that notion:  also as a way to deal with the oft-desired (foot-gun?) of majyk-iterator-returning `list_foo` methods.

**Comment by bjwatson** [comment]
@dhermes @tseaver +1

**Comment by tseaver** [comment]
Maybe `publish_async`,returning the `Event` instance?  It would have to raise `NotImplementedError` or some such if GAX is not enabled.
