### ISSUE TITLE
[BigQuery] Option to set `useLegacySql` to false on queries

### ISSUE THREAD

**Issue by kelvinabrokwa** [GoogleCloudPlatform/gcloud-python#1927]
My use case here is that there is a certain query that errors on legacy SQL (internal bug) and disabling it will allow the use of [standard SQL](https://cloud.google.com/bigquery/sql-reference/) which fixes it.

see https://cloud.google.com/bigquery/docs/reference/v2/jobs#resource-representations (find `configuration.query.useLegacySql`)

I'm happy to submit a PR is this option makes sense.

**Comment by tseaver** [comment]
@kelvinabrokwa Thanks for the report!  We'd be glad to review / merge a PR for that feature.

**Comment by dhermes** [comment]
@tseaver I can tackle this, sound good?

**Comment by tseaver** [comment]
@dhermes Sure, if @kelvinabrokwa doesn't already have it in progress.

**Comment by kelvinabrokwa** [comment]
@dhermes any progress?

**Comment by dhermes** [comment]
Doing it now. Sorry for the delay.

**Comment by kelvinabrokwa** [comment]
@dhermes no worries! Thank you! 😄

**Comment by tseaver** [comment]
Via #1992.

**Comment by kelvinabrokwa** [comment]
@dhermes @tseaver thank you!
