### ISSUE TITLE
Pub/Sub publish error (Invalid value at 'messages[0].data' (TYPE_BYTES))

### ISSUE THREAD

**Issue by gs2io** [GoogleCloudPlatform/gcloud-python#1947]
Hi,

I use "google_api_python_client-1.5.1" from pip.
I try Pub/Sub message publish to topic.

````
topics.publish(topic='topicId',
               body={
                     'messages': [{
                                   'messageId': str(uuid.uuid4()),
                                   'data': base64.encodestring('Hello')
                                  }]
                     }).execute()
````

error occurred, and return this message.

````
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://pubsub.googleapis.com/v1/projects/projectId/topics/topicId:publish?alt=json returned "Invalid value at 'messages[0].data' (TYPE_BYTES), "SGVsbG8=
````

I look like this issue.
https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/713

**Comment by tseaver** [comment]
This project does not release the `google_api_python_client` library.  Please consider reporting this issue to the tracker for that project:

  https://github.com/google/google-api-python-client/

Our library is `gcloud`:

  https://pypi.python.org/pypi/gcloud

Pubsub usage docs for `gcloud`:

  http://gcloud.readthedocs.io/en/stable/pubsub-usage.html

**Comment by gs2io** [comment]
oh, sorry...
