### ISSUE TITLE
Migrate to gRPC GA APIs

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/gcloud-python#1949]
The exception types thrown are changing in the gRPC GA APIs compared to the beta APIs currently used.
https://github.com/grpc/grpc/issues/7002#issuecomment-228103984

To minimize the amount of code users of the Cloud Bigtable APIs will need to rewrite, we should migrate to the GA APIs ASAP.

**Comment by tseaver** [comment]
@tswast I'm fine with using the GA version of the API.  It would be good the the gRPC team [updated their examples](https://github.com/grpc/grpc/issues/4977) to show us how.

**Comment by tseaver** [comment]
Via #2149.
