### ISSUE TITLE
Add ability to pull snippets when generating JSON documentation

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-python#1951]
We have a lot of great snippet code that we should be able to include when we generate docs.

See: [pubsub_snippets.py](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/docs/pubsub_snippets.py)

**Comment by tseaver** [comment]
FTR, those snippets are embedded into Sphinx narrative docs and into docstrings via the `.. literalinclude:` directives.

**Comment by daspecster** [comment]
Yeah, I will need to recreate the `literalinclude` directive functionality and add the ability to parse the files and `START` and `END` [sections](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/docs/pubsub_snippets.py#L48).

**Comment by daspecster** [comment]
Currently the generator isn't pulling in any RST files. Grabs the doc strings from the modules/classes/methods/functions. 

What I'm thinking of doing just for right now is just grabbing the snippets and populating the `examples = []` with the snippets.

@tseaver, do you think it would be possible to move the snippets to the module/class/etc doc strings later on or would that make things too messy?

**Comment by daspecster** [comment]
Added to #1775.
