### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by fyellin** [GoogleCloudPlatform/gcloud-python#1961]
Page Name: bigtable-instance-api
Release: 0.17.0

list_intances() should be list_instances()

**Comment by daspecster** [comment]
Thanks @fyellin!
This is actually fixed on `master` and will get resolved in the next release.

**Comment by tseaver** [comment]
[Stable](http://googlecloudplatform.github.io/gcloud-python/stable/bigtable-instance-api.html) only gets updated when a release is made.  [Latest](http://googlecloudplatform.github.io/gcloud-python/latest/bigtable-instance-api.html) is correct.
