### ISSUE TITLE
Update our docstrings for PEP 257

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-python#1968]
PyLint has added checks to more closely follow [PEP 257](https://www.python.org/dev/peps/pep-0257/) which caused linting to fail. We should update our docstrings so we can revert  #1967.

**Comment by tseaver** [comment]
Note that pylint 1.6 actually barfs on two of our source files:

- gcloud/bigtable/happybase/connection.py
- gcloud/streaming/http_wrapper.py

**Comment by tseaver** [comment]
See: https://github.com/PyCQA/pylint/issues/998

**Comment by dhermes** [comment]
I'm digging in to this (hopefully the global disables in #1974 can be addressed easily)

**Comment by dhermes** [comment]
I commented on https://github.com/PyCQA/pylint/issues/125, which flags our use of `grpc.framework.interfaces.face.face.NetworkError` with 

```
Catching an exception which doesn't inherit from BaseException: NetworkError (catching-non-exception)
```

**Comment by tseaver** [comment]
Via #1996.
