### ISSUE TITLE
--proxybastion=... option for compute config-ssh

### ISSUE THREAD

**Issue by schmichael** [GoogleCloudPlatform/gcloud-python#1969]
`config-ssh` is extremely useful for easily accessing hosts with public IPs.

If a project has an SSH bastion host, adding a `ProxyCommand` directive to hosts with only private IPs would allow automatically connecting to them through a user specified bastion host.

So a command like:

```sh
gclloud compute config-ssh --proxybastion=bastion1
```

Would create a `~/.ssh/config` file like:

```
Host privatehost.us-central1-a.project
    HostName 10.123.123.123
    ProxyCommand ssh %r@bastion1 -W %h:%p
    IdentityFile /home/xyz/.ssh/google_compute_engine
    UserKnownHostsFile=/home/xyz/.ssh/google_compute_known_hosts
    HostKeyAlias=compute.123
    IdentitiesOnly=yes
    CheckHostIP=no

Host publichost.us-central1-a.project
    HostName 123.123.123.123
    IdentityFile /home/xyz/.ssh/google_compute_engine
    UserKnownHostsFile=/home/xyz/.ssh/google_compute_known_hosts
    HostKeyAlias=compute.123
    IdentitiesOnly=yes
    CheckHostIP=no
```

**Comment by dhermes** [comment]
Thanks for reporting but this project is not for the `gcloud` CLI, rather it is a Python client for various Google cloud APIs

Maybe @jgeewax could redirect to someone on the CLI team?

**Comment by schmichael** [comment]
Well this is embarrassing. Sorry for the noise. Is the `gcloud` CLI not open source? I can't seem to find it.

**Comment by dhermes** [comment]
I'm not sure. @jgeewax?

**Comment by jonparrott** [comment]
There's a public issue tracker [here](https://code.google.com/p/google-cloud-sdk/issues/list).
