### ISSUE TITLE
[Documentation Issue] 

### ISSUE THREAD

**Issue by mchirico** [GoogleCloudPlatform/gcloud-python#1970]
Page Name: bigquery-usage
Release: 6d3592f

Currently the documentation states:

    with open('person_ages.csv', 'rb') as csv_file:
    ...     table.upload_from_file(csv_file, CSV,
    ...                            create_disposition='CREATE_IF_NEEDED')

Note that's incorrect.  Above CSV should be within quotes: 'CSV'.  There are a few similar issues on the page as well. 

Link to documentation:
https://googlecloudplatform.github.io/gcloud-python/latest/bigquery-usage.html

**Comment by daspecster** [comment]
Thanks for pointing that out!

Glancing through this I didn't see other instances of this kind of issue.

@mchirico, were there others that you noticed?
