### ISSUE TITLE
'gax-google-pubsub-v1' and 'gax-google-logging-v2' wreck the 'google.protobuf' namespace

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1972]
/cc @bjwatson, @tbetbetbe, @rok987

The failure only shows up when things are installed via `easy_install` (vs. `pip`).  The two packages each include and empty `google/protobuf/__init__.py`, without any namespace package declaration for it (or any purpose).  When installed in a particular order via `easy_install` / `setup.py develop`, the bogus `google.protobuf` package ends up higher on `sys.path` than the real `google.protobuf`, and mayhem ensues.

The fix would be to just drop them from the sdists altogether.

**Comment by bjwatson** [comment]
@geigerj What do you think? This seems easy to do as part of rolling new releases of these libraries for https://github.com/GoogleCloudPlatform/gcloud-python/issues/1979.

**Comment by geigerj** [comment]
Yes, I will do this when I release the new libraries. I will also fix https://github.com/googleapis/toolkit/issues/239 next, which will stop us from generating these bogus packages.

**Comment by tseaver** [comment]
@geigerj that would be great, thanks!

**Comment by geigerj** [comment]
I've put up new versions of those packages without the `google.protobuf` package.

**Comment by tseaver** [comment]
@geigerj Thank you!  I just verified that `bin/easy_install gcloud-python` in a fresh virtualenv pulls in `gax-google-pubsub-v1` 0.17.12 and `gax-google-logging-v2` 0.17.12, and that they do not break imports from `google.protobuf.*`.
