### ISSUE TITLE
Tracking namespace change

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-python#1978]
Here's a place we can track updates to the future changing of the `gcloud-python` namespace.

This change could break things in the future.

----

Sub-projects already partially created:

- [`google-cloud`](https://pypi.python.org/pypi/google-cloud)
- [`google-cloud-core`](https://pypi/.python.org/pypi/google-cloud-core)
- [`google-cloud-datastore`](https://pypi.python.org/pypi/google-cloud-datastore)
- [`google-cloud-storage`](https://pypi.python.org/pypi/google-cloud-storage)
- [`google-cloud-pubsub`](https://pypi.python.org/pypi/google-cloud-pubsub)
- [`google-cloud-bigquery`](https://pypi.python.org/pypi/google-cloud-bigquery)
- [`google-cloud-bigtable`](https://pypi.python.org/pypi/google-cloud-bigtable)
- [`google-cloud-happybase`](https://pypi.python.org/pypi/google-cloud-happybase)
- [`google-cloud-logging`](https://pypi.python.org/pypi/google-cloud-logging)
- [`google-cloud-vision`](https://pypi.python.org/pypi/google-cloud-vision)
- [`google-cloud-speech`](https://pypi.python.org/pypi/google-cloud-speech)
- [`google-cloud-language`](https://pypi.python.org/pypi/google-cloud-language) (and the alias [`google-cloud-natural-language`](https://pypi.python.org/pypi/google-cloud-natural-language))

**Comment by jonparrott** [comment]
Is this in reference to changing to `google.cloud`?

**Comment by daspecster** [comment]
@jonparrott yup! I wasn't sure if that was finalized or not.

**Comment by jonparrott** [comment]
@jgeewax can confirm, but from what I understand that is the way we want to go.

**Comment by daspecster** [comment]
We will want to update the User-Agent string as well for this right? Are there any other implications to that? i.e. people have that user-agent allowed in their apps/firewall.

**Comment by jgeewax** [comment]
Let's leave the useragent string alone -- we would have a whole heap of stuff to fix if we change that.... 

Otherwise -- yes, we're definitely going forward with google.cloud as the import path

**Comment by dhermes** [comment]
Using the [form][1] I created

- https://pypi.python.org/pypi/google-cloud
- https://pypi.python.org/pypi/google-cloud-datastore
- https://pypi.python.org/pypi/google-cloud-storage
- https://pypi.python.org/pypi/google-cloud-pubsub
- https://pypi.python.org/pypi/google-cloud-bigquery
- https://pypi.python.org/pypi/google-cloud-bigtable
- https://pypi.python.org/pypi/google-cloud-logging

with the `gcloudpypi` account on PyPI.

[1]: https://pypi.python.org/pypi?%3Aaction=submit_form

**Comment by dhermes** [comment]
@omaray I held off on grabbing the equivalents for `dns`, `error_reporting`, `monitoring`, `resource_manager` and `translate`, but I can do that as well if you like. I'm not sure if underscores are allowed in PyPI package names?

**Comment by jonparrott** [comment]
@dhermes you can use underscores but it's preferable to use `-` for consistency.

`google-cloud-error-reporting` reads better than `google-cloud-error_reporting`, even if the import path is `google.cloud.error_reporting`.

**Comment by dhermes** [comment]
Thanks @jonparrott.

@tseaver @jgeewax @omaray, shall we use `google-cloud-core` for the code shared by all modules?

**Comment by tseaver** [comment]
`google-cloud-core` SGTM.

**Comment by dhermes** [comment]
:+1: Just created https://pypi.python.org/pypi/google-cloud-core

**Comment by dhermes** [comment]
Just created https://pypi.python.org/pypi/google-cloud-happybase for #1762

**Comment by omaray** [comment]
Thanks @dhermes. All sgtm. Not sure if we added speech, vision, and language - but I guess might as well.

**Comment by dhermes** [comment]
@omaray Just created https://pypi.python.org/pypi/google-cloud-vision and https://pypi.python.org/pypi/google-cloud-speech

Should it be called `google-cloud-language` or `google-cloud-natural-language`?

**Comment by tseaver** [comment]
+1 for `google-cloudnatural-language`.

**Comment by omaray** [comment]
So Ruby and Node.js called it google-cloud-language:

Example: https://www.npmjs.com/package/@google-cloud/language

It's shorter indeed. 

If it's easy to do, let's hold both! I'll check with the team.

**Comment by dhermes** [comment]
> If it's easy to do, let's hold both! I'll check with the team.

It is easy but that would just be namespace squatting on PyPI; seems like it would be frowned upon. Though on the flipside, non-Google entities squatting on a name with `google` in it is also probably frowned upon.

----

I've noticed the Googlers keep calling it Language but that seems to be vague for people not already familiar with the API.

**Comment by jonparrott** [comment]
It's fine to have both `google-cloud-language` and `google-cloud-natural-language` as long as you publish a metapackage to one that depends on the other.

(fyi, if we do run into a case where there's someone squatting on our name we can get that resolved).

**Comment by dhermes** [comment]
So @jonparrott as packaging wizard your opinion is that I should grab both (a) and we should publish to both (b)?

**Comment by jonparrott** [comment]
Grab both and publish to one, and publish a metapackage to the other. But only if you feel like it's really necessary. I'd say don't. Just go with `google-cloud-natural-language`. Typically the metapackage magic is only done to deal with legacy stuff (like we'll eventually have to do with `oauth2client` and `google-auth`).

**Comment by dhermes** [comment]
Cool. Thanks (I love having a packaging authority person to consult with...as an authority). Grabbed https://pypi.python.org/pypi/google-cloud-language and https://pypi.python.org/pypi/google-cloud-natural-language

**Comment by dhermes** [comment]
@tseaver @omaray (and anyone else who likes to weigh in) are we a go to grab

- `google-cloud-dns`
- `google-cloud-error-reporting`
- `google-cloud-monitoring`
- `google-cloud-resource-manager`
- `google-cloud-translate`

i.e. some of these it's unclear if they deserve their own package / are priorities.

@rimey any preference for grabbing `google-cloud-monitoring` or `google-cloud-stackdriver-monitoring` or something else (or both, as we did with `language` / `natural-language` [above][1])

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1978#issuecomment-240885124

**Comment by tseaver** [comment]
I think those are fine.  AFAICT, the `-stackdriver` bit should be a replacement for `-cloud` if we are going to use it: (the branding seems confused to me).

**Comment by dhermes** [comment]
@rimey and @omaray can you weigh in as well?

**Comment by omaray** [comment]
Yeah, so the whole Stackdriver branding can indeed be confusing. I need to get back to you on that one. For the time being, everything will be `google-cloud-{api}`.

**Comment by omaray** [comment]
Yes, confirmed. We are sticking with google-cloud-{api}
