### ISSUE TITLE
iam service-accounts create does not return keys

### ISSUE THREAD

**Issue by kwoodson** [GoogleCloudPlatform/gcloud-python#1983]
I would like to automate the creation of service-accounts which would return us a json or p12 file so that I can use the credentials in scripts.

https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts.keys

If I am doing this incorrectly or this is already available through gcloud iam please let me know.

**Comment by kwoodson** [comment]
Sorry for the bother, found it.

https://cloud.google.com/iam/docs/managing-service-account-keys

gcloud iam service-accounts keys create \
    ~/key.json \
    --iam-account my-sa-123@my-project-123.iam.gserviceaccount.com

**Comment by dhermes** [comment]
@kwoodson Thanks for teaching me about `gcloud iam service-accounts keys create`. Pretty awesome that it exists!
