### ISSUE TITLE
Datastore put operations: what happens on error?

### ISSUE THREAD

**Issue by dakoner** [GoogleCloudPlatform/gcloud-python#1986]
The gcloud-python datastore documentation (https://googlecloudplatform.github.io/gcloud-python/stable/datastore-client.html) does not define what happens if an error occurs during a put() entity operation. We would like to get an exception, or an error.

**Comment by tseaver** [comment]
Thanks for the report!  Errors from the back-end get mapped onto one of the exceptions defined in `gcloud.exceptions`, based on the HTTP status code.  The back-end doesn't document what status codes `put` might return for errors, which means that, unfortunately, we cannot document them either.
