### ISSUE TITLE
Code branch test coverage

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-python#1993]
So since merging #1876, the hooks don't seem to be working. I'm not sure if it's us or codecov.io at this point.

Also since we ran into this being an issue [again](https://github.com/GoogleCloudPlatform/gcloud-python/pull/1992#issuecomment-233423389)...

I'm proposing that we just have travis-ci fail on `tox -e cover`.

**Comment by dhermes** [comment]
Seems wasteful, since we'll want the fancy badge to show we are cool and responsible.

**Comment by daspecster** [comment]
Could have travis-fail + coveralls. Then we would be cool and truly responsible ;)

**Comment by dhermes** [comment]
Yeah I know, I'm just being grumble grumble

**Comment by daspecster** [comment]
I feel ya, I wish codecov just worked.

**Comment by tseaver** [comment]
Via #2103.
