### ISSUE TITLE
pep8 is dead

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#2011]
As of version 1.7.0, [`pep8`][1] is no longer getting releases, the tool is now called [`pycodestyle`][2]. Visit https://github.com/PyCQA/pep8 to see the redirect.

This means we haven't had any updates since January 12, 2016. Oops.

[1]: https://pypi.python.org/pypi/pep8
[2]: https://pypi.python.org/pypi/pycodestyle/

**Comment by tseaver** [comment]
LGTM
