### ISSUE TITLE
ImportError: No module named http_client

### ISSUE THREAD

**Issue by liumingming** [GoogleCloudPlatform/gcloud-python#2014]
When I type `from gcloud import datastore`

them

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "gcloud/datastore/__init__.py", line 53, in <module>
    from gcloud.datastore.batch import Batch
  File "gcloud/datastore/batch.py", line 24, in <module>
    from gcloud.datastore import helpers
  File "gcloud/datastore/helpers.py", line 27, in <module>
    from gcloud._helpers import _datetime_to_pb_timestamp
  File "gcloud/_helpers.py", line 34, in <module>
    from six.moves.http_client import HTTPConnection
ImportError: No module named http_client
```

**Comment by daspecster** [comment]
How did you install `gcloud-python`?

You could try `pip install --upgrade six` since it looks like you may be using an older version of `six.

Let me know if that changes anything!

**Comment by dhermes** [comment]
If you are on Mac OS X you may not be able to upgrade `six`

**Comment by liumingming** [comment]
Yes, i am on Mac os X,but i have already upgrade six package，it still not working,it is great on linux

**Comment by dhermes** [comment]
Apple both locks down the system installed `six` package and puts that same package on your import path in front of where you've installed it. Run

```
$ python -c 'import six; print(six.__file__)'
```

to see where it is actually getting imported from and you'll see the problem
