### ISSUE TITLE
Documentation links in README.md do not work

### ISSUE THREAD

**Issue by awblocker** [GoogleCloudPlatform/gcloud-python#2022]
All links to https://googlecloudplatform.github.io/gcloud-python/ lead to 404 errors.

**Comment by daspecster** [comment]
Seems all the others are broken as well `gcloud-node`, `gcloud-php`, etc...

Did something with the DNS change?

**Comment by dhermes** [comment]
Thanks for the report @awblocker!

**Comment by daspecster** [comment]
They're back!
