### ISSUE TITLE
Docu broken

### ISSUE THREAD

**Issue by xamoom-raphael** [GoogleCloudPlatform/gcloud-python#2024]
If i try to click on "Source Code" link @ https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/datastore/client/client?method=gcloud.datastore.client.Client.put_multi
i get a 404.

404: Link: https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/.tox/json-docs/lib/python2.7/site-packages/gcloud/datastore/client.py#L331

**Comment by daspecster** [comment]
Thanks for the report @xamoom-raphael!

This seems to be related to #2022 and https://github.com/GoogleCloudPlatform/gcloud-common/issues/154.

However that last one looks like the link didn't generate correctly.
