### ISSUE TITLE
Implement natural language API

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#2027]
- https://cloud.google.com/natural-language/docs/
- https://developers.google.com/apis-explorer/#p/language/v1beta1/
- `/v1beta1/documents:analyzeEntities`
- `/v1beta1/documents:analyzeSentiment`
- `/v1beta1/documents:annotateText`
- Protobufs not released as of https://github.com/googleapis/googleapis/tree/6d6a1529e2c76db85b80c73760ed1791908f3cf2

**Comment by dhermes** [comment]
When constructing a [`Document`][1] for analysis, the content can either be raw bytes from the request or a reference to an object in a Cloud Storage bucket (`gcsContentUri`).

@tseaver What approach have we taken in similar situations where one service "reaches into" another? I could construct a method which accepts a reference to a `gcloud.storage.blob.Blob` or just accept bucket and object names as strings and construct the `gs://{bucket}/{obj}` string for the user. WDYT?

[1]: https://cloud.google.com/natural-language/reference/rest/v1beta1/Document

**Comment by tseaver** [comment]
The [BigQuery `LoadTableFromStorageJob`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/565c992958a6d498385c16f34b37feda8af83bad/gcloud/bigquery/job.py#L387) is probably the closest equivalent.  The other one which is somewhat reltated is the [Logging sink to Storage bucket](https://github.com/GoogleCloudPlatform/gcloud-python/blob/565c992958a6d498385c16f34b37feda8af83bad/gcloud/logging/sink.py#L20), but there we just pass the user-supplied URI through to the back-end.

**Comment by dhermes** [comment]
See #2062

**Comment by dhermes** [comment]
Closed via #2211
