### ISSUE TITLE
Source code links from doc pages are broken.

### ISSUE THREAD

**Issue by sharbison3** [GoogleCloudPlatform/gcloud-python#2046]
Starting in, for example:
https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/logging/metric/metric 
or
https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/client/client

All the links labeled "Source code"  seem to be broken. ("Not the page you're looking for")

Here's one of the bad links:
https://github.com/GoogleCloudPlatform/gcloud-python/blob/master//home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/json-docs/lib/python2.7/site-packages/gcloud/client.py/gcloud/client.py#L120

**Comment by dhermes** [comment]
Thanks for reporting @sharbison3 

@daspecster Can you point us in the right direction?

**Comment by daspecster** [comment]
Yeah, I think I know what's wrong. I have to strip out everything except the lib path and I try splitting it on `gcloud`  but that's been flakey between environments(local vs travis).

**Comment by daspecster** [comment]
Should be fixed from #2052. Thanks for reporting @sharbison3!
