### ISSUE TITLE
The landing page has rendering issues. 

### ISSUE THREAD

**Issue by arouzrokh** [GoogleCloudPlatform/gcloud-python#2049]
![image](https://cloud.githubusercontent.com/assets/11892468/17375017/41a43152-597d-11e6-9716-eefe4d1133f8.png)

**Comment by dhermes** [comment]
Thanks for filing @arouzrokh!

@daspecster @jgeewax Who is the CSS guru for `gcloud-common`?

**Comment by daspecster** [comment]
I'll make an issue on `gcloud-common` for this.  I tried it locally and dropping the `hero` font-size from 5.6em to 4.6em works for us but other languages might want it bigger.

**Comment by Linicks** [comment]
I was just getting ready to create this issue :)
