### ISSUE TITLE
BigQuery: How do I specify to use Standard SQL instead of Legacy SQL

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/gcloud-python#2053]
https://googlecloudplatform.github.io/gcloud-python/stable/bigquery-client.html#gcloud.bigquery.client.Client.run_sync_query

I want to be able to set `useLegacySql` to false here: https://cloud.google.com/bigquery/docs/reference/v2/jobs/query#request-body

**Comment by dhermes** [comment]
@tswast I assume #1992 covers you? Release `0.18.0` just cut today.

**Comment by tswast** [comment]
Nice. Thanks!

**Comment by ravindranathakila** [comment]
```query.use_legacy_sql = False```
