### ISSUE TITLE
Source code links are broken in the documentation

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/gcloud-python#2061]
I noticed this issue on this page.
https://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/bigquery/client/client

For example, the source code link for the `__init__` method links to https://github.com/GoogleCloudPlatform/gcloud-python/blob/master//home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/json-docs/lib/python2.7/site-packages/gcloud/client.py/gcloud/client.py#L184 which 404s.

**Comment by daspecster** [comment]
There is a PR to fix this that hasn't been merged yet. I'm out of the country at the moment with spotty wifi. I can look at it tonight possibly though.

**Comment by tswast** [comment]
Closing this as a duplicate of https://github.com/GoogleCloudPlatform/gcloud-python/issues/2046.
