### ISSUE TITLE
What setup is required to get Monitoring system tests running?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#2064]
The usage docs should document the setup process more clearly:  it is not as simple as enabling the API at https://console.developers.google.com/apis/api/cloudmonitoring/overview.

/cc @waprin

**Comment by waprin** [comment]
Will review/fix this.

**Comment by rimey** [comment]
That's the wrong API. You want the Google Monitoring API.

Ken

**Comment by tseaver** [comment]
Are there words for the kind of failure that is?
