### ISSUE TITLE
Pip Install Error

### ISSUE THREAD

**Issue by patrick-ogrady** [GoogleCloudPlatform/gcloud-python#2066]
Collecting gcloud
  Downloading gcloud-0.18.0.tar.gz (435kB)
Collecting httplib2>=0.9.1 (from gcloud)
  Downloading httplib2-0.9.2.zip (210kB)
Collecting googleapis-common-protos (from gcloud)
  Downloading googleapis-common-protos-1.2.0.tar.gz
Collecting oauth2client>=2.0.1 (from gcloud)
  Downloading oauth2client-3.0.0.tar.gz (77kB)
Collecting protobuf!=3.0.0.b2.post1,>=3.0.0b2 (from gcloud)
  Downloading protobuf-3.0.0-py2.py3-none-any.whl (342kB)
Requirement already up-to-date: six in /usr/lib/python2.7/dist-packages (from gcloud)
Collecting grpcio>=1.0rc1 (from gcloud)
  Downloading grpcio-1.0.0rc1-cp27-cp27mu-manylinux1_x86_64.whl (4.7MB)
Collecting google-gax<0.13dev,>=0.12.3 (from gcloud)
  Downloading google-gax-0.12.5.tar.gz
Collecting gax-google-pubsub-v1<0.8dev,>=0.7.12 (from gcloud)
  Downloading gax-google-pubsub-v1-0.7.12.tar.gz
Collecting grpc-google-pubsub-v1<0.8dev,>=0.7.12 (from gcloud)
  Downloading grpc-google-pubsub-v1-0.7.12.tar.gz
Collecting gax-google-logging-v2<0.8dev,>=0.7.12 (from gcloud)
  Could not find a version that satisfies the requirement gax-google-logging-v2<0.8dev,>=0.7.12 (from gcloud) (from versions: 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.8.0)
No matching distribution found for gax-google-logging-v2<0.8dev,>=0.7.12 (from gcloud)
The command '/bin/sh -c /usr/local/bin/pip install --upgrade gcloud' returned a non-zero code: 1

**Comment by tseaver** [comment]
/cc @bjwatson, @geigerj are you guys removing historical releases?  That is a really poor practice:  it breaks your users.  Please don't remove them unless there is a *really* good reason, i.e. *force majeur* such as a DMCA takedown, or something similar.  PyPI won't let you re-upload them, which means that nobody can use gcloud 0.18.0 (just released last week) ever again.

#2065 should fix the issue on `master`.  I will look into making a branch from our `0.18.0` tag, and releasing a `0.18.1` which relaxes that maximum version.

**Comment by tseaver** [comment]
Note that our pin `< 0.8dev`, was actually *correct*:  the 0.8.0 `gax-google-<foo>` releases are *not* backward-compatible:  they move the generated API wrappers from `google.<foo>` to `google.cloud.<foo>`.

**Comment by geigerj** [comment]
Really sorry for the breakage. I'm pretty sure I accidentally took down logging `0.7.12` earlier today. We certainly don't intend to remove historical releases.

**Comment by tseaver** [comment]
@patrick-ogrady Can you please try again with the 0.18.1 release I just made?

- https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/0.18.1
- https://pypi.python.org/pypi/gcloud/0.18.1

**Comment by dhermes** [comment]
@patrick-ogrady I'm closing out as fixed. If the issue still persists, please let us know.

**Comment by sdcooke** [comment]
Just to confirm - I was having the same issue and 0.18.1 fixed it. Thanks!
