### ISSUE TITLE
system_test_utils:  Distinguish between missing and invalid GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#2084]
See: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1944#issuecomment-238979486

/cc @geigerj

**Comment by dhermes** [comment]
Is this our "error message" problem or one in `oauth2client`?

**Comment by tseaver** [comment]
It is [our error handling](https://github.com/GoogleCloudPlatform/gcloud-python/blob/27f0af52c371373440ae35f983b9e2a7e6db8e8f/system_tests/system_test_utils.py#L54).

**Comment by dhermes** [comment]
@tseaver I can handle this, on it now
