### ISSUE TITLE
Monitoring system tests:  Collision on group.create

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#2093]
From:  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/151551907#L1081-L1091

```python
======================================================================
ERROR: test_list_group_members (monitoring.TestMonitoringGroups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/monitoring.py", line 263, in test_list_group_members
    group.create()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/monitoring/group.py", line 178, in create
    method='POST', path=path, data=self._to_dict())
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.ServiceUnavailable: 503 Write collision, please retry. (POST https://monitoring.googleapis.com/v3/projects/precise-truck-742/groups/)
```

**Comment by dhermes** [comment]
@rimey Can you weigh in here?

**Comment by tseaver** [comment]
Smells like we just need to add a `RetryErrors(ServiceUnavailable)` here.

**Comment by tseaver** [comment]
I think #2095 addresses this error.

**Comment by rimey** [comment]
@dhermes I'm having trouble assigning this issue to @supriyagarg. Does she need to be a member of GoogleCloudPlatform?

**Comment by rimey** [comment]
I think she needs to be a member of the GoogleCloudPlatform "Contributors" team.

**Comment by rimey** [comment]
See my comment on #2092. This error is slightly surprising. Let's find out more about in exactly what circumstances it occurs, and whether it is deterministic.

**Comment by dhermes** [comment]
Closed by #2095

**Comment by dhermes** [comment]
@tseaver How hard is it to reproduce these errors? I tried on my local machine and trying on Compute Engine right now and haven't been able to repro. I am doing this because I want to see if there is an equivalent to `error['reason'] == 'rateLimitExceeded'` in the caught error

**Comment by tseaver** [comment]
@dhermes I saw them multiple times the day I was trying to squash all the flaky issues:  if I had to guess, I would say that the issue would be related to load on the back-end.

**Comment by dhermes** [comment]
I don't know why I never tried before, but just running `nosetests system_tests/monitoring.py --pdb -vv` in two separate bash shells at the same time forced a 503 on the first try.

FWIW @tseaver the 503 occurred in a 404-wrapped delete during `tearDown` of `TestMonitoringGroups.test_group_hierarchy`.

From the debugger:

```Python
(Pdb) print(json.dumps(response, indent=2))
{
  "status": "503",
  "alternate-protocol": "443:quic",
  "content-length": "247",
  "x-xss-protection": "1; mode=block",
  "x-content-type-options": "nosniff",
  "transfer-encoding": "chunked",
  "vary": "Origin, X-Origin, Referer",
  "server": "ESF",
  "-content-encoding": "gzip",
  "cache-control": "private",
  "date": "Mon, 22 Aug 2016 14:38:43 GMT",
  "x-frame-options": "SAMEORIGIN",
  "alt-svc": "quic=\":443\"; ma=2592000; v=\"35,34,33,32,31,30\"",
  "content-type": "application/json; charset=UTF-8"
}
(Pdb) print(content)
{
  "error": {
    "code": 503,
    "message": "Write collision, please retry.",
    "status": "UNAVAILABLE",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.RetryInfo",
        "retryDelay": "1.000s"
      }
    ]
  }
}
```

Also note that

```python
(Pdb) exc = make_exception(response, content, error_info=method + ' ' + url)
(Pdb) exc.errors
[]
(Pdb) exc._errors
()
```

because the error payload [doesn't have the key][1] `msg['error']['errors']`.

What we really want is a check like `payload['error']['status'] == u'UNAVAILABLE'` just like [in `system_tests.bigquery._rate_limit_exceeded`][2].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2c134264b63c5f8d10c41c0e9ec29f43f10297ed/gcloud/exceptions.py#L201
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2c134264b63c5f8d10c41c0e9ec29f43f10297ed/system_tests/bigquery.py#L33-L36
