### ISSUE TITLE
Merging logging-stdlib-handling-feature into master

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/gcloud-python#2102]
@tseaver @dhermes @jgeewax tell me what needs to be done.

The feature branch approach is not really working either.

**Comment by waprin** [comment]
@dhermes  said he can set up time on GVC with me to sort some of this stuff out on Wednesday so we'll hold off for that convo.

**Comment by dhermes** [comment]
@daspecster I don't think this is what you meant to close with #2052.

**Comment by daspecster** [comment]
No, it is not. It was #2104.

**Comment by dhermes** [comment]
@waprin Do I have your go-ahead to delete the branch?

**Comment by dhermes** [comment]
https://github.com/GoogleCloudPlatform/gcloud-python/tree/logging-stdlib-handler-feature

**Comment by waprin** [comment]
Yes sounds good. Thanks again for all the help here. Let me know if you have ideas on best way to address concerns you raised.

**Comment by dhermes** [comment]
Will do
