### ISSUE TITLE
There are broken links for source code

### ISSUE THREAD

**Issue by edgartanaka** [GoogleCloudPlatform/gcloud-python#2104]
Broken links here http://googlecloudplatform.github.io/gcloud-python/#/docs/master/gcloud/storage/client/client 
when clicking to see source code

**Comment by daspecster** [comment]
Thanks for reporting!
This is a duplicate of #2046, and will be fixed by #2052.

**Comment by daspecster** [comment]
Actually I'll leave this open and have the PR close it when it's merged. My bad!

**Comment by daspecster** [comment]
Should be fixed with the next docs generation per #2052.
