### ISSUE TITLE
SDK unable to resolve DNS address www.facebook.com

### ISSUE THREAD

**Issue by Paradoxis** [GoogleCloudPlatform/gcloud-python#2120]
I'm currently using the ~~cgloud~~ cloud python SDK, when trying to resolve certain hostnames the following error is thrown:

    RuntimeError: error('illegal IP address string passed to inet_pton',)

Examples:

    # Fetching `www.google.com`
    socket.gethostbyname_ex("www.google.com")    

    # Returns:
    [
        "www.google.com",
        [], 
        [
            "173.194.65.106",
            "173.194.65.104",
            "173.194.65.105",
            "173.194.65.103",
            "173.194.65.99",  
            "173.194.65.147"
        ]
    ]

    # Fetching `www.twitter.com`
    socket.gethostbyname_ex("www.twitter.com") 

    # Returns:
    [
        "twitter.com",
        [
            "www.twitter.com"
        ],
        [
            "199.16.156.230",
            "199.16.156.198",
            "199.16.156.102",
            "199.16.156.70"
        ]
    ]

    # Fetching `www.facebook.com`
    socket.gethostbyname_ex("www.facebook.com")

    # Raises:
    RuntimeError: error('illegal IP address string passed to inet_pton',)

**Comment by tseaver** [comment]
Thanks for the report.  It doesn't appear that your issue has anything to to with the `gcloud-python` library (which is what is produced from this repository).  The `socket.gethostbyname_ex` function is part of the Python standard library.  Its [docs](https://docs.python.org/2/library/socket.html#socket.gethostbyname_ex) say:

> gethostbyname_ex() does not support IPv6 name resolution, and getaddrinfo() should be used instead for IPv4/v6 dual stack support.

Maybe the failing hostnames are both IPv6/IPv4?

**Comment by Paradoxis** [comment]
@tseaver Hi, thanks for the help, but after digging deep into the SDK code it seems the dev appserver uses a wrapper around the real socket object, which fails to execute the lookup somewhere.

**Comment by dhermes** [comment]
@Paradoxis The SDK is not part of this project. Maybe @jonparrott can point you to the right issue tracker?

**Comment by jonparrott** [comment]
@Paradoxis the public issue tracker is [here](https://code.google.com/p/googleappengine/issues/list).
The socket module is heavily modified in GAE, so I'm not totally surprised by this.
