### ISSUE TITLE
Using Google Cloud Datastore API in Python Code

### ISSUE THREAD

**Issue by naveensinghal** [GoogleCloudPlatform/gcloud-python#2152]
Hi @dhermes ,

I am trying to Implement Google Cloud DataStore in my Python Django Project not running on Google App Engine.

Can it be possible to use Google Datastore without having the project run on Google App Engine ? 

If yes, Can you please tell how to retrieve the complete entity object or execute the query successfully, if possible ?

The below code snippet prints the query object but throws an error after that. 
( I have a valid project. It prints the correct project if i try to print the value of key)

Code Snippet: 
```
from gcloud import datastore
entity_kind = "EntityKind"
numeric_id = 1234xxx89

client = datastore.Client()
key = client.key(entity_kind, numeric_id)
query = client.query(kind=entity_kind)
print(query)
results = list(query.fetch())
print(results)
```

Error: 
`NotFound: 404 The project gxxxp does not exist or it does not contain an active App Engine application. Please visit http://console.developers.google.com to create a project or https://console.developers.google.com/appengine?project=gxxxp to add an App Engine application. Note that the app must not be disabled.`

Thanks

**Comment by dhermes** [comment]
Did you follow the recommendation in the error?

**Comment by naveensinghal** [comment]
Thanks @dhermes for your reply. 
I have a valid Google Project. But No Active App running on Google App Engine. I wish to use Google Datastore API without using the Google App Engine. Is it possible ?

**Comment by dhermes** [comment]
I don't think so. You should file an issue on https://github.com/GoogleCloudPlatform/google-cloud-datastore to double check (and also people in the future can find out there).
