### ISSUE TITLE
Pub/Sub system tests failing

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#2163]
`test_list_subscriptions` consistently terminates with `UNAVAILABLE` and `test_fetch_delete_subscription_w_deleted_topic` consistently fails `self.assertTrue(orphaned.topic is None)`

https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154261312
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154256059
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154251510

This may be related to #2140. The 3 builds above were the first time this error appeared

**Comment by dhermes** [comment]
Since, 1 build has succeeded

https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154329853

and 1 has failed the same way

https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154329912

**Comment by dhermes** [comment]
Again https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154552669

**Comment by dhermes** [comment]
@tmatsuo Any idea why Travis would consistently get an UNAVAILABLE but locally the tests run just fine?

**Comment by dhermes** [comment]
Again https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154661458

**Comment by dhermes** [comment]
Again https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154875146

**Comment by dhermes** [comment]
Again: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154939849

@tmatsuo PTAL

**Comment by tseaver** [comment]
I'm going to put on my Pollyanna/Candide hat and claim that #2195 has resolved this issue.
