### ISSUE TITLE
'google-cloud-sdk' was not found

### ISSUE THREAD

**Issue by gergelyke** [GoogleCloudPlatform/gcloud-python#2196]
Hey,

suddenly all our google-cloud-sdk installations fail - both using the update command and from `apt-get`

* Version '120.0.0' for 'google-cloud-sdk' was not found
* The component listing for Cloud SDK version [119.0.0] could not be found

`gcloud components update --version 120.0.0 kubectl`

**Comment by dhermes** [comment]
@gergelyke the public issue tracker for the `gcloud` CLI is [here][1]. This repo is for the Python Google Cloud client library.

[1]: https://code.google.com/p/googleappengine/issues/list
