### ISSUE TITLE
Contributing guidelines broken

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-python#2198]
```
virtualenv ~/envs/gcloudpython
source ~/envs/gcloudpython/bin/activate
python setup.py develop
```
Results in `error: Could not find suitable distribution for Requirement.parse('gax-google-logging-v2<0.8dev,>=0.7.12')`

Then `tox -e docs`

Fails with 
```
ERROR: could not install deps [nose, nose-exclude, unittest2, grpcio >= 1.0rc1, google-gax >= 0.12.3, < 0.13dev, gax-google-pubsub-v1 >= 0.7.12, < 0.8dev, grpc-google-pubsub-v1 >= 0.7.12, < 0.8dev, gax-google-logging-v2 >= 0.7.12, < 0.8dev, grpc-google-logging-v2 >= 0.7.12, < 0.8dev, nose, nose-exclude, unittest2, grpcio >= 1.0rc1, google-gax >= 0.12.3, < 0.13dev, gax-google-pubsub-v1 >= 0.7.12, < 0.8dev, grpc-google-pubsub-v1 >= 0.7.12, < 0.8dev, gax-google-logging-v2 >= 0.7.12, < 0.8dev, grpc-google-logging-v2 >= 0.7.12, < 0.8dev, Sphinx, sphinx_rtd_theme]
```

**Comment by dhermes** [comment]
@elibixby I think we have moved past 0.7 to 0.8 (on phone, forgive me I can't check)

Are you sure you are running that command from `HEAD`?

Your IAM PR is certainly behind and won't build for similar reasons (broken versions of GAX deps).

**Comment by daspecster** [comment]
@elibixby I'm able to run `python setup.py develop` locally in my virtualenvs.

Can you run `python setup.py --version` should print your checked out version.

**Comment by dhermes** [comment]
I am on a laptop now. [Confirmed][1] you have an old checkout (e.g. `gax-google-pubsub-v1 >= 0.7.12, < 0.8dev` is old).

@elibixby Please re-open if the issue still persists at `HEAD`

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/fd0e6bf7aac1f4373c64d8e76552d395a1dbf279/setup.py#L24-L28
