### ISSUE TITLE
Bigtable instance undelete doesn't exist

### ISSUE THREAD

**Issue by destijl** [GoogleCloudPlatform/gcloud-python#2209]
The documentation and some code comments think there should be an undelete for bigtable instances:

https://github.com/GoogleCloudPlatform/gcloud-python/blob/e63b1d8bd24a826c28865a21766ee7537ce87285/gcloud/bigtable/instance.py#L283

https://googlecloudplatform.github.io/gcloud-python/stable/bigtable-instance.html

but AFAICT looking at code it appears to be unimplemented.

**Comment by tseaver** [comment]
Thanks for the report!  `UndeleteCluster` endpoint went away in [V2 of the API](https://cloud.google.com/bigtable/docs/reference/admin/rpc/google.bigtable.admin.v2#google.bigtable.admin.v2.BigtableInstanceAdmin).  The `Instance` concept is new in V2, and never had an `UndeleteInstance` endpoint.

The artifacts you are seeing are fossils (in the `Cluster` docstrings) and copy-past of fossils (in the `Instance` docstrings).

**Comment by destijl** [comment]
OK. I was testing code that stands up a new instance, I ended up just using a random instance id instead of trying to resurrect the same one.
