### ISSUE TITLE
URL forwarding for root domain.

### ISSUE THREAD

**Issue by ojengwa** [GoogleCloudPlatform/gcloud-python#2228]
Recently,  I convinced our team to port our DNS to Google Cloud DNS.
Unfortunately, the cloud DNS service does not support aliasing/CNAME for the root domain. 

I understand that this is a DNS specs `standard`.

Please, any work around on redirecting a root domain to a sub/another domain?

**Comment by daspecster** [comment]
Thanks for asking @ojengwa!

If I understand correctly, this is actually not supported by the DNS specifications.

Here's some conversation I found on the issue.
http://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain.

@tseaver may have some more insight if this is possible or not.

**Comment by ojengwa** [comment]
Yes, it's not :(

Most DNS services provide a workaround (Google domains actually allows you to set up URL forwarding on the root domain for example...).

Currently losing major traffic (new product launch) because the root domain cannot be reached...

**Comment by jonparrott** [comment]
@ojengwa your best bet would be to put a simple webserver at the root domain to handle 301ing to a subdomain. This is pretty easy to do with [nginx](http://stackoverflow.com/questions/6045020/how-to-redirect-to-a-different-domain-using-nginx).

**Comment by ojengwa** [comment]
Hi @jonparrott, we are currently deployed on Heroku... :(

**Comment by daspecster** [comment]
@ojengwa, you may need to spin up another heroku instance/gear/? to do the redirect.
Also, Heroku has some DNS settings that may [help](https://devcenter.heroku.com/articles/custom-domains#subdomain-examples).

**Comment by jonparrott** [comment]
You could still do that with heroku, I believe.

**Comment by daspecster** [comment]
I'm going to close this for now. I don't know there's a move we can make here AFAIK. If there is, feel free to reopen.
