### ISSUE TITLE
gcloud crashed (ValueError): No JSON object could be decoded

### ISSUE THREAD

**Issue by JuanCarlosM** [GoogleCloudPlatform/gcloud-python#2232]
When $HOME/.dockercfg exists but is empty, gcloud command could not decode content and crashes

How to reproduce:
$ echo  > $HOME/.dockercfg
$ gcloud docker ps
ERROR: gcloud crashed (ValueError): No JSON object could be decoded

**Comment by daspecster** [comment]
@JuanCarlosM for reporting!
This repository is specifically for the python library to interact with Google Cloud Platform services and doesn't have anything to do with the `$ gcloud` command line tool.

I _believe_ that is over at https://code.google.com/p/google-cloud-sdk/issues/list.

**Comment by JuanCarlosM** [comment]
opps..., ok forwarded! thanks!

**Comment by daspecster** [comment]
Awsome! Thank you!
