### ISSUE TITLE
storage.Key.get_contents_to_filename:  sync mtime with 'updated' time from metadata

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#311]
Split from #148.

See the [v1 API resource representation for Object](https://cloud.google.com/storage/docs/json_api/v1/objects), which defines the `updated` field as an [RFC 3339](https://tools.ietf.org/html/rfc3339) timestamp string (`YYYY-MM-DDThh:mm:ssZ` or `YYYY-MM-DDThh:mm:ss+hh:mm`).

**Comment by dhermes** [comment]
@tseaver and @grapefruit623 Please re-open if this is not fully fixed.
