### ISSUE TITLE
Entity should not require a Key

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#471]
Relates to
https://docs.google.com/document/d/1xKw8Tz6lfN5uOcv0my4uUgFSeDoRzwCLho2UGlBpqDU/edit

From the [spec][1]:

> An entity must have a key, unless otherwise documented (for example, an entity in
> &lt;code&gt;Value.entityValue&lt;/code&gt; may have no key). An entity's kind is its key's path's 
> last element's kind, or null if it has no key.

Though not required, we should be opinionated (in the constructor) about when it's not necessary if possible.

[1]: https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/21e029b2657ebb15fef5429c90c4315326855fd1/proto/datastore_v1.proto

**Comment by Alfus** [comment]
In an entity value, the key can be present, partial or missing. This lets the value handle dicts (no key) and entities (with partial or complete keys).

**Comment by dhermes** [comment]
This is not an issue any longer, the `Key` is not required and failure occurs naturally in methods than need a `Key`.
