### ISSUE TITLE
Version the docs

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/gcloud-python#472]
The docs at http://googlecloudplatform.github.io/gcloud-python/datastore-api.html document the current API at git head - and include a version tag of 0.3.0

This matches the current released version on pypi (that does not have the recent change for implicit credentials)

Please consider using something like readthedocs and provide versioned docs - so that what users find actually matches what they are likely to install :)

Or at least mark the version in master as -dev with a warning in docs, and tag to stable version in a branch.

**Comment by yjkogan** [comment]
+1 for this. I'm starting reading source code at the specific commit / tag in order to know what's supported in that version.

**Comment by rstuart85** [comment]
+1 for this. The coding example under Getting Started for Storage doesn't work because the signature for get_buckets() has changed. This is really confusing because the docs say ``0.3.0`` which matches the version on PyPi as already pointed out. The only way to figure it out is the read the source code which probably isn't ideal.

**Comment by dhermes** [comment]
Something like http://googlecloudplatform.github.io/gcloud-node/#/docs/history is preferred so hopefully we can borrow from `gcloud-node`

@silvolu you mentioned you had started this, do you have any half-finished work to go from?

**Comment by silvolu** [comment]
@dhermes I mentioned I would start this, but then I got side tracked, so nope, I got nothing :/

**Comment by dhermes** [comment]
@rstuart85 in the short term https://github.com/GoogleCloudPlatform/gcloud-python/releases/tag/v0.4.0 means the docs reflect the latest version on PyPI. I'm hoping to resolve this issue soon-ish.

**Comment by dhermes** [comment]
Starting on this right now.

**Comment by rstuart85** [comment]
@dhermes great news!

**Comment by dhermes** [comment]
Release pushed but new docs didn't build:
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/50716542

"Not in master on a non-pull request. Doing nothing."

Me thinks `"${TRAVIS_BRANCH}" == "master"` fails when pushing a tag. I'll have to play around and address this.
