### ISSUE TITLE
Add GAE/GCE support for datastore.set_default_dataset and add exception on failure

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#475]
See discussion in #444 for comments on exception.

Something like [`oauth2client.client._get_environment`][1] could be good to detect GAE/GCE dataset ID's but `_detect_gce_environment` should be better as discussed in google/oauth2client#93

Not blocking for M1.

[1]: https://github.com/google/oauth2client/blob/481b4b6310e5872fbd5ed6c7aa336938e564d729/oauth2client/client.py#L953

**Comment by dhermes** [comment]
Relevant to GAE:
```python
>>> import os
>>> from google.appengine.api import app_identity
>>>
>>> print repr(os.getenv('APPLICATION_ID'))
's~foo'
>>> print repr(app_identity.get_application_id())
'foo'
```

**Comment by dhermes** [comment]
Relevant to GCE:
```python
>>> import urllib2
>>> BASE = 'http://metadata.google.internal/'
>>> PROJECT_PATH = 'computeMetadata/v1/project/project-id'
>>> URI = BASE + PROJECT_PATH
>>> request = urllib2.Request(URI, headers={'Metadata-Flavor': 'Google'})
>>> response = urllib2.urlopen(request)
>>> contents = response.read()
>>> response.close()
>>> contents
'foo'
```

No prefix there.

**Comment by dhermes** [comment]
@tseaver I just realized that #572 does not raise when setting fails.

We can add this in a sweeping way for both packages after #572 goes through?

**Comment by dhermes** [comment]
Re-opening until exception questions resolved.

**Comment by jgeewax** [comment]
This isn't possible with the current dataset_id situation requiring s~ or e~ prefixes in the key protobuf. Moving to Datastore Future since we don't know for sure when this will be fixed.
