### ISSUE TITLE
DISCUSSION: Remove Entity.reload()

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#490]
@jgeewax We never use [`Entity.reload()`][1] within the library and it doesn't seem to be particularly useful and can even be replaced in a one liner:
```python
entity.update(entity.key.get())
```

What did you have in mind when you implemented it?

----

To give some more context, we have been discussing / making a case for removing `Entity` and just using a `dict` (as in `gcloud-node`) since most of the logic lives elsewhere. `Entity.save()` can be moved to `gcloud.datastore.__init__` and so `reload()` is the only remaining blocker.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/ced11fbb7e3ba353b25d57b8ba0652954b7bc6a5/gcloud/datastore/entity.py#L203

**Comment by jgeewax** [comment]
AFAI remember, `reload` was intended as a shortcut for the code you mentioned. I wanted a quick way to say "I recognize that this data probably changed from when I first grabbed the object."

I'd be on board for getting rid of the concept of an Entity -- however that "entity.save()" thing is pretty important. What's the plan for that? (Feel free to move this conversation elsewhere if you think this isn't the right place.)

**Comment by dhermes** [comment]
Yes we'll be sure to make sure `entity.save()` is an easily accesible concept if we are to remove `Entity`.

I'll cc you on any PRs / discussions we have before `Entity` is removed. Just wanted to make I wasn't missing anything with `Entity.reload()`.

Thanks

**Comment by dhermes** [comment]
Was removed in #517.
