### ISSUE TITLE
DISCUSSION: Re-add dataset as wrapper for read/write options

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-python#523]
Right now read and write methods are split between `Key` and `Entity`, requiring that the user explicitly specify things like `namespace`, `connection`, and once supported things like `eventual` and `force`, each time a rpc call is made. Instead, I would propose we use dataset as the main point of interaction between the user and the datastore (has mutation and fetch methods), and encapsulate all of the properties that users may not want to re-specify (connection, namespace, read/write options). I think this has a few advantages:

* Stylistically, things like namespace and connection should be only be specified once per object. While there is nothing wrong with the way it's set up now, I think that an entirely new object each time a new namespace or connection is specified will be more robust in the future.
* Makes it much easier for us to drop `Key` and/or `Entity` in the future as objects if we find a user-friendly way to do that
* `Transaction` `Batch` and `Dataset` can all share a common interface. I think this is a potentially huge improvement to usability. 

I'd love to hear thoughts on this.

**Comment by dhermes** [comment]
Please let us finish the API changes before forming too many opinions about what the final thing should look like.

I do think we can enable more settings as we currently do in `_implicit_environ.py` and we will certainly look to address that.

However, the core focus now is getting right what **every** user must do
- Auth
- Specify a dataset
- Interact with the dataset

All the rest are "upgrades" and we want to make the upgrade path smooth and easy as well. But we can't do that until we have the ground floor built.

----

I am familiar with how `gcloud-node` thinks of a `Dataset` and think it's a fine abstraction. All in due time.

**Comment by elibixby** [comment]
Sounds good. If you would let me know when you hit the next milestone and want me to try writing sample apps with the API again I would really appreciate it. Other than that I'll just lurk =)

**Comment by dhermes** [comment]
@elibixby Check it out, API changes are "stable".

I'm going to close this (to push it off my mental queue), feel free to re-open or open a new one if you have more specific / pointed feedback.
