### ISSUE TITLE
Add requires.io badge

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#530]
I activated as a test:
https://requires.io/github/GoogleCloudPlatform/gcloud-python/requirements/?branch=master

It pointed out we still have [`protobuf==2.6.0`][1] for Py26, which is out-of-date. @tseaver is this still necessary?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/0525530ad7a76e408ca2e842b883d49c353ed56d/tox.ini#L11

**Comment by dhermes** [comment]
This is the badge:
https://requires.io/github/GoogleCloudPlatform/gcloud-python/requirements.svg?branch=master

**Comment by tseaver** [comment]
That pin is there from 9c8f4321c21e4223a45759bcb38d568ea93c48ac, whose commit message (from 2014-10-22) says:

>  Work around protobuf 2.6.1 install failure on Python 2.6.x.

There is a [3.0.0-alpha1](https://pypi.python.org/pypi/protobuf/3.0.0-alpha-1) release of protobuf, which is not a good fit for us, I think (adds risky new `proto3`, does not explicitly call out real Py3k support, etc.)

**Comment by dhermes** [comment]
WDYT about adding the badge? At what point are badges too noisy?

----

RE: "2.6.0 vs. 2.6.1" I see, for some reason I thought the `protobuf` folks updated after releasing a broken version. I'm unclear why `proto3` is "risky" but that isn't part of this issue, so not really worth hashing out.

**Comment by tseaver** [comment]
I just meant "risky" in the sense of "new API with unknown compatibility issues".

Ideally, we would adopt the 3.0.0 final release as our supported dependency, perhaps with notes on how to use 2.6.x (e.g., no 2.6.1 on Python 2.6), especially if they get the Python3 story sorted.

**Comment by tseaver** [comment]
Re:  badge noise:  I'm ambivalent.  I think we are tracking our dependencies pretty thoroughly ATM, and our current pin is certainly justified (if we could find a more elegant way to spell the "avoid protobuf 2.6.1 on Python 2.6" rule, that would be OK with me).
