### ISSUE TITLE
DISCUSSION: Implement Key.__eq__ and Entity.__eq__

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#533]
Currently comparison must be done in an ad-hoc way:

```python
assert dict(arya_entity.items()) == {'name': 'Arya', 'family': 'Stark'})
```

FWIW `__eq__` is not something that should really be needed outside of the `Key`, and even then not so much.

**NOTE**: This was a small part of #336

**Comment by dhermes** [comment]
FWIW I have implemented `Key.__eq__` in https://github.com/dhermes/gcloud-python/tree/key-comparison but it greatly depends on the conversation in #528

**Comment by tseaver** [comment]
Can we simplify by saying that incomplete keys never compare equal to anything?  We shoudn't expect them to be super long-lived anyway, and the use-cases seem strongly biased toward "real" equivalence.

Note that we need to implement `__hash__` as well for many sensible uses of `__eq__`.

**Comment by jgeewax** [comment]
Just had a chat with @dhermes about "what does equality mean?". The current thinking is:

- Equal key path
- Equal entity data (dictionary equivalence)
- Equal dataset_id (`if dataset_id.startswith(s~ or e~): dataset_id = dataset_id[2:]`)

If people just want to compare the entity data, they can do a `dict(entity) == `
If people just want to compare the key path, they can do a `key.path ==`
