### ISSUE TITLE
Prep for M1 announcement

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#534]
Remaining work to "launch" M1:

### Code
- [ ] Finish "API buffing work" (~~#336 and~~ implementing PRs)
- [ ] API docs cleanup pass
- [ ] Check Python3 support in deps one last time (#91, particularly protobuf)

### LGTMs
- [ ] Solicit an LGTM from @GoogleCloudPlatform/cloud-datastore 
- [ ] Find out if there are other teams we should get an LGTM for...

**Comment by dhermes** [comment]
There is really no context for this anymore.

@jgeewax Please re-open if we have a "plan" of an announcement at any point.
