### ISSUE TITLE
storage: cannot set object properties

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/gcloud-python#536]
Or at least I haven't figured out how. This is how the documentation suggests it may work.

```Python
>>> from gcloud import storage
>>> bucket = storage.get_bucket('bucket', 'id')
>>> key = storage.key.Key(bucket=bucket, name='dir/file.webp', 
...                       properties={'contentType': 'image/webp'})
>>> key.upload_from_filename('dir/file.webp')
```
Success?
```Python
>>> key.properties['contentType']
'image/webp'
>>> key.content_type
'image/webp'
```
It's a lie unfortunately. (Also verified with ```gsutil```).
```Python
>>> webp = bucket.get_key('dir/file.webp')
>>> webp.properties['contentType']
u'application/unknown'
>>> webp.content_type
u'application/unknown'
```

**Comment by pdknsk** [comment]
Just an additional minor remark. ```gsutil``` prefers ```application/octet-stream``` to ```application/unknown```.

**Comment by dhermes** [comment]
@pdknsk Thanks for the feedback, we'll look into it. (Also thanks for hunting down a more sensible default.)

**Comment by tseaver** [comment]
Note that [upload_from_filename](https://github.com/GoogleCloudPlatform/gcloud-python/blob/dcb73d34b74c9be34635dc387bf5afd3da650006/gcloud/storage/key.py#L358) overwrites any previously-set `contentType` (via `upload_from_file`).  So, the fix would be to call `self._reload_properties()` at the end of `upload_from_file`.

**Comment by pdknsk** [comment]
I applied the fix and the result is this.
```Python
>>> key.upload_from_filename('dir/file.webp')
>>> key.content_type
u'application/unknown'
```
Which is correct in a way, because that's how the object is stored online, even if incorrectly so.

I tried ```Cache-Control``` and it doesn't work either.

**Comment by pdknsk** [comment]
I've figured out that in order send metadata with the request it has to be set on the request body before ```upload.ConfigureRequest``` is called. This works for ```Content-Type``` and ```Cache-Control``` in this case.
```Diff
--- a/gcloud/storage/blob.py
+++ b/gcloud/storage/blob.py
@@ -296,7 +296,7 @@ class Blob(_PropertyMixin):
         }
 
         upload = transfer.Upload(file_obj,
-                                 content_type or 'application/unknown',
+                                 content_type or self.properties.get('contentType', 'application/unknown'),
                                  total_bytes, auto_transfer=False,
                                  chunksize=self.CHUNK_SIZE)
 
@@ -311,6 +311,11 @@ class Blob(_PropertyMixin):
         # Use apitools 'Upload' facility.
         request = http_wrapper.Request(upload_url, 'POST', headers)
 
+        if self.properties:
+            import json
+            headers['content-type'] = 'application/json'
+            request.body = json.dumps(self.properties)
+
         upload.ConfigureRequest(upload_config, request, url_builder)
         query_params = url_builder.query_params
         request.url = conn.build_api_url(path=self.bucket.path + '/o',
```

**Comment by dhermes** [comment]
So the core issue here is that `Blob.upload_from_filename` uses `mimetypes` rather than the given `content_type`. I tested with a [real webp file][2] and `mimetypes` doesn't know what to think.

You could "get around this" by [using `upload_from_file`][1]  directly.

[1]: https://gist.github.com/dhermes/ed61e3a5e8206b7be471
[2]: https://www.gstatic.com/webp/gallery/4.sm.webp

**Comment by dhermes** [comment]
@tseaver I'm going to send a fix and we should discuss the "right approach" in the PR.

**Comment by pdknsk** [comment]
I haven't tried but from what I can tell 83c0fc1 only fixes ```Content-Type``` but not the other properties, called [Optional Properties](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) in the docs. The underlying library nicely does all the work on this when it [detects](https://github.com/GoogleCloudPlatform/gcloud-python/blob/8ab8c1bca7da80ab3d5b7ee918f74589c0e84cac/_gcloud_vendor/apitools/base/py/transfer.py#L533) that ```request.body``` is set.

**Comment by dhermes** [comment]
@pdknsk Yeah, per my comments in #629 I think we're better off having a clear `Blob.create()` and `Blob.update()`. Still trying to figure out what the best API surface is.

**Comment by pdknsk** [comment]
The only difference I noticed in setting the metadata separately afterwards is that it increases [metageneration version](https://cloud.google.com/storage/docs/generations-preconditions#_Generations). So you wouldn't be able to make an object with metageneration ```1```. I have no clue if anyone would need it — I very much doubt it.

And another remark on this bug. The ```gsutil``` [documentation](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#content-type) has an interesting comment stating that if ```Content-Type``` is not set, it will be set server-side.
> For example, at the time of writing this, the filename extension ”.webp” was recognized by the server-side content detection system, but not by gsutil.

I haven't been able to get this to work though, with ```gsutil``` at least.

**Comment by dhermes** [comment]
Thanks for digging more. I filed #632 and hopefully (if we move forward on it) something like `Blob.create()` will handle this correctly.

**Comment by dhermes** [comment]
@pdknsk So I merged the fix, but you indicated other things are not addressed.

Essentially `upload` doesn't send `properties` is the issue?

It seems instead of `blob._reload_properties()` (as @tseaver said) we would want to call 

```python
blob._patch_properties(blob._properties)
```

at the end of `upload`. WDYT? Shall we open a new bug (not specific to content type)?

Or instead do you think the plan put forth in #632 is sufficient?

**Comment by pdknsk** [comment]
I tried and it works well.

It does however also set ```metageneration``` version to ```2```. As I already said, I have no clue if anyone needs metageneration ```1```.

Another potential problem is that between both separate requests, the object is very briefly online with incorrect properties, I think. This could byte anyone who uses permissive ```acl``` by default on the bucket, and sets a restrictive ```acl``` per object, as opposed to the better, opposite way. There is also the freak chance that your connection fails just after the first request, which makes it not so brief.

**Comment by dhermes** [comment]
Yeah it needs a lot of work, thanks for verifying. Hopefully #632 leads to something useable.
