### ISSUE TITLE
Consider removing hard dependency on PyOpenSSL

### ISSUE THREAD

**Issue by s3ththompson** [GoogleCloudPlatform/gcloud-python#537]
Authenticating service accounts with a JSON private key should not require installing PyOpenSSL.

More specifically, when [`isinstance(credentials, service_account._ServiceAccountCredentials)`](https://github.com/GoogleCloudPlatform/gcloud-python/blob/f577b3079333273f0be3393de4f3767853f95add/gcloud/storage/connection.py#L65) is `True`, PyOpenSSL is not required.

Given that PyOpenSSL requires OpenSSL, minimizing the dependency is beneficial.

**Comment by dhermes** [comment]
:+1: The `oauth2client` dependency should be sufficient. It's a dep that's been "unexamined" for some time. The last time it was touched was in #419 (my PR). It's used to convert a PKCS12 key to a PM payload for signing a URL.

```python
        # Take our PKCS12 (.p12) key and make it into a RSA key we can use.
        pkcs12 = crypto.load_pkcs12(
            base64.b64decode(credentials.private_key),
            'notasecret')
        pem_text = crypto.dump_privatekey(
            crypto.FILETYPE_PEM, pkcs12.get_privatekey())
```

The function `storage.connection._get_pem_key` is **only used** by the function `storage.connection._get_signed_query_params` which in turn is **only used** by `storage.connection.Connection.generate_signed_url`.

The only other place we use "crypto" is in our regression tests, checking an MD5 hash against a stored file.

------

@craigcitro What do you think about moving some of the behavior of `_get_pem_key` and `_get_signed_query_params` into google/oauth2client? We've discussed this before, but signed a URL is a generic thing people may do.

**Comment by craigcitro** [comment]
@dhermes SGTM, especially if you move some tests in with it. `;)`

**Comment by dhermes** [comment]
google/oauth2client#115 created to offload the dependency onto `oauth2client`.

That library makes me sad every time I read the source :( But this is true of a **lot** of popular libraries, so meh.

I'm wondering if we could also ditch the `PyCrypto` dependency? @s3ththompson I don't have a lot of expertise here, is one easier to deal with than the other?

**Comment by s3ththompson** [comment]
Since PyCrypto is a pure-python library, there's not really a need to ditch it as a dependency.  The problem with PyOpenSSL is just that it depends on installing OpenSSL a (non-python) binary.

**Comment by dhermes** [comment]
Ahhh! Very nice.

**Comment by dhermes** [comment]
So google/oauth2client#115 has been cut, so fixing this can now be done on the next release of `oauth2client`.
