### ISSUE TITLE
Remove "Python" from top section of docs and make section much smaller.

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#538]
Can we make this say something more descriptive? Maybe mirror what we see on the Node JS page? (http://googlecloudplatform.github.io/gcloud-node/#/)

**Comment by silvolu** [comment]
I'll fix this along with #472 asap.

**Comment by dhermes** [comment]
Thanks @silvolu !

**Comment by dhermes** [comment]
It turns out this is the same as #614, just stated differently.

**Comment by jgeewax** [comment]
If you want to combine the two, that's OK. But this one certainly isn't blocked on a landing page. To be extra clear, here's the thing I'm talking about::

![python](https://cloud.githubusercontent.com/assets/112928/6187585/244d036e-b356-11e4-95d5-c30cc7190b61.png)

**Comment by jgeewax** [comment]
Feel free to re-close if you still think it's a dupe.

**Comment by dhermes** [comment]
@jgeewax I believe you're talking about `http://googlecloudplatform.github.io/gcloud-python/`

When #624 gets merged, that page will live at one of

```
http://googlecloudplatform.github.io/gcloud-python/latest/
http://googlecloudplatform.github.io/gcloud-python/0.4.0/
http://googlecloudplatform.github.io/gcloud-python/master/
```

and `http://googlecloudplatform.github.io/gcloud-python/` can be a true landing page.

I'm going to leave this open though because just "Python" isn't very useful. Nothing at all would be better even.

**Comment by dhermes** [comment]
@jgeewax WDY want to do with this bug.

Current http://googlecloudplatform.github.io/gcloud-python/latest/

![screen_shot_003](https://cloud.githubusercontent.com/assets/520669/6311372/a8197f72-b916-11e4-909b-ce6081bab688.png)

Current http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0

![screen_shot_004](https://cloud.githubusercontent.com/assets/520669/6311375/b6e2ba82-b916-11e4-9555-54984b546343.png)

**Comment by jgeewax** [comment]
Can we swap this to "Python Client Library" ? or "gcloud for Python" ? Or something more descriptive? What would you guys expect to see ? (I certainly wouldn't expect just "Python")

**Comment by dhermes** [comment]
It looks fine with no title at all, especially considering we have the blue bar that says Python as well:

![screen_shot_069](https://cloud.githubusercontent.com/assets/520669/6355620/256bea58-bc0c-11e4-8b3c-5049cd0f4acc.png)

and another example page

![screen_shot_070](https://cloud.githubusercontent.com/assets/520669/6355621/256d6b80-bc0c-11e4-8e55-e594a95b33b9.png)


What do the node guys thinks?

**Comment by dhermes** [comment]
@jgeewax WDYT of the above?

**Comment by jgeewax** [comment]
Can we make that space ... much smaller? looks like we're wasting lots of space there if there's no text.

**Comment by dhermes** [comment]
SGTM. I don't know who has been creating the template but it is shared between at least us and Node.

Can I move this to "Core Future"?
