### ISSUE TITLE
DISCUSSION: abstractions of service calls in storage

### ISSUE THREAD

**Issue by silvolu** [GoogleCloudPlatform/gcloud-python#545]
Generally speaking, the library functions seem to abstract when service interactions occur from the user.  In other words, some operations are local to the object (e.g [acl.grant](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/storage/acl.py#L125)), others interact with the service (e.g. [acl.save](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/storage/acl.py#L414)), while still others interact only some of the time (e.g. [bucket.default_object_acl](https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/gcloud/storage/bucket.py#L124)).
If you're going to follow this model (and I'm not sure you should), I think you need to add preconditions to most service calls to ensure that confusing things don't happen. 
A good example of this would be the save and reload functions in the ACL class.  When should the user call reload()?  I don't think it's clear.  What happens when the user calls save() but the target ACL has changed on the service side since we last loaded it?  

This abstraction is especially dangerous because it works very well when a single client is involved but creates subtle problems when deployed at scale.

/cc @thobrla

**Comment by dhermes** [comment]
In addition to a more focused / consistent approach, I think the methods in `Connection` should have no side effects, just as we do in the `datastore` subpackage.

Just look at something like [`Connection.delete_bucket`][1]. When called with `force=True` it makes an arbitrary (potentially large) number of delete calls for individual objects. This abstraction should happen on the `Bucket` class ([if at all][2]), not on the `Connection`.

Some other differences / poorly aligned overlap (as of 86acc4a7c3e09f28e4342f905c23c188f725ba22): 
- `Connection.make_request` in `storage` vs. `Connection._request` in `datastore` (big overlap)
- `Connection.api_request` in `storage` vs. `Connection._rpc` in `datastore` (public vs. private)
- `Connection.__iter__` loops through all buckets (seems out of place). This is used in `get_all_buckets`.
- `Connection.lookup` does what `Connection.get_bucket` (probably) should do. Either way, they are too similar and one should be removed.
- `Connection.new_bucket` factory should be scrapped and higher quality `Bucket` constructor implemented (if needed) (ditto on `Bucket.from_dict`, a `classmethod` which could be incorporated into the constructor)
- `Connection.generate_signed_url` does not actually make any HTTP request and only relies on the associated `credentials` object for the connect. Consider making a function?
- `Connection.__contains__` feels out of place and is a proxy for "does connection have access to this bucket? / does this bucket exist?"

In addition, there are 10 uses of `Connection.api_request` outside of the `Connection` class:

```
$ git grep '\.api_request' | egrep -v 'storage/connection' | egrep -v test
gcloud/storage/_helpers.py:        self._properties = self.connection.api_request(
gcloud/storage/_helpers.py:        self._properties = self.connection.api_request(
gcloud/storage/acl.py:        found = self.bucket.connection.api_request(method='GET', path=url_path)
gcloud/storage/acl.py:            result = self.bucket.connection.api_request(
gcloud/storage/acl.py:        found = self.key.connection.api_request(method='GET', path=url_path)
gcloud/storage/acl.py:            result = self.key.connection.api_request(
gcloud/storage/bucket.py:            response = self.connection.api_request(method='GET', path=key.path)
gcloud/storage/bucket.py:        self.connection.api_request(method='DELETE', path=key.path)
gcloud/storage/bucket.py:        self.connection.api_request(method='POST', path=api_path)
gcloud/storage/iterator.py:        response = self.connection.api_request(
```

These should be consolidated inside `Connection` itself. (Ditto for the 2 uses of `build_api_url` in `storage.key`.)

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/86acc4a7c3e09f28e4342f905c23c188f725ba22/gcloud/storage/connection.py#L435
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/564

**Comment by dhermes** [comment]
@thobrla We are trying to distill your concerns further. /cc @tseaver 

RE: "others interact only some of the time": this is done mostly for lazy loading, which is a benefit for users. Do you think this is problematic?

RE: "`ACL.save()` without an `ACL.reload()`" I've been trying to unravel service calls and but having a hard time keeping track due to the convenience mapping of metadata keys to native Python properties. We have been discussing a bit, but don't have a clear solution / path forward.

Are you aware of
```python
with bucket.batch:
    bucket.enable_versioning()
    bucket.disable_website()
```

**Comment by thobrla** [comment]
It is a benefit for users until an error occurs (even a transient service error) and breaks the illusion of atomicity.

Batching configuration changes into a single patch request is fine.

**Comment by dhermes** [comment]
Closing based on @thobrla [comment][1].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/632#issuecomment-74305190
