### ISSUE TITLE
Milestones for 2015?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#558]
Hi guys,

Now that 2015 is here, I was wondering if we could take another pass at the milestones. We originally went with "let's just try to break this down by different services" and that seemed to kick things off. I don't know if that's the same right now, given we have the majority of work done for the different services, and still have some finishing touches.

Could we brainstorm some good milestones for the year and then update them in here?

### Straw man for us to discuss

- `gcloud.datastore` 1.0 (any issue related to Datastore getting to 1.0 from now on would go here)
- NDB Integrated into Datastore (I suspect there will be a lot of issues related to this -- maybe this is a sub-milestone to the above?)
- `gcloud.storage` 1.0 (include getting Google's Cloud Storage team to give us a :+1: on this)
- Documentation 1.0 (anything that's needed to get our docs being what we consider to be 1.0 "done")
- `gcloud.pubsub` 0.1 (anything that we need to do to get pubsub to an "alpha" that works but might be backwards incompatible over time)
- `gcloud.pubsub` 0.5 (get to "beta" -- works, stable, less likely to be backwards incompatible, but still useful)
- `gcloud.pubsub` 1.0 (including sign-off from Google's Cloud Pub/Sub team)

(same for DNS, BigQuery, SQL, and Compute)

Thoughts?

### Straw man of service priorities

1. Datastore
1. Storage
1. Pub/Sub
1. DNS
1. BigQuery
1. SQL
1. Compute

### Proposed "milestones" to add to gcloud-python for our 2015 work

1. datastore stable
1. datastore future
1. storage stable
1. storage future
1. pubsub alpha
1. pubsub beta
1. pubsub stable
1. pubsub future
1. dns alpha
1. dns beta
1. dns stable
1. dns future

and a "catch all" called "stable" for things that aren't specific to a service.

/cc @dhermes @tseaver

**Comment by dhermes** [comment]
I like it. We'll likely need to prioritize PubSub / DNS / BigQuery / SQL / Compute. I'm not clear which order you prefer.

**Comment by jgeewax** [comment]
Cool - @dhermes Updated the comment with a straw-man of priorities.

**Comment by jgeewax** [comment]
Any more suggestions before we put this to a vote?

**Comment by tseaver** [comment]
Is the following a typo:
> gcloud.pubsub 1.0 (including sign-off from Google's Cloud DNS team)

I would expect the sign-off would be from the Pubsub team?

**Comment by tseaver** [comment]
Also, is adding `gcloud.datastore.ndb` a blocker for a `datastore 1.0` milestone?

**Comment by jgeewax** [comment]
@tseaver 

- Yes it's a type, I'll fix that.
- I don't think NDB is a blocker, I think we're targeting somewhere in Q2 (Q1 if we're extra aggressive)

**Comment by jennolsen84** [comment]
python3 :+1:.  See a lot of great from @tseaver work towards that

Also perhaps something related to GKE/Kubernetes?

**Comment by jgeewax** [comment]
Hi guys, 

Just updated the issue with a proposal of the milestones to create. Can we get some +1's or any further revisions ? 
/cc @tseaver @dhermes

**Comment by tseaver** [comment]
@jgeewax I'm not sure what the `-future` bits mean WRT the other priorities.  Other than that, LGTM.

**Comment by jgeewax** [comment]
"future" is stuff that aren't blocking a stable release, but are things we want to do later. Think we should drop them ?

**Comment by dhermes** [comment]
SGTM

**Comment by jgeewax** [comment]
OK - these are all created. I spent a bit of time moving issues around -- hopefully we're close enough.

When in doubt, put stuff in the "stable" milestone, and we can push it out to "future" if we decide it's not a blocker for the stable release for a service.
