### ISSUE TITLE
Add environ extras to user-agent

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#566]
For example `gcloud-python/0.3.0-GAE` instead of just ``gcloud-python/0.3.0`.

See discussion in #561 for context.

**Comment by dhermes** [comment]
One worthwhile change from `gcloud/connection.py` (in the closed PR):

```python
import gcloud

class Connection(object):
    ...
    USER_AGENT = "gcloud-python/{0}".format(gcloud.__version__)
     """The user agent for gcloud-python requests."""
```

instead of the previous

```python
USER_AGENT = "gcloud-python/{0}".format(get_distribution('gcloud').version)
```

**Comment by dhermes** [comment]
@jgeewax On a side-note I realized we don't really have a label for a utility class like `gcloud.connection.Connection` which is inherited by each sub-package.

**Comment by jgeewax** [comment]
@dhermes : Not sure I understand the question -- can you give any more background to this?

**Comment by dhermes** [comment]
If you look in the [`gcloud/` directory][1], there are two utility modules (`connection` and `credentials`) used by every package. So a label like `storage` or `datastore` does not apply.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/tree/86acc4a7c3e09f28e4342f905c23c188f725ba22/gcloud

**Comment by dhermes** [comment]
@tseaver I'm going to close this out.

This started as a "wouldn't it be cool if we" and become way too much to implement.

--------

@jgeewax The idea was that we could have environment based user agents:

```
gcloud-python/0.4.1
gcloud-python/0.4.1-compute-engine
gcloud-python/0.4.1-app-engine
```

so that within the GOOG, doing a logs search would be able to see a breakdown of where users are making API requests.

However, I realized that there is other information in the logs that would indicate compute engine or app engine.

--------

We can revisit if it seems important. Right now, with no demand and no legitimate use case, it's not worth the dev time.

**Comment by jgeewax** [comment]
SGTM
