### ISSUE TITLE
datastore-getting-started and storage-getting-started don't actually get built into docs

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#567]
They are in `docs/_components` and so are not built into it. To verify

```
$ tox -e docs
...
$ grep -r 'sort of like' docs/_build/html/  # A phrase from datastore-getting-started
$ grep -r tutorial docs/_build/html/  # A word from storage-getting-started
```

**Comment by silvolu** [comment]
When I migrated from the developers.google.com like style to the gcloud one, I didn't include those pages because I thought there was too much 'getting started with...' and 'this thing in 10 seconds' going on.
Agree with you it should be decided either to include them in some way or remove them.

**Comment by dhermes** [comment]
They have been completely removed now
