### ISSUE TITLE
Add Authorization section to README (follow the new format)

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#591]
See GoogleCloudPlatform/gcloud-meta#3 for what we're hoping to be the shared (mostly) format.

**Comment by dhermes** [comment]
I'm updating the title based on my comment "Holding off on Authorization until we finalize this behavior and unify across services." in #673.

**Comment by dhermes** [comment]
@jgeewax What do we want to do about this?

**Comment by jgeewax** [comment]
We obviously need extra stuff outside of the shared docs, but anything that is common would (ideally) get pushed back up into gcloud-common... Otherwise, we can call this done.
