### ISSUE TITLE
Code changes are not reflected in Pypi package

### ISSUE THREAD

**Issue by vasanthnathan** [GoogleCloudPlatform/gcloud-python#592]
```pip install gcloud``` which installs version "0.3.0" has different code base than what it is specified in the documentation. For example the dataset class is not present in the document, but it still exists in the code. Right now I am using the dataset class as a reference to communicate to cloud datastore,since I have seen a lot of changes added to the master branch I wanted to use the updated code base, so when do we can expect the next release?

**Comment by dhermes** [comment]
@vasanthnathan Thanks for filing. This has already been mentioned in #472 and we are working on it.

In the meantime, we will try to cut a new release soon so you can have access to the new features via PyPI.

Closing as a duplicate issue.
