### ISSUE TITLE
Figure out what our "usable auth" story is for gcloud-python

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#593]
There is some discussion going on now about a separate library that would *just* handle authentication. The goal of this issue is:

- [ ] figure out a plan to moving the authentication code into a separate library we depend on (apitools? googleauthkit (working name)?)
- [ ] make this library exist and add it as a dependency (if not already done)
- [ ] remove our custom authentication code and replace it with calls into this outside library to get an authenticated transport

(Forgive me if this is a duplicate issue...)

**Comment by tseaver** [comment]
ISTM that (with the exception of signing URL endpoints, which uses crypto, but is not really authnz), we already delegate pretty much all our authnz to `oauth2client`.

**Comment by dhermes** [comment]
Echo what @tseaver says. We don't have any custom auth behavior and the auth is quite usable.

**Comment by dhermes** [comment]
@jgeewax Closing this out because it's been in `oauth2client` all along. Please re-open if you disagree.
