### ISSUE TITLE
Enable resolution of unprefixed dataset IDs

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#609]
This started in #528 before an existing bug existed.

**Comment by dhermes** [comment]
Porting comment [from][1] @jgeewax on related issue (#475):

> This isn't possible with the current dataset_id situation requiring s~ or e~ prefixes in 
> the key protobuf. Moving to Datastore Future since we don't know for sure when
> this will be fixed.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/475#issuecomment-72705448

**Comment by yjkogan** [comment]
+1 to this. I had an issue with ndb.StructuredProperties related to this where app engine couldn't access an entity's structure properties b/c one of them was a key with `_app=MY_APP` instead of `_app=s~MY_APP`.

**Comment by dhermes** [comment]
@yjkogan Comment makes me realize I should link to GoogleCloudPlatform/google-cloud-datastore#59 in this issue.

@yjkogan You are better off just using `s~MY_APP` as your dataset ID.

We'd like to help along people who don't realize the prefix exists, but since you do, it's no big deal to use. Does that make sense?

**Comment by yjkogan** [comment]
@dhermes Yeah I just set `s~MY_APP` as my dataset id. It was an easy workaround. Just +1ed since I'm in favor of making that distinction invisible to users of this library.

**Comment by dhermes** [comment]
Great!

**Comment by dhermes** [comment]
This is made moot by `v1beta3`, follow #1288 for progress towards that.
