### ISSUE TITLE
`datastore.set_defaults()` does not error, but `Key` constructor fails

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-python#618]
The following code
```
from gcloud import datastore
datastore.set_defaults()
key = datastore.Key('test',1)
```
Results in `ValueError("A Key must have a dataset ID set")`

**Comment by dhermes** [comment]
@elibixby Thanks for filing. #610 covers this.

**Comment by elibixby** [comment]
@dhermes woops, thanks, sorry for the noise.

**Comment by dhermes** [comment]
It's not noise. I assume your using `0.4.0` from PyPI rather than pulling from HEAD. Either way #610 has only been merged for like 12 hours.
