### ISSUE TITLE
Problem handling local structured property kind without keys

### ISSUE THREAD

**Issue by twumdjin** [GoogleCloudPlatform/gcloud-python#627]
According to: https://cloud.google.com/appengine/docs/python/ndb/properties#structured
Local structured properties do not require keys and AppEngine appears to be fine with this.
Unfortunately, the gcloud-python library expects keys for every entity, even if they're local structured ones.
My work around is to update my entities in AppEngine to provide dummy keys, however, it would be nice if the library supported it natively.

```
gcloud/datastore/helpers.pyc in entity_from_protobuf(pb)
     46     :returns: The entity derived from the protobuf.
     47     """
---> 48     key = key_from_protobuf(pb.key)
     49     entity_props = {}
     50     exclude_from_indexes = []

gcloud/datastore/helpers.pyc in key_from_protobuf(pb)
    103         namespace = pb.partition_id.namespace
    104 
--> 105     return Key(*path_args, namespace=namespace, dataset_id=dataset_id)

gcloud/datastore/key.pyc in __init__(self, *path_args, **kwargs)
     74         # _flat_path, _parent, _namespace and _dataset_id must be set before
     75         # _combine_args() is called.
---> 76         self._path = self._combine_args()

gcloud/datastore/key.pyc in _combine_args(self)
     131         :raises: :class:`ValueError` if the parent key is not complete.
     132         """
--> 133         child_path = self._parse_path(self._flat_path)

gcloud/datastore/key.pyc in _parse_path(path_args)
      92         """
      93         if len(path_args) == 0:
---> 94             raise ValueError('Key path must not be empty.')
 
ValueError: Key path must not be empty.
```

**Comment by dhermes** [comment]
@twumdjin Thanks for filing! It was actually filed a few days ago as #616 and fixed in #617. You can use the newest version via

```
pip install git+https://github.com/GoogleCloudPlatform/gcloud-python
```

or wait for the next release.

I am considering cutting a `0.4.1` release tomorrow.

**Comment by dhermes** [comment]
Also @twumdjin thanks for using the library and caring enough to give feedback!

**Comment by twumdjin** [comment]
Thanks for the really quick response Danny!
I was very glad I found this library, I was in the process of porting GAE's ndb library to provide a a cleaner ORM layer to Google datastore when I stumbled upon your project on an SO response. I seriously wish I'd found it sooner, keep up the great work!

I'll be looking forward to the next release.

**Comment by dhermes** [comment]
Thanks @twumdjin 

I'd also recommend following #557. We plan on porting `ndb` wholesale at some point.

As an aside, what sort of posting or announcement could we have made to

1. Make it clear this library exists (even though it's not an ORM like `ndb`)
1. Make it clear we intend to support `ndb` at some point

**Comment by twumdjin** [comment]
Would be great if that port happens. While the async functionality on ndb is great and I use it extensively, I wouldn't even mind having a version that didn't support async initially. Simply having some OO interface to entity definitions would be a big win. 

Unfortunately, discovering this library is a bit of an SEO challenge. 
I see that it comes up first on a query for "gcloud datastore", however, I get the impression 'Google datastore' and 'Google cloud datastore' would be a more popular search term for the service and the Google docs on the service itself dominate search results for for anything with those combinations (understandably).

I wonder if you can get this linked from the official Google Datastore documents. Some of the other Google services have client libraries promoted that way.

I can't imagine anyone using Google datastore outside of GAE who wouldn't be hunting for a solution like this

**Comment by dhermes** [comment]
Thanks for the detailed feedback @twumdjin. It's really useful!

/cc @jgeewax

**Comment by jgeewax** [comment]
Thanks for the feedback @twumdjin (and for the CC @dhermes) !

Once we get to a 1.0 release, we'll update the official Google Cloud Platform Python snippets, examples, and documentation to use gcloud-python code (and obviously link to it from the homepage of how to get started in Python by running `pip install gcloud`).

If you're interested in the "1.0" timeline, we're aiming for the Datastore, Storage, and Core "Stable" milestones to be closed out (see https://github.com/GoogleCloudPlatform/gcloud-python/milestones?direction=desc&sort=completeness&state=open).

**Comment by twumdjin** [comment]
Thanks for the 0.4.1 update with the fix @dhermes!

**Comment by dhermes** [comment]
Glad it helps!
