### ISSUE TITLE
Entity documentation error

### ISSUE THREAD

**Issue by rstuart85** [GoogleCloudPlatform/gcloud-python#630]
[Line 37 of gcloud.datastore.entity.Entity][1] says 

```
Use :func:`gcloud.datastore.get` to retrieve an existing entity."
```

There is no such function. I think you mean `gcloud.datastore.api.get()`.

Also, on a side note but slightly related, I find the package name `gcloud.datastore.entity.Entity` strange. Why not just `gcloud.datastore.Entity`? Seems that the currnet approach probably goes against PEP 423 and 25.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f73ad7e8fc877e14e2f9c0b4ec42430f2396f770/gcloud/datastore/entity.py#L37

**Comment by pdknsk** [comment]
Both of these are available as aliases in  ```0.4.0``` at least.

```Python
>>> import gcloud
>>> gcloud.datastore.api.get
<function get at 0x7f9113397488>
>>> gcloud.datastore.get
<function get at 0x7f9113397488>
>>> gcloud.datastore.entity.Entity
<class 'gcloud.datastore.entity.Entity'>
>>> gcloud.datastore.Entity
<class 'gcloud.datastore.entity.Entity'>
```

**Comment by dhermes** [comment]
@rstuart85 You are both correct and "incorrect". I filed #632 and hopefully (if we move forward on it) something like `Blob.create()` will handle this correctly.

**Comment by dhermes** [comment]
@rstuart85 You are both correct and "incorrect".

The classes and functions needed for `datastore` are [loaded][1] into the main namespace in `__init__.py`:

```
from gcloud import credentials
from gcloud.datastore import _implicit_environ
from gcloud.datastore.api import allocate_ids
from gcloud.datastore.api import delete
from gcloud.datastore.api import get
from gcloud.datastore.api import put
from gcloud.datastore.batch import Batch
from gcloud.datastore.connection import Connection
from gcloud.datastore.entity import Entity
from gcloud.datastore.key import Key
from gcloud.datastore.query import Query
from gcloud.datastore.transaction import Transaction
```

@pdknsk Thanks for the assist.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/f73ad7e8fc877e14e2f9c0b4ec42430f2396f770/gcloud/datastore/__init__.py#L51-L62

**Comment by tseaver** [comment]
> I find the package name gcloud.datastore.entity.Entity strange. Why not just gcloud.datastore.Entity? Seems that the currnet approach probably goes against PEP 423 and 25.

FWIW, on the terminology front:

- `gcloud` and `gcloud.datastore` are packages
- `gcloud.datastore.entity` is a module
- `gcloud.datastore.entity.Entity` is a class. As @dh

**Comment by dhermes** [comment]
:+1: Thanks @tseaver
