### ISSUE TITLE
Warning admonitions are the same color as note (and tip) admonitions

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#636]
Looks like we're not making warnings very scary. Might be worthwhile to make them... a subtle yellow or orange so they stand out a tiny bit?

This is how it looks today (http://googlecloudplatform.github.io/gcloud-python/storage-blobs.html#gcloud.storage.blob.Blob.rename) 

![warning-admonition](https://cloud.githubusercontent.com/assets/112928/6187538/9e745e9a-b355-11e4-9a33-fa3c6ed15f3c.png)

**Comment by dhermes** [comment]
Closing this since CSS will be part of shared docs.
