### ISSUE TITLE
DISCUSSION: Fixed version link in README

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#642]
In the README / `long_description` that gets uploaded to PyPI, is it important that we link to the static version of the docs corresponding to that version?

More concretely, should https://pypi.python.org/pypi/gcloud/0.4.1 link to

```
https://googlecloudplatform.github.io/gcloud-python/latest/
```

or

```
https://googlecloudplatform.github.io/gcloud-python/0.4.1/
```

If we say the latter, then `setup.py` will need to do a replace
```python
long_desc = long_desc.replace(
    'https://googlecloudplatform.github.io/gcloud-python/latest/',
    'https://googlecloudplatform.github.io/gcloud-python/{VERSION_HERE}/'
)
```

(Though maybe the link in the README should point to the `/master` docs instead of the `/latest` docs)

**Comment by tseaver** [comment]
I would say point to the landing page, where folks can pick the version of the docs they want.

**Comment by dhermes** [comment]
1) I like that approach because it requires doing nothing :)

2) But if they are on https://pypi.python.org/pypi/gcloud/0.4.1 don't we assume they want the 0.4.1 docs?

**Comment by tseaver** [comment]
Leaving them the choice is OK to me.  If we had a cool switcher like the [one used on RTD](http://zopeeent.rtfd.org) (see the bottom left), we could just land them on `/latest`.

**Comment by dhermes** [comment]
1. I like the switcher on RTD and we could probably add one eventually.
1. I was more focusing on people who are looking at an old version, i.e. we are at 1.0.0 and they are pinned at 0.7.3, so they want those docs immediately.

**Comment by dhermes** [comment]
Closing this out. We can address if people ever have concerns.
