### ISSUE TITLE
Add datastore.get_defaults() ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#648]
It looks like we have a `set_defaults()` method, but no `get_defaults()` method to introspect exactly what we have set here.

I have a feeling that for debugging purposes it might be a nice thing to have? I could be wrong here though...

**Comment by dhermes** [comment]
Yes, working on a design for lazy-loading (i.e. don't call `datastore.set_defaults()`) which will incorporate this.
