### ISSUE TITLE
Add support for gcd local development server

### ISSUE THREAD

**Issue by rstuart85** [GoogleCloudPlatform/gcloud-python#650]
Right now, there doesn't appear to be any support for the [datastore local development server gcd](https://cloud.google.com/datastore/docs/tools/devserver). For instance, the usage instructions tell you to set the dataset id in the environment variable ``DATASTORE_DATASET`` but gcloud-python doesn't appear to look for that in the ``set_default_dataset_id()`` function.

**Comment by rstuart85** [comment]
It's not clear to me how exactly this is meant to work. I have set the environment variable DATASTORE_HOST to be the local development server as per the gcd instructions but it seems to be completely ignored by gcloud-python. It works with the googledatastore library so it would be nice if it worked here too.

**Comment by dhermes** [comment]
@rstuart85 Thanks for the request. I have not used `gcd` and will look into this. It should be easy enough to support in `gcloud/datastore/connection.py` (at 61c6814d81525b0a35581943b58cc36c687e7332)

```python
class Connection(connection.Connection):
    API_BASE_URL = os.getenv('DATASTORE_HOST', connection.Connection.API_BASE_URL)
    ...
```

and in `gcloud/datastore/__init__.py`

```
def set_default_dataset_id(dataset_id=None):
    if dataset_id is None:
        dataset_id = os.getenv(_DATASET_ENV_VAR_NAME)

    if dataset_id is None:
        dataset_id = os.getenv('DATASTORE_DATASET')

    if dataset_id is None:
        dataset_id = _implicit_environ.app_engine_id()
   ...
```

(check comes before App Engine but after the production environment variable)

**Comment by rstuart85** [comment]
Certainly seems straightforward and would really simplify local development of products that use Datastore. Hopefully it will also reduce latency when developing!

**Comment by dhermes** [comment]
@rstuart85 support is in. We'll (hopefully) cut `0.4.2` on Friday so you'll be able to use `gcd` out of the box.

**Comment by rstuart85** [comment]
@dhermes Wonderful, thanks for all the hard work.

**Comment by dhermes** [comment]
@rstuart85 sorry for the delay but `0.4.2` went out today so use `gcd` at your heart's content!
