### ISSUE TITLE
Make left nav in the docs position:fixed

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#681]
It'd be really nice if the left navigation scrolled with you as you get further down (so that the only "scrolling" part of the page is the actual content).

This way, when you get really far down the page, instead of needing to scroll to the top to view the navigation, it's already right there.

Here's what we have today:

![scrollfix](https://cloud.githubusercontent.com/assets/112928/6372454/5e4393e6-bcd2-11e4-8489-865d5fea1868.png)

Here's what I hope we can make it look like:

![scrollfixed](https://cloud.githubusercontent.com/assets/112928/6372490/a2f94030-bcd2-11e4-805a-901b338069ca.png)

**Comment by dhermes** [comment]
@jgeewax This seems like a "nice-to-have" we'd hand off to a designer, yes? Most of the changes I've been making recently were actually features needed.

**Comment by jgeewax** [comment]
Yep - that's why it's in the "Future" milestone.

**Comment by dhermes** [comment]
I figured. Thanks.

**Comment by jgeewax** [comment]
Closing this out since we're going to working on shipping docs as JSON to the gcloud-common site
