### ISSUE TITLE
Purge set_defaults() from all the docs

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#685]
Is set_defaults() fully not necessary anymore? If so, can we chop that from all the documentation?

Looks like they're in there quite a bit...  (http://googlecloudplatform.github.io/gcloud-python/latest/datastore-api.html)

**Comment by dhermes** [comment]
Yes, we even discussed tearing it out as a method since `set_default_connection()` and `set_default_dataset_id()` exist.

**Comment by jgeewax** [comment]
Love it. I'll update the ticket to be more clear :)

**Comment by dhermes** [comment]
Tackling this right now.
