### ISSUE TITLE
Update gcloud.storage docs to use 'from gcloud import storage'

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#686]
Looks like we use `import gcloud.storage` a lot in the storage docs (http://googlecloudplatform.github.io/gcloud-python/latest/storage-api.html).

I'd prefer if we kept it consistent with datastore, to use `from gcloud import storage`.

Thoughts?

**Comment by dhermes** [comment]
I do too. Much to be done still in docs (see #632)

**Comment by dhermes** [comment]
Running

```
$ git grep 'import gcloud\.storage'
```

turns up nothing while

```
$ git grep 'from gcloud import storage' | wc
     10      51     562
```
