### ISSUE TITLE
Solved a wsgi_server issue

### ISSUE THREAD

**Issue by ashumeow** [GoogleCloudPlatform/gcloud-python#687]
I solved a bug issue for Google Cloud in Python by editing in wsgi_server.py --- Do you know where can i send the patch? I've never sent a patch to Google before.
Anyways, Here it goes...
I was unable to bind to localhost:8000. The online answers <a href="http://stackoverflow.com/questions/22601724/unable-to-bind-localhost8000-error-while-running-sample-application-in-google">never helped</a> me.
Then, i entered into this path:-
<code>C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2</code>
Then, i edited <code>wsgi_server.py</code>
There was error in <code>lines 314 and 336</code>
I changed it to:-
line 314:- <code>if port != 8000:</code>
line 336:-<code>assert port != 8000</code>
After changing it... i did a run on one demo file to check it --- <code>dev_appserver.py guestbook</code>
It worked. (^_^)

**Comment by dhermes** [comment]
Thanks for taking the time to file a bug! Unfortunately, this repository is not for App Engine / `dev_appserver.py`.

This is where you'll want to go to file the issue:
https://code.google.com/p/googleappengine/wiki/FilingIssues?tm=3

Maybe @jgeewax can comment on any equivalent place on GitHub to file the bug? As far as I know Google Code Hosting is the only place.

**Comment by ashumeow** [comment]
@dhermes  Thank you so much for your help. I sent a patch here:- https://code.google.com/p/googleappengine/issues/detail?id=11739
