### ISSUE TITLE
[QUESTION] What's the feasibility of something like GridFS (from mongo) for entities greater then 1MB?

### ISSUE THREAD

**Issue by rstuart85** [GoogleCloudPlatform/gcloud-python#696]
MongoDB has implemented a feature called [GridFS](http://docs.mongodb.org/manual/core/gridfs/) for all of their drivers. It overcomes the 16MB BSON-document size limit. The Python code is [here](https://github.com/mongodb/mongo-python-driver/tree/master/gridfs).

The 1MB limit on entities can be an issue in some applications and a feature like GridFS would be a great way to overcome that. Is such a feature something that could live in this project?

**Comment by dhermes** [comment]
It seems like feature creep that isn't really needed when Cloud Storage is so readily available.

The Google Cloud Datastore is meant to be a key-value store (typical NoSQL) while Google Cloud Storage is meant to be an object store.

OTOH MongoDB is document-oriented, so something like GridFS fits more in that context.

**Comment by dhermes** [comment]
@rstuart85 I don't think it makes sense given Cloud Storage. Feel free to re-open if you'd like to take up the discussion again.
