### ISSUE TITLE
datastore.get() requires a list

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#701]
See http://googlecloudplatform.github.io/gcloud-python/

The snippet is:

```python
from gcloud import datastore
datastore.set_defaults()

product_key = datastore.Key('Product', 123)
print datastore.get([product_key])
```

I'd expect it to be:

```python
from gcloud import datastore
product_key = datastore.Key('Product', 123)
product = datastore.get(product_key)
```

**Comment by dhermes** [comment]
Sorry about that. The homepage source only lives in the `gh-pages` branch so my `git grep` for `set_defaults()` missed it.

As for `datastore.get(key)`, the method only accepts one type: a list (of keys). When we were making these, we were noticing that half the code was special casing the input types and it just wasn't worth it for two brackets.

**Comment by jgeewax** [comment]
@dhermes : Did we have an issue for that to discuss? I really think it's worthwhile to do that... :(

**Comment by dhermes** [comment]
No specific issue to discuss. Came as part of adding `get()` / `put()` / `delete()` as per request from datastore team. (They are very nice to have. I'm happy we did it, it made the code much nice and informed the way we wrote `Batch` -> `Transaction`.)

I know Python is slow already, but for high-traffic apps, I cringe at adding a branch point into these methods every time they get called

```python
if isinstance(entities, list):
    ...
else:
    ...
```

**Comment by jgeewax** [comment]
The latency we'd be introducing there would be *nothing* compared to the latency from wire time getting to and from datastore. Datastore's selling point is latency, it's availability and throughput.

I'm a huge fan of taking away the brackets....

**Comment by jgeewax** [comment]
Renaming the issue to reflect the remaining issue: .get only ever taking a list.

I really would like to add the following to our `.get` method:

```python
def get(keys):
  if isinstances(keys, datastore.Key):
    keys = [keys]
  ...
```

I have no issue at all with the extra branch when this is called. Our goal is usability first, performance second.

**Comment by jonparrott** [comment]
I would also prefer adding the ability to specify a single key and additionally not get a list back if I specify a single key.

**Comment by jgeewax** [comment]
Oh - that's a good point! We should recognize when a single key is provided and return a single result back. Maybe something along the lines of...

```python
def get(key):
  if not isinstance(key, datastore.Key):
    return get_multi(key)
  result = get_multi([key])
  return result[0] if result else None

def get_multi(keys):
  return multiple_entity_results
```

**Comment by jonparrott** [comment]
Yep, that's exactly what I had in mind.

**Comment by dhermes** [comment]
Just did too much sleuthing to figure out how much code we had to support this before. It was removed in #582. So we'd be adding 11+ lines of code and tests to make it so that users can do

```python
result = datastore.get(key)
```

instead of

```python
result, = datastore.get([key])
```

I'm not giving an opinion here, just some numbers.

----

As for an opinion, it doesn't make sense to have two different methods for this that do identical things. We should help the users understand that the API makes no distinction between a list of 1 and a list of N keys in a lookup request.

**Comment by jgeewax** [comment]
Cool - thanks for those numbers. 11 LOC doesn't sound unreasonable to me to give some convenience to the method...

**Comment by tseaver** [comment]
I don't see the added complexity as any kind of win:

- Having the return type of a library function / method depend on its arguments is a recipe for surprising the library's users.
- The amount of complexity induced on those methods (in terms of extra code paths, and therefore extra tests) is pretty large.

I'd rather have a `get` and `get_many` than mangle the two cases together.

**Comment by dhermes** [comment]
What if we just leave `datastore.get([...])` as is and just implement `Key.get()`? Only caveat being I'm not sure it's possible to implement `Key.get()` without import cycle hell.

**Comment by jonparrott** [comment]
Semantics would still be weird with ``Key.get``. It would make sense, for example, to have classmethod ``Key.get()`` capable of fetching multiple objects but instancemethod  ``key.get()`` only fetch one.

I'm personally in favor of ``get`` and ``get_multi`` or ``get_many``. single ``get`` could just be a thin wrapper around the multiple get.

**Comment by dhermes** [comment]
Yeah I'm seeing the need now. It makes me sad, `get/put/delete` was so clean and

```python
entity,  = datastore.get([key])
```

seemed close enough to

```python
entity  = datastore.get(key)
```

**Comment by jgeewax** [comment]
Yikes, I'm -1 on `Key.get` as a class method... seems kind of scary..

Note that the datastore API for App Engine has `get` accept either a list or a single key: https://cloud.google.com/appengine/docs/python/datastore/functions#get . I suspect we could keep things entirely backwards compatible if we were to go this route... (Not that that's a hard requirement, just convenient.)

NDB made some changes to that, where the only function that exists globally is `ndb.get_multi()`, and `get()` is called on an instance of a `Key` object: https://cloud.google.com/appengine/docs/python/ndb/functions

(As a side note, I suspect the majority of `get` calls are singular rather than multiple, but I'd have to pull some data on our side to know that for sure.)

**Comment by dhermes** [comment]
Yeah I think `get`/`get_multi` is the way to go, it just makes me sad (temporarily).

**Comment by jgeewax** [comment]
Also.. if it helps... I just checked the history, and I can confirm that Guido van Rossum was the one who introduced the dual-nature of `db.get()`... He made it accept both single and multiple keys, and made it return a single result (or None) for the single key, and a list for the multiple keys....

**Comment by dhermes** [comment]
Ha! I love it that you tracked that down and that it's true.

**Comment by jgeewax** [comment]
OK so what's the final call? Now that we have all the data, is it OK to allow the single/multi behavior of `get`? 

(Just to chime in, I think that even if we did allow that, we should also put in `get_multi` so that people can be explicit.... And `get_multi` should throw an error if it doesn't get a list... )

**Comment by dhermes** [comment]
@tseaver WDYT?

**Comment by tseaver** [comment]
I'd still rather not have the single/multiple in the same method.

FWIW, Guido himself has been known to be [critical of his own design choices](http://python-history.blogspot.com/), usually after they've been frozen-in-amber in the Python stdlib.

**Comment by dhermes** [comment]
OK. I'll go with `get` and `get_multi`

**Comment by dhermes** [comment]
@jgeewax @jonparrott What are your thoughts on multi vs. single for `put` and `delete`?

**Comment by jgeewax** [comment]
I don't feel super strongly, but... I think if we're going the way of `get` and `get_multi`, we should probably stick to it for put and delete like NDB does: https://cloud.google.com/appengine/docs/python/ndb/functions

**Comment by dhermes** [comment]
It's worth it to remember we're going to include `ndb` at some point. But independent of `ndb`, it probably makes sense.
