### ISSUE TITLE
Docs datastore short snippet still has set_defaults and brackets

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#702]
See http://googlecloudplatform.github.io/gcloud-python/latest/index.html#cloud-datastore

Snippet is 

```python
from gcloud import datastore
datastore.set_defaults()

entity = datastore.Entity(key=datastore.Key('Person'))
entity['name'] = 'Your name'
entity['age'] = 25
datastore.put([entity])
```

I'd expect it to be 

```python
from gcloud import datastore

entity = datastore.Entity(key=datastore.Key('Person'))
entity['name'] = 'Your name'
entity['age'] = 25
datastore.put(entity)  # Note no brackets
```

**Comment by dhermes** [comment]
@jgeewax Latest refers to the last release which was uploaded to PyPI. If you want `master`, you want:
http://googlecloudplatform.github.io/gcloud-python/master/index.html#cloud-datastore

Closing this out.

(We need to cut a release soon anyhow.)

**Comment by dhermes** [comment]
Also RE: "Note no brackets", see my comment on #701 about multiple types accepted to `put()` and `get()`.
