### ISSUE TITLE
Datastore transaction doc snippet has two imports

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#705]
See http://googlecloudplatform.github.io/gcloud-python/latest/datastore-transactions.html#gcloud.datastore.transaction.Transaction

Snippet is

```python
>>> from gcloud import datastore
>>> from gcloud.datastore.transaction import Transaction

>>> datastore.set_defaults()

>>> with Transaction():
...     datastore.put([entity1, entity2])
```

I'd expect it to be

```python
>>> from gcloud import datastore
>>> with datastore.Transaction():
...     datastore.put([entity1, entity2])
```

**Comment by dhermes** [comment]
@jgeewax Fixed in `master`:
http://googlecloudplatform.github.io/gcloud-python/master/datastore-transactions.html#gcloud.datastore.transaction.Transaction
