### ISSUE TITLE
Datastore transaction snippets all use `Transaction()` instead of `datastore.Transaction()`

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#706]
Looking at this page (in it's entirety): http://googlecloudplatform.github.io/gcloud-python/latest/datastore-transactions.html

Minor thing here, but would be more clear if we explicitly wrote `datastore.Transaction`.

Basically `s/Transaction()/datastore.Transaction()/`

**Comment by dhermes** [comment]
@jgeewax I had that same thought when I wrote #689.

Fixed in `master`:
http://googlecloudplatform.github.io/gcloud-python/master/datastore-transactions.html
