### ISSUE TITLE
Dataset isn't in the docs as a "concept

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#707]
We added back the Dataset class (basically an alias class that fills in some blanks for you), but it's not listed on the left navigation of the docs. Any chance we can put that back?

If we do, we should add a lovely `..note:` banner on that page saying that if you only interact with one dataset (a default one) that you don't need to worry about this, and you can use `datastore.<method>` and we'll automatically use the default dataset.

------------

**NOTE**: @dhermes ported this text over from #708

**Comment by dhermes** [comment]
On it.

Secondary bug is that we have no automated way of determining that modules are left out of the api docs. (It's low priority since we seldom add modules.)

**Comment by dhermes** [comment]
Filed #714 and sent an easy fix in #713.
