### ISSUE TITLE
Looks like we don't expose the `Dataset` class as datastore.Dataset?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#709]
There are some docs that use the following syntax:

```python
>>> from gcloud import datastore
>>> dataset = datastore.get_dataset('dataset-id')
```

I'm not sure if this is accurate, but either way, if we're following the convention of datastore/__init__.py, this should be:

```python
>>> from gcloud import datastore
>>> dataset = datastore.Dataset('dataset-id')
```

However I don't see the import in `__init__.py`, so I'm guessing that neither of these work...?

**Comment by dhermes** [comment]
Yeah `get_dataset` doesn't exist, I'm on it.

I did a `git blame` and that text was added in #509, a looooong time ago.

**Comment by dhermes** [comment]
@jgeewax It turns out that dead code wasn't being used in the snippet anyhow, so it just get's axed in #715
