### ISSUE TITLE
STORAGE: Which requests require a project?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#726]
Grepping through the JSON discovery spec for `"project"` it only occurs in 

```
storage.buckets.insert
storage.buckets.list
```

yet we send it with every single request:

```python
    def build_api_url(self, path, query_params=None, api_base_url=None,
                      api_version=None, upload=False):
        ...
        query_params.update({'project': self.project})
        ...
```

/cc @thobrla

**Comment by thobrla** [comment]
Yes, project is only meaningful for the two requests you mentioned.

**Comment by dhermes** [comment]
Great! @tseaver I made a PR to remove `project` from `Connection` and just use `project` in `create_bucket` and `get_all_buckets`.
