### ISSUE TITLE
STORAGE: Does a connection need to be bound to anything other than a Batch or Iterator?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#728]
Run

```
$ git grep -n '\.connection' -- gcloud/datastore/ | egrep -v test | egrep -v 'datastore\.connection'
$ git grep -n '\.connection' -- gcloud/storage/ | egrep -v test | egrep -v 'storage\.connection'
```

to compare uses.

**Comment by dhermes** [comment]
I'm going to start this work in a series of small changes (I'm guessing there will be a lot of test re-factoring).

Please protest if there are any issues.

**Comment by dhermes** [comment]
@tseaver We have some methods which make HTTP requests for historical reasons only:

```python
Bucket.update_cors
Bucket.get_default_object_acl
Bucket.update_lifecycle
Bucket.get_logging
Bucket.enable_logging
Bucket.disable_logging
Bucket.configure_website
Bucket.disable_website
Bucket.make_public
```

Also `Blob.make_public` doesn't really fit the rest of methods, but that makes an HTTP request via the `ObjectACL`.

**Comment by tseaver** [comment]
I think we could easily change the metadata-updating methods to drop the call (and require calling `patch()`).  Maybe ACL updates should also require an explict `patch` or `save` call?

**Comment by dhermes** [comment]
@tseaver I agree. Being more declarative was the original goal of #545. I tried to sketch a way (in #761) to make these properties, but some of them are a bit involved (i.e. have multiple values associated).

We could look into using `apitools` generated clients at some point?

**Comment by dhermes** [comment]
@tseaver Removing `__iter__` and `__contains__` is impossible if no `Connection` is bound to a `Bucket`. As I [mention][1] in #761, using `__iter__` is pretty scary for large applications / buckets.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/761#discussion_r27305977
