### ISSUE TITLE
Unify '_implicit_environ' handling

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#741]
There is a lot of overlap between `datastore._implicit_environ` and `storage._implicit_environ`.  We should factor that out, especially before implementing yet another version in `pubsub`.

**Comment by dhermes** [comment]
I like it. Was trying to move gradually towards this while building out the implicit functionality into `storage`.

The hardest thing to factor out is the dependence on the local concepts of `Connection` and `_DefaultsContainer`.

**Comment by tseaver** [comment]
Here's my notional take on a unification plan;

- [ ] Add `gcloud.helpers.get_scoped_connection()`, which takes the connection class and a scopes list as arguments;  make each `gcloud.*._implicit_environ.get_connection` delegate to that helper (e.g., via `functools.partial`).
- [ ] Move the "project detection" logic from `gcloud.storage._implicit_environ` into `gcloud.helpers`.
- [ ] Consider how 'project' and 'dataset_id' should be related (e.g., does an app running on AppEngine / GCE use the same logic to determine its project ID for storage / pubsub purposes?) 
- [ ] Move the `_DefaultsContainer` up into `gcloud.helpers`, and make it generic;  instantiate it (subclassing only if *really* necessary) in each `gcloud.*._implicit_environ`.

@dhermes WDYT?

**Comment by dhermes** [comment]
I don't see `_DefaultsContainer` able to be generalized due to the dependence on package specific functions for lazy-loading.

The rest seems great.

RE: Project ID vs. App Engine App ID. We should ask someone with more knowledge of the current state of things. I think they are the same, but could be wrong.

App Engine apps also have a default bucket created for them: `<app-id>.appspot.com` (bucket names with periods can't usually be created)

**Comment by tseaver** [comment]
Re: `_DefaultsContainer`:  I (now) agree. When I moved the project stuff up into `gcloud._helpers`, I split apart the `_DefaultsContainer` class in `gcloud.storage._implicit_environ`:  each modules version knows only about the attributes relevant to its own functions.

**Comment by dhermes** [comment]
@tseaver What's the status on this?

**Comment by tseaver** [comment]
I think that we are good, here:  the default project stuff is shared, as is the repeated connection stuff (via `get_scoped_connection`).
