### ISSUE TITLE
Drop `reload()` / `patch()` in testcases for no-longer-remote Bucket/Blob properties

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#778]
Ref:

https://github.com/GoogleCloudPlatform/gcloud-python/pull/769#discussion_r27420594
https://github.com/GoogleCloudPlatform/gcloud-python/pull/773#issuecomment-87799124

**Comment by tseaver** [comment]
Re #777:  Ships that cross in the night, I guess.

**Comment by dhermes** [comment]
Indeed!
