### ISSUE TITLE
Should we provide batching across services?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#796]
This was brought up by @squee1945 in https://github.com/GoogleCloudPlatform/gcloud-python/issues/557#issuecomment-90101833

> e.g., I can't batch a storage request together with a datastore request (please correct me if I'm wrong).

If we wanted to batch these together, the API might be pretty tricky, but could look like...

```python
with gcloud.Batch() as batch:
  batch.datastore.put(...)
  batch.storage.upload_file(...)
```

I'm not sure how much value this adds, but wanted to discuss it in a separate issue so that we can make a decision...

My vote is: :-1: -- I don't think the value offsets the cost.

/cc @squee1945 @dhermes @tseaver

**Comment by dhermes** [comment]
I think it's a bit worse even, it indicates that somehow the backends support grouped batching, but they don't. :-1: for me as well

**Comment by tseaver** [comment]
Note that the endpoint API URL for batching is:  https://www.googleapis.com/batch', which isn't visibly associated w/ storage.  I don't know if that endpoint is able to process sub-requests which point into other services.

**Comment by tseaver** [comment]
@dhermes, @jgeewax could we make every API-triggering method take an optional `connection` argument, which would override the bound / default connection for only that call?  Seems like that would be a useful pattern across all services;  it would also help mark those methods as being API/latency relevant.

**Comment by jgeewax** [comment]
I'm +1 to that idea.

Either way, closing this out as won't fix given we really don't want to batch across services.....
