### ISSUE TITLE
Out-of-order / repeated message delivery

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#797]
The [pubsub docs](https://cloud.google.com/pubsub/publisher) say:

> Although Pub/Sub usually delivers messages in order of publication, this is not guaranteed; it is  possible for subscriptions to receive messages out of order. For this reason, we suggest that you include sequence information in the message payload or attribute so that subscribers that need in-order messaging can implement logic to do so.

Do we need to provide support in the library for generating sequence / timestamp info?

**Comment by tseaver** [comment]
Note that I've actually seen out-of-order messages while working on #795 (it originally sent two messages, but they routinely arrived in reverse order).

**Comment by tseaver** [comment]
#809 addresses adding a `timestamp` field automatically to the `message.attributes`.  Addressing this issue completely might require adding some kind of subscriber-side help as well.

**Comment by tmatsuo** [comment]
Note that, if your publishers are distributed, you can not guarantee the correct order unless you have precise system clocks.

**Comment by tseaver** [comment]
We currently have an optional `timestamp_messages` parameter to `Topic.__init__`:  if it is True, then the topic adds a `timestamp` attribute to each message it publishes.  In #1623, @dhermes argues for removing this feature.
