### ISSUE TITLE
Error passing 'fields' to pubsub GET API for subscription

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#799]
```
$ tox -e regression --notest
GLOB sdist-make: /home/tseaver/projects/agendaless/Google/src/gcloud-python/setup.py
regression inst-nodeps: /home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/dist/gcloud-0.4.3.zip
___________________________________ summary ____________________________________
  regression: skipped tests
  congratulations :)
$ .tox/regression/bin/python regression/run_regression.py --package=pubsub
test_create_subscription (pubsub.TestPubsub) ... ERROR
test_create_topic (pubsub.TestPubsub) ... ok
test_list_subscriptions (pubsub.TestPubsub) ... ok
test_list_topics (pubsub.TestPubsub) ... ok
test_message_pull_mode_e2e (pubsub.TestPubsub) ... ERROR

ERROR: test_create_subscription (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/regression/pubsub.py", line 74, in test_create_subscription
    self.assertFalse(subscription.exists())
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression/lib/python2.7/site-packages/gcloud/pubsub/subscription.py", line 112, in exists
    query_params={'fields': 'name'})
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/regression/lib/python2.7/site-packages/gcloud/connection.py", line 293, in api_request
    raise make_exception(response, content)
gcloud.exceptions.BadRequest: 400 Invalid JSON payload received. Unknown name "fields": Cannot bind query parameter.
```

I omitted a similar failure in another test:  both are for a call to `subscription.exists()` where the expected value is False.

@dhermes this is the one I was working around in #794 

@jgeewax maybe tag w/ "google bug"?

**Comment by dhermes** [comment]
Whoa! @tmatsuo note that `fields` is in the [discovery doc][1], but does not actually work when used.

@tseaver Shall we "fix" be re-implementing your previous commit? (PS Good thing exception handling is finally working the way we want :))

[1]: https://www.googleapis.com/discovery/v1/apis/pubsub/v1beta2/rest

**Comment by tseaver** [comment]
Caused breakage in regression tests on master:

  https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/57382647

Interestingly, the second failure I saw does not appear there.  #heisenbug

**Comment by tseaver** [comment]
It would be nice to have confirmation that `fields` is not expected to be passed for non-existing subscriptions.  @tmatsuo can you comment?

**Comment by tmatsuo** [comment]
Actually it is the first time I'm aware of the `fields` query parameter.
@tseaver 
Let me confirm, does this succeed with existing subscription, and fail with non-existing subscriptions?

**Comment by tseaver** [comment]
@tmatsuo I just tweaked our regression test to avoid the call for non-existing subscription, and saw the same failure for an existing subscription.

**Comment by tmatsuo** [comment]
I think this is a bug within the new API infrastructure. I'll file a bug internally.

**Comment by tseaver** [comment]
I can provoke the 400 by supplying `name` in the `fields` input on the [try it page](https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/subscriptions/get)

**Comment by tmatsuo** [comment]
Thanks! Filed a bug with an id: 20091445 internally

**Comment by tmatsuo** [comment]
I got a response.

"""
Could you try "$fields" instead?
"""

Actually I don't like the answer, but could you try it as suggested, just to see if it works?

**Comment by tseaver** [comment]
Using `{"$fields": "name"}` as `query_params` prevents the 400.

**Comment by tmatsuo** [comment]
Thanks for confirming.

JFYI, if the fields -> $fields change is an official thing, we still need to fix bunch of things.
- API explorer shows "fields" query param and there is no way to override it.
- Documentations need to be updated
    - https://developers.google.com/discovery/v1/using
    - https://developers.google.com/discovery/v1/parameters

Do you have any opinions about it?

**Comment by dhermes** [comment]
-   It seems like a fix of something that wasn't broken.
-   The discovery document still says `fields`:

    ```json
    "fields": {
     "type": "string",
     "description": "Selector specifying which fields to include in a partial response.",
     "location": "query"
    },
    ```

-   Does the APIs Explorer even have an owner?
-   Note that @tseaver said the API accepted `fields` when the subscription existed and `$fields` when it did not.

**Comment by tseaver** [comment]
Changing it seems like a wrong choice to me:  it it just an unintended artifact of some implementation decision?

**Comment by tseaver** [comment]
@dhermes I couldn't reproduce that later (after cleaning out `.tox/regression`):  `fields` fails on both cases (try it in the Explorer and see for yourself).

**Comment by tmatsuo** [comment]
@tseaver 
I agree. Do you have access to the internal issue tracker? If so you can express your opinion there (I cc'd both of you).

**Comment by dhermes** [comment]
@tmatsuo I do not have access internally.

**Comment by tmatsuo** [comment]
Oh I see. I expressed my opinion there and keep you updated here (is this the right place?).

**Comment by dhermes** [comment]
Sure

**Comment by dhermes** [comment]
Closing this. Will re-open if it matters to us.

The pub/sub folks shouldn't break users expectations though :grinning:
