### ISSUE TITLE
Entity creation type safety

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-python#819]
Right now, if you create an entity like:

    e = datastore.entity.Entity(key, ('data'))

The unindexable properties will be 'd', 'a', or 't'. Obviously in this case the user meant to specify:

    e = datastore.entity.Entity(key, ('data',))

Perhaps the Entity constructor should verify that exclude_from_indexes is a list or tuple.

Here is the discussion where the user ran into this: https://groups.google.com/forum/#!topic/gcd-discuss/rqwF8CRdTAY

**Comment by dhermes** [comment]
Thanks for the pointer to the discussion! I'm torn on this.

Getting bit by passing in a string as an iterable is somewhat of a rite of passage in Python (as we saw, the user misunderstood the `('data')` syntax as being a way to create a tuple). By whitelisting `list` and `tuple` it rules out people that might want to pass in their own custom iterables. On the flipside, this is a really straightforward property so maybe we'd just suggest they pass in `list(custom_iterable)`.

**Comment by pcostell** [comment]
I'm not partial either way, just wanted to pass it on.

**Comment by dhermes** [comment]
Got it. Thanks.

@tseaver WDYT?

**Comment by pcostell** [comment]
One extra thought --

Maybe it should be an error if you provide properties to exclude_from_indexes that you never actually store in the entity. It could indicate bad application logic.

**Comment by dhermes** [comment]
When do we decide the `Entity` is "final"?

**Comment by pcostell** [comment]
In this instance probably on put.
