### ISSUE TITLE
Creating a new datastore.entity with a key name is a pain

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#82]
If I know I want to create a new Person named `jim`, it's a huge pain to get a handle on this entity.

What I would like to do:

```python
entity = dataset.entity(['Person', 'jim'])
entity['age'] = 80
entity.save()
```

What I currently have to do:

```python
key = Key.from_path(['Person', 'jim']).dataset(dataset)
entity = dataset.entity('Person').key(key)
entity['age'] = 80
entity.save()
```

This is a whole bunch of extra wiring I really shouldn't need to deal with.

**Comment by dhermes** [comment]
#488 combined with the new ease of creating `Key` via #451 will make this possible. Will close out #484 when complete.

Now construction easy via:
```python
datastore.set_default_dataset()
entity = Entity(key=Key('Person', 'jim'))
entity['age'] = 80
```

Future PRs may even allow specifying `age=80` in the constructor.
