### ISSUE TITLE
Add optional 'connection' parameter for any method that hits the wire

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#825]
From #796 

> @dhermes, @jgeewax could we make every API-triggering method take an optional connection argument, which would override the bound / default connection for only that call? Seems like that would be a useful pattern across all services; it would also help mark those methods as being API/latency relevant.

**Comment by dhermes** [comment]
Thanks for filing. That's the goal. Mentioned this in #728 and #632 but it's not really spelled out.

**Comment by tseaver** [comment]
## `datastore`

### Free API functions

- [x] `api.get`
- [x] `api.put`
- [x] `api.delete`
- [x] `api.allocate_ids`

### `batch.Batch` methods

(note that `Batch.__init__` takes a `connection`, handles fallback)

- [ ] `Batch.commit` 

### `dataset.Dataset` methods

(note that `Dataset.__init__` takes a `connection`, defaulting to None).

- [ ] `Dataset.get` (wraps `api.get`)
- [ ] `Dataset.put` (wraps `api.put`)
- [ ] `Dataset.delete` (wraps `api.delete`)
- [ ] `Dataset.batch` (`Batch` instance holds connection)
- [ ] `Dataset.transaction` (`Transaction` instance holds connection)

### `query.Query` methods

- [x] `Query.fetch` (handles fallback, passes connection to `Iterator`)

### `transaction.Transaction` methods:

(note that `Transaction.__init__` takes a `connection`, handles fallback via `Batch.__init__`)

- [ ] `Transaction.begin` 
- [ ] `Transaction.rollback` 
- [ ] `Transaction.commit` (delegates to `Batch.commit`).

## `pubsub`

### Free API functions

- [x] `api.list_topics`
- [x] `api.list_subscriptions`

### `subscription.Subscription` methods

- [x] `Subscription.from_api_repr`
- [ ] `Subscription.create` (uses `self.topic.connection`)
- [ ] `Subscription.exists` (uses `self.topic.connection`)
- [ ] `Subscription.reload` (uses `self.topic.connection`)
- [ ] `Subscription.modify_push_configuration` (uses `self.topic.connection`)
- [ ] `Subscription.pull` (uses `self.topic.connection`)
- [ ] `Subscription.acknowledge` (uses `self.topic.connection`)
- [ ] `Subscription.modify_ack_deadline` (uses `self.topic.connection`)
- [ ] `Subscription.delete` (uses `self.topic.connection`)

### `topic.Topic` methods:

(note that `Topic.__init__` takes a `connection`, handles fallback)

- [x] `Topic.from_api_repr`
- [ ] `Topic.create` (uses `self.connection`)
- [ ] `Topic.exists` (uses `self.connection`)
- [ ] `Topic.publish` (uses `self.connection`)
- [ ] `Topic.batch` (delegates to `_Batch` instance)
- [ ] `Topic.delete` (uses `self.connection`)

### `topic._Batch` methods:

- [ ] `_Batch.commit` (uses `self.topic.connection`, called from `__exit__` when batch used as a context manager)

## `storage`

### `_helpers._PropertyMixin` methods (inherited by `Blob` / `Bucket`)

- [ ] `_PropertyMixin.reload`
- [ ] `_PropertyMixin.patch`

### `acl.ACL` methods

- [ ] `ACL.reload` ("pure virtual", but could work w/ explict connection)
- [ ] `ACL.save` (ditto)
- [ ] `ACL.clear` (ditto)

### `acl.BucketACL` methods

- [ ] `BucketACL.reload` (uses `self.bucket.connection`)
- [ ] `BucketACL.save` (ditto)
- [ ] `BucketACL.clear` (ditto)

### `acl.BlobACL` methods

- [ ] `BlobACL.reload` (uses `self.blob.connection`)
- [ ] `BlobACL.save` (ditto)
- [ ] `BlobACL.clear` (ditto)

### Free API functions

- [x] `api.lookup_bucket`
- [x] `api.list_buckets` (handles fallback, passes connection to `_BucketIterator`)
- [x] `api.get_bucket`
- [x] `api.create_bucket`

### `batch.Batch` methods

(note that `Batch.__init__` takes a `connection`, handles fallback)

- [ ] `Batch._do_request` (uses `self._connection`)
- [ ] `Batch.finish` (delegates to `_do_request`;  called in `__exit__` when batch used as a context manager).

### `blob.Blob` methods

- [ ] `Blob.connection` property (delegates to `self.bucket.connection`)
- [x] `Blob.generate_signed_url`
- [x] `Blob.exists`
- [ ] `Blob.rename` (delegates to `self.bucket.copy_blob`)
- [ ] `Blob.delete` (delegates to `self.bucket.delete_blob`)
- [x] `Blob.download_to_file`
- [x] `Blob.download_to_filename`
- [x] `Blob.download_as_string`
- [x] `Blob.upload_from_file`
- [x] `Blob.upload_from_filename`
- [x] `Blob.upload_from_string`
- [ ] `Blob.make_public`

### `bucket.Bucket` methods

(note that `Bucket.__init__` takes a `connection`, does *not* handle fallback)

- [ ] `Bucket.connection` property
- [ ] `Bucket.exists`
- [ ] `Bucket.create`
- [ ] `Bucket.get_blob`
- [ ] `Bucket.list_blobs` (delegates to `_BlobIterator`, which uses bucket's `connection`)
- [ ] `Bucket.delete_blob`
- [ ] `Bucket.delete_blobs` (delegates to `delete_blob`)
- [ ] `Bucket.copy_blob`
- [ ] `Bucket.upload_file` (should die?)
- [ ] `Bucket.upload_file_object` (should die?)
- [ ] `Bucket.make_public` (delegates to `self.default_object_acl` and blobs)

**Comment by dhermes** [comment]
@tseaver Please re-open if this isn't covered (by `client`s now instead of `connection`s)
