### ISSUE TITLE
Pub/Sub surface doc title should be "Summary" or "Quick start" or "Overview" or "Common tasks"

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#828]
Doc in reference: http://googlecloudplatform.github.io/gcloud-python/latest/pubsub-surface.html

Any votes on the options (or new ideas) ?

- Summary
- Quick start
- Overview
- Common tasks

**Comment by tseaver** [comment]
How about, "Using the Pubsub API"?

**Comment by tseaver** [comment]
Or even just "Using the API"
