### ISSUE TITLE
pubsub.Topic.create() returns None?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#837]
I'd really like to write

```python
topic = pubsub.Topic('topic').create()
```

Looks like from the code we have today, that we don't return anything, so this won't work (topic will be `None` right here).

**Comment by dhermes** [comment]
We've spoken a bit about this. That is un-Pythonic.

For example, see from the standard library.

```python
>>> a = [1, -1, 10, 6]
>>> b = a.sort()
>>> b is None
True
>>> a
[-1, 1, 6, 10]
```

**Comment by jgeewax** [comment]
Being able to chain things nicely is un-Pythonic? Do we have more references to why this is a bad idea? Can you point me to that discussion?

It looks like Boto does this... See:

- http://boto.readthedocs.org/en/latest/ref/sqs.html#boto.sqs.connection.SQSConnection.create_queue
- https://github.com/boto/boto/blob/develop/boto/sqs/connection.py#L68

**Comment by dhermes** [comment]
Having been inside, `boto` is not a very Pythonic library. Method chaining is a JavaScript idiom, not Python.

**Comment by jgeewax** [comment]
That doesn't really answer things for me ... :(

I think the bigger issue is that I don't see a use for a `Topic` object that isn't 'created'. that is, what can I do with `topic = pubsub.Topic('name')` besides create it?

Would this method be better as a factory?

```python
topic = pubsub.Topic.create('topic-name')
```

or

```python
topic = pubsub.create_topic('topic-name')
```

?

**Comment by dhermes** [comment]
1.  Yeah I was going to point out `pubsub.create_topic('topic-name')`

1.  I'll let @tseaver speak on the design, but for us, the point of a method like `topic.create()` is to make it clear to the user when they are making an HTTP request and when they are just updating a local property of a `Topic` object.

    So they have the option of "functional" approach `pubsub.create_topic('topic-name')` or OO approach `topic.create()`

**Comment by jgeewax** [comment]
> Yeah I was going to point out pubsub.create_topic('topic-name')

Does that exist? I don't see it...

> the point of a method like topic.create() is to make it clear to the user when they are making an HTTP request and when they are just updating a local property of a Topic object.

Totally agree - I don't want to hide that a request is being made.

Wouldn't the two options go against the whole "one way to do things" idea?

**Comment by dhermes** [comment]
Indeed they would violate the [Zen of Python][1] "There should be one-- and preferably only one --obvious way to do it.". @tseaver has mentioned abolishing functions of the form

```python
top_level_package.verb_thing(args)
```

in favor of

```python
thing = top_level_package.Thing(...)
thing.verb(args)
```

[1]: https://www.python.org/dev/peps/pep-0020/

**Comment by jgeewax** [comment]
What's the reason for that ?

If we're going to go that way, I'd like to re-open the topic of enforcing all our methods to be chainable. I'd rather go the `package.verb_thing(args)` though....

**Comment by dhermes** [comment]
Closing this as #911 due to lost steam
