### ISSUE TITLE
datastore: keys_only query should return Keys?

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/gcloud-python#839]
I don't know the answer to that question, but I'd like to suggest so. It's what ```ndb``` [does](https://cloud.google.com/appengine/docs/python/ndb/queryclass#kwdargs_options). Right now, ```gcloud-python``` returns a key-only ```Entity```. It's a minor issue either way as the ```key``` is just one property away.

**Comment by tseaver** [comment]
-1 for having the return type vary based on arguments:  "queries return entities" is much easier to reason about than "queries return entities, except when they return keys."

**Comment by dhermes** [comment]
I'm -1 too.

@pdknsk WDYT about a separate method for keys only queries just like `datastore.get` and `datastore.get_multi`?

Also keep in mind #557 will be resolved someday.

**Comment by jonparrott** [comment]
-1 as well, it was surprising at first because I was used to ndb, but really, keys only is a projection and it definitely makes sense to have query/get/get_multi always return entities.

**Comment by dhermes** [comment]
Will re-open if @pdknsk weighs in.
