### ISSUE TITLE
DISCUSSION: Reduce amount of implicit magic

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#847]
See https://github.com/GoogleCloudPlatform/gcloud-python/pull/830/files#r29357515

**Comment by jgeewax** [comment]
(Still a draft, have to go to a meeting but wanted to put this out there...)

IMO, the goal here should be to support the implicit magic if users want it (and hell, for a lot of people it's what they have come to expect from App Engine), however support the explicit side of things as well.

**Disclaimer**: This conversation may very well bring us in a full circle... and I apologize if that happens.

Some thoughts:

1. `<module>.<method>()` calls (ie, `datastore.get(...)`) all would have a connection parameter.
1. If connection is None, we try to resolve it by looking to a default, potentially resolving it using magic.
1. Setting a default connection should have global effect (no per-module default connections).
1. If you don't want a global default connection, you should be able to easily create a connection and then use it like you would any other API (ie `pubsub_connection.create_topic('topic_name')`) (I'd expect this to be 'the recommended way' of doing things...)
1. A Connection object represents a combination of Credentials, a Project ID, and a transport, so a globally shared default connection implies a globally shared default project ID as well as credentials.
1. Connections should have classmethod factories for simplicity (ie, `from_environment_variable`, `from_path`, `from_p12`)

### Using an explicitly built connection object (not the module)

#### Auto detect project ID and credentials (aka, don't think about it)

```python
from gcloud import pubsub

pubsub_connection = pubsub.Connection()
pubsub_connection.create_topic('topic_name')
```

#### Auto detect the project ID but specify where to get credentials

```python
from gcloud import pubsub

pubsub_connection = pubsub.Connection.from_environment_variable('....')
pubsub_connection.create_topic('topic_name')
```

#### Auto detect the credentials but specify the project ID

```python
from gcloud import pubsub

pubsub_connection = pubsub.Connection(project='project_id')
pubsub_connection.create_topic('topic_name')
```

#### Specify both the project ID and the credentials

```python
import gcloud
from gcloud import pubsub
from gcloud.credentials import get_for_service_account_json

pubsub_connection = pubsub.Connection.from_environment_variable('....', project='project_id')
pubsub_connection.create_topic('topic_name')
```

### Using the module itself

#### Auto detect project ID and credentials (aka, don't think about it)

```python
from gcloud import pubsub
pubsub.create_topic('topic_name')
```

#### Auto detect the project ID but specify where to get credentials

```python
import gcloud
from gcloud import pubsub

gcloud.Connection.from_environment_variable('....').set_as_default()
pubsub.create_topic('topic_name')
```

#### Auto detect the credentials but specify the project ID

```python
import gcloud
from gcloud import pubsub

gcloud.Connection(project='project_id').set_as_default()
pubsub.create_topic('topic_name')
```

#### Specify both the project ID and the credentials

```python
import gcloud
from gcloud import pubsub
from gcloud.credentials import get_for_service_account_json

gcloud.Connection.from_environment_variable('....', project='project_id').set_as_default()
pubsub.create_topic('topic_name')
```

**Comment by jgeewax** [comment]
After our conversation yesterday, it seems like if our goal is to simplify the use of different "connection" objects we might be able to do this cleanly using the same type of pattern as we do with Batches by making the `Connection` object a context manager. This would make code look like:

```python
connection = ...  # Get a Connection object somehow.
connection2 = ...  # Get a Connection object somehow.

with connection:
    pubsub.create_topic('topic_name')

with connection 2:
    pubsub.create_topic('topic_name')
```

We still need to address the problem of "If I want to swap out credentials, it should be easy and simple" -- in other words "Getting a connection object somehow." should be straight forward assuming the two things I want to tweak are the credentials and the project ID.

More discussion on this soon...

**Comment by dhermes** [comment]
This is kind of a redundant issue at this point, given #816, etc.
