### ISSUE TITLE
Use gRPC for Pub/Sub, Datastore, and Logging when possible

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#851]
See: https://github.com/google/googleapis

- [ ] Pub/Sub
- [ ] Datastore

----

**PREVIOUS CONTENT**: Now that gRPC is open-source, I was wondering how much effort it might be to add it to gcloud-python as the transport layer. Currently, I believe it would be supported for the Datastore and PubSub services...

Obviously we'd have to look at package distribution (as pip install grpc has some extra dependencies) but it'd be cool to add support for this as I suspect we'd see better performance.

**Comment by tseaver** [comment]
I don't see any docs for it (either in the repo, or linked from the PyPI page).  I don't really have any notion of what its API would be like.

**Comment by dhermes** [comment]
I'd love to be stable on other things before. This screams of churn (though I don't have much faith in our transport layer, `httplib2`).

**Comment by mwitkow-io** [comment]
This would be lovely, but would probably require the Google API Frontend service to support gRPC in the first place.

**Comment by dhermes** [comment]
@nathanielmanistaatgoogle Would you have some time to chat about feasibility of using `gRPC` in a stable project?

**Comment by pcostell** [comment]
Just an FYI  for Datastore -- v1beta2 does not support grpc. The next Datastore release will, however the gcd tool will likely not support it in the short term.

**Comment by dhermes** [comment]
@pcostell Thanks for the heads up. When do you expect the next release to come out?

**Comment by pcostell** [comment]
We are pretty close, so hopefully soon.

**Comment by tmatsuo** [comment]
FYI, Cloud Pub/Sub will enable gRPC soon too.

**Comment by dhermes** [comment]
Great to hear from both. Will there be a formal announcement / something for us to look out for?

**Comment by pcostell** [comment]
Datastore will have an announcement, I'll make sure to file bugs against the gcloud-* libs to upgrade once it is ready.

**Comment by dhermes** [comment]
Awesome! Thanks

**Comment by tseaver** [comment]
All three APIs now use gRPC when available.
