### ISSUE TITLE
./google-cloud-sdk/install.sh throws error

### ISSUE THREAD

**Issue by charlesbclifford** [GoogleCloudPlatform/gcloud-python#867]
Not sure if this error thrown by install.sh is due to local installation of Python (brand new install of Fedora 22), or the install.sh

$  ./google-cloud-sdk/install.sh
Welcome to the Google Cloud SDK!
Traceback (most recent call last):
  File "/home/charles/./google-cloud-sdk/bin/bootstrapping/install.py", line 8, in <module>
    import bootstrapping
  File "/home/charles/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 17, in <module>
    import oauth2client.gce as gce
  File "/home/charles/google-cloud-sdk/bin/bootstrapping/../../lib/oauth2client/gce.py", line 26, in <module>
    from oauth2client import util
  File "/home/charles/google-cloud-sdk/bin/bootstrapping/../../lib/oauth2client/util.py", line 38, in <module>
    logger = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'

Any suggestions on clearing this up are appreciated.

**Comment by jgeewax** [comment]
It seems you've figured this one out -- any chance you could share what the solution was?

I'm just guessing that you might have a file called `logging.py` in your `PYTHONPATH` which was being picked up instead of the builtin logging library.

**Comment by charlesbclifford** [comment]
I am keeping a running log of all the steps to installing GCP SDK on Fedora
22.

There are a few critical prerequisite steps before installing gcloud-Python


On Sunday, May 10, 2015, JJ Geewax <notifications@github.com> wrote:

> It seems you've figured this one out -- any chance you could share what
> the solution was?
>
> I'm just guessing that you might have a file called logging.py in your
> PYTHONPATH which was being picked up instead of the builtin logging
> library.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-100640366>
> .
>


-- 
Charles B. Clifford
(720) 842-7251

**Comment by jgeewax** [comment]
Adding @rdayal (who works on the Cloud SDK).

**Comment by charlesbclifford** [comment]
Good, the more help the better. I'm just about done testing the BigQuery
loader. Once that is completed testing, then my build doc for Fedora 23
will be finished.

On Monday, May 11, 2015, JJ Geewax <notifications@github.com> wrote:

> Adding @rdayal <https://github.com/rdayal> (who works on the Cloud SDK).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-100932241>
> .
>


-- 
Charles B. Clifford
(720) 842-7251

**Comment by charlesbclifford** [comment]
Attached in the step-by-step guide for installing Google SDK on Fedora 22.
I hope that the guide will be of help to Google SDK and Python newbies like
myself. Please distribute the guide as you see fit.

On Mon, May 11, 2015 at 11:06 AM, Charles Clifford <
charlesbclifford@gmail.com> wrote:

> Good, the more help the better. I'm just about done testing the BigQuery
> loader. Once that is completed testing, then my build doc for Fedora 23
> will be finished.
>
> On Monday, May 11, 2015, JJ Geewax <notifications@github.com> wrote:
>
>> Adding @rdayal <https://github.com/rdayal> (who works on the Cloud SDK).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-100932241>
>> .
>>
>
>
> --
> Charles B. Clifford
> (720) 842-7251
>
>


-- 
Charles B. Clifford
(720) 842-7251

**Comment by jgeewax** [comment]
Hm @charlesbclifford : looks like e-mail attachments don't come through. Can you maybe put it on Google Drive or Dropbox and share the link here?

**Comment by charlesbclifford** [comment]
Will do, but that will happen later this afternoon. Right now I have to
figure out how to configure and build out a Container cluster.

On Tue, May 12, 2015 at 8:29 AM, JJ Geewax <notifications@github.com> wrote:

> Hm @charlesbclifford <https://github.com/charlesbclifford> : looks like
> e-mail attachments don't come through. Can you maybe put it on Google Drive
> or Dropbox and share the link here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-101301038>
> .
>



-- 
Charles B. Clifford
(720) 842-7251

**Comment by charlesbclifford** [comment]
Attached is the promised guide for installing Google SDK Python on a new
Linux/Fedora 22 host. There must be some additional required installation
steps since, because when attempting to download a blob as a file, an
AttributeError 'api_request' is being thrown. Also, the guide is a 1st
draft so reading it can be a bit rough in sections.
Thanks for your help with my previous issues. Much appreciated. I could not
have gotten this far without your help.

On Tue, May 12, 2015 at 8:32 AM, Charles Clifford <
charlesbclifford@gmail.com> wrote:

> Will do, but that will happen later this afternoon. Right now I have to
> figure out how to configure and build out a Container cluster.
>
> On Tue, May 12, 2015 at 8:29 AM, JJ Geewax <notifications@github.com>
> wrote:
>
>> Hm @charlesbclifford <https://github.com/charlesbclifford> : looks like
>> e-mail attachments don't come through. Can you maybe put it on Google Drive
>> or Dropbox and share the link here?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-101301038>
>> .
>>
>
>
>
> --
> Charles B. Clifford
> (720) 842-7251
>



-- 
Charles B. Clifford
(720) 842-7251

**Comment by dhermes** [comment]
Again, your e-mail attachments don't come through to GitHub.

**Comment by charlesbclifford** [comment]
What email address should I send the requested guide to.

On Friday, May 15, 2015, Danny Hermes <notifications@github.com> wrote:

> Again, your e-mail attachments don't come through to GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-102412852>
> .
>


-- 
Charles B. Clifford
(720) 842-7251

**Comment by dhermes** [comment]
As @jgeewax said

> Can you maybe put it on Google Drive or Dropbox and share the link here?

**Comment by rdayal** [comment]
@stephenmw

**Comment by stephenmw** [comment]
You can also post the guide to the Cloud SDK google group https://groups.google.com/forum/#!forum/google-cloud-sdk

**Comment by charlesbclifford** [comment]
I have just posted the guide, in the Issues section of the Cloud SDK Google
group. It is a bit rough around the edges, but it has been tested on Fedora
22, Debian and CentosOS.

Once again thanks for you help, and I trust once this guide is edited
beyond its draft form, may prove helpful to others in the community.

On Thu, May 21, 2015 at 4:59 PM, Stephen Weinberg <notifications@github.com>
wrote:

> You can also post the guide to the Cloud SDK google group
> https://groups.google.com/forum/#!forum/google-cloud-sdk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/867#issuecomment-104444724>
> .
>



-- 
Charles B. Clifford
(720) 842-7251

**Comment by stephenmw** [comment]
Have you tried following the official methods? There are two sets explained here: https://cloud.google.com/sdk/.

1. run curl https://sdk.cloud.google.com | bash
2. download google-cloud-sdk.zip or google-cloud-sdk.tar.gz, unpack it, and launch the ./google-cloud-sdk/install.sh script.

The one thing that these instructions are missing is installing python2.7 when it is not the default. We are working on fixing it, but until then, exporting the CLOUDSDK_PYTHON environment variable is useful. This is necessary when dealing with CentOS 6.

I tested installing via the curl method on a fedora 22 beta 3 live cd and it worked fine.
