### ISSUE TITLE
pip install gcloud throws gcc error on Fedora 22

### ISSUE THREAD

**Issue by charlesbclifford** [GoogleCloudPlatform/gcloud-python#868]
Just installed Fedora 22, and executed yum groupinstall 'Development Tools' 

When I run 'pip install gcloud' it throws the following error:

building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o
    src/MD2.c:31:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Lho9Ge/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SlocM3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Lho9Ge/pycrypto

Any suggestions for a work around are appreciated.

**Comment by jgeewax** [comment]
Did you try `yum install pycrypto` ?

(Reference:
http://stackoverflow.com/questions/11861846/error-in-installing-pycrypto-2-3-on-fedora-15
)

**Comment by charlesbclifford** [comment]
Installing pycytpto solved the pip install gcloud problem. Thank you, much appreciated.

**Comment by dhermes** [comment]
Also missing `Python.h` is a sign you don't have `python-dev` installed. FWIW `pip install` is preferred over `yum install` (or `apt-get install`)l
