### ISSUE TITLE
Solicit some dev exp feedback about config / auth

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#871]

**Comment by tseaver** [comment]
@jgeewax I'd like to propose asking @mcdonc (one of my partners at Agendaless) to do a four-hour "outside" review of the APIs, and offer a recommendation.  He made a well-liked [presentation at PyCon 2013 on API design](https://github.com/mcdonc/apidesign/blob/master/presentation.rst), and might provide some useful insight.

**Comment by dhermes** [comment]
This died on the vine

**Comment by jonparrott** [comment]
You can ping me and @waprin for devrel review, as we're working on a series of tutorials for python on GCP (similar to [these for node](https://cloud.google.com/nodejs)).

So far, we've only explored "implicit" configuration (app default credentials), but we can explore other methods too.

**Comment by dhermes** [comment]
@jonparrott This was filed before we had #861 and before the clients issue was resolved.
