### ISSUE TITLE
Travis regression tests are being run when they shouldn't be

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#874]
See:
https://github.com/GoogleCloudPlatform/gcloud-python/pull/873
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/62434732

Also related:
https://github.com/google/oauth2client/pull/174

**Comment by dhermes** [comment]
It looks like the `TRAVIS` environment variables are not being set.

Running `env | grep -i travis` we find only

```
VIRTUAL_ENV
PATH
PWD
```

Though the [ci-environment][1] is expected to have

```
TRAVIS=true
TRAVIS_BRANCH
TRAVIS_BUILD_DIR
TRAVIS_BUILD_ID
TRAVIS_BUILD_NUMBER
TRAVIS_COMMIT
TRAVIS_COMMIT_RANGE
TRAVIS_JOB_ID
TRAVIS_JOB_NUMBER
TRAVIS_PULL_REQUEST
TRAVIS_SECURE_ENV_VARS
TRAVIS_REPO_SLUG
TRAVIS_OS_NAME
TRAVIS_TAG
```

[1]: http://docs.travis-ci.com/user/ci-environment/

**Comment by dhermes** [comment]
Getting a list of every single environment variable set, we [see][1] it's quite short:

```
python -c "import os; print '\n'.join(os.environ.keys())"
_
SHLVL
VIRTUAL_ENV
PWD
PYTHONHASHSEED
PATH
```

[1]: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/62440140

**Comment by tseaver** [comment]
I believe this is actually due to [tox 2.0.x](https://testrun.org/tox/latest/changelog.html):

> (new) introduce environment variable isolation: tox now only passes the PATH and PIP_INDEX_URL variable from the tox invocation environment to the test environment and on Windows also SYSTEMROOT, PATHEXT, TEMP and TMP whereas on unix additionally TMPDIR is passed. If you need to pass through further environment variables you can use the new passenv setting, a space-separated list of environment variable names. Each name can make use of fnmatch-style glob patterns. All environment variables which exist in the tox-invocation environment will be copied to the test environment.

**Comment by dhermes** [comment]
Yay!

Thanks @tseaver
