### ISSUE TITLE
Add language switcher drop-down to landing page

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#885]
The other guys (ie http://googlecloudplatform.github.io/gcloud-node/#/) link to us on their landing page, might be nice to return the favor.

**Comment by ludoch** [comment]
That would be needed for all the runtimes to be consistent. Changing runtimes from there should in fact not induce UI/css style difference.

**Comment by jgeewax** [comment]
@ludoch : That makes the assumption that all of the libraries follow the exact same styling. Go and Java, (I believe, as of now) don't. I think it's a reasonable ask that the site in gcloud-python has the dropdown, but we can debate the others later on in their respective repositories.

**Comment by dhermes** [comment]
Which ones are public and can be linked to? Shouldn't more than just Ruby + Python + Node be linked?

**Comment by jgeewax** [comment]
Right now, Node + Ruby + Python are linkable. We have to get Java and Go into a linkable state before we can add them.
