### ISSUE TITLE
Query order argument incorrectly uses a string as an iterable type. 

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-python#887]
When querying an empty dataset that is empty with a sort order, for example:

```python
query = datastore.Query(kind='Book', order='title')
it = query.fetch(limit=limit, start_cursor=cursor)
entities, more_results, cursor = it.next_page()
```

It raises an exception:
```
PreconditionFailed: 412 no matching index found.
```

Once you create an entity in the dataset, the error disappears. It reappears when you delete all entities.

gcloud-node doesn't suffer from the same problem, as this just returns an empty array for an empty dataset:
```javascript
var q = ds.createQuery([kind])
      .limit(limit)
      .order('title')
      .start(token);
```

**Comment by dhermes** [comment]
1. In your snippet where did you get a cursor if nothing exists?
1. Is it a 419 or 412?
1. Is this an issue for libraries or the datastore eng. folks? I.e. should the behavior change on backend.
1. Is node swallowing the 412 status code from the backend? Isn't that a bad thing?

**Comment by jonparrott** [comment]
1. Cursor is None in this case.
2. 412, title was a typo.
3. Not sure.
4. I couldn't find any evidence of this in the source of gcloud-node.

**Comment by dhermes** [comment]
Well 3 and 4 should be resolved. Regarding 4, we don't make exceptions for status codes unless the backend gives a bad response (outside of 2xx range). So the theory here would be that node and python libraries create the requests in a different way?

**Comment by jonparrott** [comment]
Hmm, seems my assumption was wrong: This occurs regardless of if there are items in the dataset or not. Order doesn't seem to be working. 

Is this the proper syntax?

```python
query = datastore.Query(kind='Book', order='title')
```

**Comment by dhermes** [comment]
Yeah. How are you setting the dataset ID and connection? Using latest library version? Include stacktrace?

**Comment by dhermes** [comment]
We can screenshare if it'll speed things up.

**Comment by jonparrott** [comment]
Actually I found the problem.

The right synxtax is ``order=['title']`` not ``order='title'``. I'm guessing that since it expects a sequence, it was trying to sort on indexes ``['t', 'i', 't', 'l', 'e']`` which of course don't exist. Would it be to hard to make this accept single and list values?

**Comment by dhermes** [comment]
D'oh! I must retract my previous "yeah". Today in "maintainer doesn't understand how to use library". WAT!

@pcostell filed a very similar #819 and I was torn on this since Python encourages using lots of different types of iterables. Rather than putting `str` in a blacklist of iterable types, I'm going to vote we use a whitelist of `tuple` and `list` to avoid this in the future (I HATE type-checking inputs, but the issues speak for themselves, still crying inside a little, my fault for falling in love with Python).

**Comment by jonparrott** [comment]
Haha, I think it speaks volumes that both of us missed this *twice* in the code above. I agree that using a whitelist for (list, tuple) is the best way to go here.

Thanks!

**Comment by jonparrott** [comment]
Updated the title to better fit what the bug really is.

**Comment by dhermes** [comment]
Thanks
