### ISSUE TITLE
Move gcloud.storage.iterator into gcloud's common package

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#90]
We'll need this for Cloud DNS in the ManagedZones.list method (https://developers.google.com/cloud-dns/api/v1beta1/managedZones/list)

**Comment by dhermes** [comment]
Closing. We'll address this if / when it comes up, but YAGNI for now.

**Comment by dhermes** [comment]
Relevant again due to #933.
