### ISSUE TITLE
Not possible to set the datastore namespace globally.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-python#902]
Currently, ``gcloud.datastore.set_defaults`` lets you set the default dataset id, but doesn't let you set the default namespace. This means to use a namespace you have to be meticulous about setting in in every query, key, etc. 

It'd be much easier if we are able to set the namespace at the dataset or connection level.

**Comment by dhermes** [comment]
Thanks @jonparrott 

I had an [eye on this][1] a while back:

```
    In the future we will likely enable methods like

    - set_default_namespace
```

just haven't got to it. Given the discussion in #891 I'll hold off on fixing this until a client / `Dataset` approach is in place.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/3e86aaed3c7e192a17d9b790f90a41cc2b7baa6a/gcloud/datastore/__init__.py#L81-L83

**Comment by jgeewax** [comment]
This is tricky -- I don't think `set_default_namespace` fixes the entire issue. I think it might be worth discussing another thin-wrapper like we did for `Dataset`, so the code we might write would be...

```python
client = datastore.Client()
dataset = datastore.dataset('my-dataset-id')
namespace = dataset.namespace(customer_namespace_id)
company = namespace.get(namespace.Key('Company', 'google'))
```

Note that `dataset` wouldn't be required if you have the default set:

```python
client = datastore.Client()
namespace = client.namespace(customer_namespace_id)
company = namespace.get(namespace.Key('Company', 'google'))
```

**Comment by dhermes** [comment]
When people use a namespace, they typically (in my experience, an overwhelming majority of the time) do it for an entire feature / section of a codebase, so

```
d = Dataset('foo', namespace='bar')
```

would be in one team's production code while

```
d = Dataset('foo', namespace='baz')
```

would be in another's.

This seems much more reasonable than having 3 classes to handle this scenario

```
Client -> Dataset -> Namespace
```

**Comment by jgeewax** [comment]
I like that. So the code an app would have would effectively be:

```python
namespace = get_current_subdomain()
d = client.dataset('foo', namespace=namespace)
d.get(d.Key(...))
```

**Comment by dhermes** [comment]
Yes.

**Comment by jonparrott** [comment]
This was resolved by moving to clients instead of having global methods.

**Comment by dhermes** [comment]
:+1:
