### ISSUE TITLE
Ensure Python 3 support

### ISSUE THREAD

**Issue by aliafshar** [GoogleCloudPlatform/gcloud-python#91]
Let's not be that guy.

Though our crypto dependencies might make this non-trivial.

**Comment by tseaver** [comment]
Assuming we go forward with requiring `protobuf 3.0.0-alpha-1` or later, we have already merged our own changes to support Python 3.3 / 3.4, but are blocked on officially supporting them by https://github.com/google/oauth2client/issues/125 (fix merged but not yet released).

**Comment by tseaver** [comment]
#676 changes the `regression3` environment to use a checkout of `oauth2client` until a release is available which fixes google/oauth2client#125

**Comment by dhermes** [comment]
Wooooooo! Closed by #820

**Comment by dhermes** [comment]
As for concerns about readiness of `protobuf 3.0.0-alpha-1`, see google/protobuf#250
