### ISSUE TITLE
Get a subscription from a topic

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#912]
In pubsub-usage.rst we have:

```python
client = pubsub.Client()
topic = client.topic('topic-name')
sub = pubsub.Subscription('sub-name', topic)
```

I think we should consider changing this to

```python
client = pubsub.Client()
topic = client.topic('topic-name')
sub = topic.subscription('sub-name')
```

**Comment by dhermes** [comment]
I am :+1: 

@tseaver WDYT?

**Comment by tseaver** [comment]
Given that we advertise `client.topic()` as the "normal" way to instantiate `Topic`, this would be more consistent.

**Comment by dhermes** [comment]
@tseaver I'm trying to incorporate this into #910 and Pylint is not happy about `cylic-import`. I even move the imports from global down to the methods which use them as

```python
# In topic.py
        # pylint: disable=cyclic-import
        from gcloud.pubsub.subscription import Subscription
        # pylint: enable=cyclic-import
# In subscription.py
        # pylint: disable=cyclic-import
        from gcloud.pubsub.topic import Topic
        # pylint: enable=cyclic-import
```

and it still complains.

Thoughts?

**Comment by dhermes** [comment]
Ended up solving by factoring out the behavior in the `from_api_repr` factories into a shared helper library.
