### ISSUE TITLE
pubsub can't infer a connection when running locally.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-python#916]
When running locally with ``gcloud auth`` providing application default credentials, pubsub is unable to infer a connection, so this will fail:

```python
import pubsub
pubsub.set_default_project('my-project-id')
topic = pubsub.Topic('my-topic')
topic.publish(...)
```

with ``EnvironmentError: Connection could not be inferred.``

The fix is to set an explicit connection using adc:
```python
credentials = GoogleCredentials.get_application_default()
pubsub.set_default_connection(pubsub.Connection(credentials))
```

However, storage and datastore do not have this issue. It seems unnecessarily to do this just for pubsub.

**Comment by dhermes** [comment]
@jonparrott This is a known issue, but becomes moot via #910

**Comment by jonparrott** [comment]
Gotcha. Subscribed to #910 and will keep an eye on it.

**Comment by dhermes** [comment]
Yeah. After #861 it's very possible that `_implicit_environ` will all be removed and you'll need to create an explicit client. However, the constructors will have nice defaults just like `set_default_*` do.

**Comment by dhermes** [comment]
#910 made this moot.

**Comment by jonparrott** [comment]
confirmed, the new client method only needs the project id. Thanks!
