### ISSUE TITLE
datastore: Query does not allow inequality filter on __key__ property.

### ISSUE THREAD

**Issue by vinays** [GoogleCloudPlatform/gcloud-python#917]
Datastore query raises a ValueError for inequality(non-equality to be correct) operators on `__key__` property. 
https://github.com/GoogleCloudPlatform/gcloud-python/blob/3e86aaed3c7e192a17d9b790f90a41cc2b7baa6a/gcloud/datastore/query.py#L223

According to Google Cloud Datastore documentation inquality operators on `__key__` property are supported, and should not raise exception.
https://cloud.google.com/datastore/docs/concepts/queries#Datastore_Key_filters

It is a critical part of our data-model.

**Comment by vinays** [comment]
For those who are facing the same issue; Workaround is to pass filters for `__key__` property at the time of query construction.
Example:
Instead of:
```python
query = datastore.Query('Kind')
query.add_filter('__key__', '>=', datastore.Key('Kind', '<startname>'))
query.add_filter('__key__', '<', datastore.Key('Kind', '<endname>'))
entities = query.fetch()
```
Use:
```python
start_key = datastore.Key('Kind', '<startname>')
end_key = datastore.Key('Kind', '<endname>')
queries = datastore.Query('Kind', filters=[('__key__', '>=', start_key), ('__key__', '<', end_key)])
entities = query.fetch()
```

**Comment by dhermes** [comment]
Thanks @vinays 

I'm not sure why we limit in

```python
        if property_name == '__key__':
            if not isinstance(value, Key):
                raise ValueError('Invalid key: "%s"' % value)
            if operator != '=':
                raise ValueError('Invalid operator for key: "%s"' % operator)
```

It also points out that the initial filters from the constructor aren't being verified.

----

I really appreciate it and will be making a fix ASAP!

**Comment by vinays** [comment]
(thumbsup) @dhermes thanks for quick response and fix.

**Comment by dhermes** [comment]
:+1:
