### ISSUE TITLE
[Documentation Issue] Function/class name CSS is not easy to distinguish

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/gcloud-python#925]
Page Name: gcloud-api
Release: 0.6.0

Picking out the function names and class names is hard.  In the docs, those names are in the same gray text as the rest of the doc.  Making them bold and black would help me a lot.

**Comment by dhermes** [comment]
Thanks!

**Comment by dhermes** [comment]
Closing this since CSS will be part of shared docs.

/cc @jgeewax
