### ISSUE TITLE
Magically take care of efficient discovery doc retrieval, please.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/gcloud-python#927]
It's easy to post an app on app engine that makes too many calls to the discovery doc service and gets throttled.  I think the code in this library will suffer the same fat.  More details here:

https://cloud.google.com/appengine/articles/efficient_use_of_discovery_based_apis

**Comment by dhermes** [comment]
@SurferJeffAtGoogle Thanks for pointing that out. I am the author of that document :)

We don't use discovery docs (at least not yet), but will keep an eye out! Thanks

**Comment by SurferJeffAtGoogle** [comment]
Cool.  Thanks!
