### ISSUE TITLE
[Documentation Issue] Low contrast text is hard to read.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/gcloud-python#928]
Page Name: _modules/gcloud/pubsub/topic
Release: 0.6.0

A lot of the text is dark gray on top of a light gray background.  The low contrast makes it hard to read.  Black and white would be easier to read.

**Comment by dhermes** [comment]
Closing this since CSS will be part of shared docs.

/cc @jgeewax
