### ISSUE TITLE
Ditch apitools and implement it ourselves

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#935]
After a quick discussion in today's standup, we decided to just implement the small feature-set from `apitools` ourselves. 

Main reasons
- Dead library
- No docs
- Small feature set used by us

/cc @craigcitro

**Comment by craigcitro** [comment]
:+1:

**Comment by dhermes** [comment]
I think it's worth tackling #909 directly after doing this.

**Comment by tseaver** [comment]
Re-created as #1186.
