### ISSUE TITLE
"503 Backend Error" when connecting to App Engine local datatstore

### ISSUE THREAD

**Issue by nlokare** [GoogleCloudPlatform/gcloud-python#947]
There doesn't appear to be any documentation on how to connect a local compute engine application to a local app engine datastore.

`datastore.set_default_dataset_id('dev~myapplicationid')` causes a `ServiceUnavailable: 503 Backend Error`

**Comment by dhermes** [comment]
@nlokare You mean a local `gcd` application?

You can set it [via the `DATASTORE_DATASET`][1] environment variable (we need docs for that, thanks for pointing out).

To [point to the correct server][3], you need to set the [DATASTORE_HOST][2] environment variable.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/b975d9cf81c177f38336e4d3ce1fecc7eb692ad3/gcloud/datastore/_implicit_environ.py#L30
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/b975d9cf81c177f38336e4d3ce1fecc7eb692ad3/gcloud/datastore/connection.py#L28
[3]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/b975d9cf81c177f38336e4d3ce1fecc7eb692ad3/gcloud/datastore/connection.py#L55-L57

**Comment by nlokare** [comment]
@dhermes Thanks for the feedback. I followed the directions in the documentation you linked to, but I appear to have trouble connecting still. If my app engine application is running on localhost:8080 and my flask app is running on localhost:5000. What's the correct values for the environment variables you mentioned above?

I logged the request URI in the _request function in gcloud/datastore/connection.py which is "http://localhost:8080/datastore/v1beta2/datasets/dev~my--appengine-id/runQuery" and now I am getting a GCloudError: 302

Any help would be greatly appreciated. Thanks

**Comment by dhermes** [comment]
So are you running `gcd` or a local App Engine app via `dev_appserver`?

**Comment by nlokare** [comment]
@dhermes I am running a local app engine application through dev_appserver on port 8080 and then a flask app on a local gcd running on port 5000. I am having trouble configuring the flask app to connect to my local app engine datastore.

**Comment by dhermes** [comment]
Why do you have both of them running? You can run a flask app with `dev_appserver`.

- The datastore associated with the app run through `dev_appserver` cannot be accessed with this library because that backend has no protobuf API (or any public API for that matter)
- The [GCD][1] backend can be communicated with via my previous comments. If the `gcd` server is running on port 5000, use `localhost:5000`. If the flask app is running on port 5000, you still need to determine which port the `gcd` server is running on.

[1]: https://cloud.google.com/datastore/docs/tools/

**Comment by nlokare** [comment]
Sorry for the misunderstanding. 

In production and staging, I have an App Engine application and a Flask app on Compute Engine using the same datastore. However, I cannot replicate this configuration during local development.

Essentially, my App Engine application makes requests to the Compute Engine app, which then accesses the data it needs from NDB (our Compute Engine app does the heavy lifting, while App Engine, which handles the business logic, passes along the data Compute Engine needs to query in NDB via a POST request). 

This configuration is easily set up on production, but there is no way to do so during development. This is a pretty important feature for us, as we are building a complex application using this integrated architecture and it makes our workflow much more productive to have this work in a local environment.

Thanks again.

**Comment by nlokare** [comment]
@dhermes Is there a way through the gcd tool to connect both applications to the same local datastore?

**Comment by dhermes** [comment]
@nlokare Thanks. I was just in the process of writing about your second question

@pcostell Is it possible to hook up `gcd` as the datastore for an app run with `dev_appserver`?

From

https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/21
http://stackoverflow.com/a/21129453/1068170

it's unclear how one might do such a thing.

**Comment by pcostell** [comment]
Unfortunately there isn't support for that right now. We are working to unify the two backends but right now gcd and dev_appserver have two entirely different Datastore stacks.

**Comment by nlokare** [comment]
@dhermes @pcostell Thanks for clarifying, guys. Looking forward to the version that unifies the two!

**Comment by dhermes** [comment]
@pcostell Maybe it will be moot if we are able to unify some of the GAE RPC code from `ndb` into `gcloud-python`.

**Comment by pcostell** [comment]
That may work, but may be less than optimal. It would mean in development you'd have to run `gcloud-python` inside an App Engine app. the App Engine runtime plays lots of gross games with python -- I'd prefer if users could run a local Datastore service without having to mess with any of that stuff.

**Comment by dhermes** [comment]
@pcostell I didn't mean we'd disable the current support of hitting a local `gcd` instance, just that users who wanted fast code in GAE could test locally with `dev_appserver`. The desire for fast code in GAE necessitates us using a the GAE RPCs when available, right?

**Comment by pcostell** [comment]
Ah yes -- This would definitely be good for testing running `gcloud-python` inside of App Engine.

But it sounds like the use case you want is:

gcloud-python (outside GAE) ----> Local Datastore <---- App Engine app in dev_appserver

In this case, you don't want to force the `gcloud-python` code to run inside a dev_appserver since it prevents you from doing other things (like including SWIG libraries that aren't allowed inside GAE).

**Comment by dhermes** [comment]
Yeah that is somewhat separate. @nlokare will be most-helped by allowing a `gcd` backend to work with `dev_appserver`.

**Comment by nlokare** [comment]
@pcostell @dhermes The scenario that @pcostell illustrated is exactly what we are looking for.

**Comment by dhermes** [comment]
@pcostell How is the unification of the `gcd` and `dev_appserver` backends coming?

RE:

>  We are working to unify the two backends but right now gcd and dev_appserver have two entirely different Datastore stacks.

----

PS I'm doing a bug sweep. Sorry if it's annoying.

**Comment by pcostell** [comment]
There are several complications due to the need to install java to run gcd (whereas unnecessary if you are running the dev_appserver with a non-java app). But it's still on our radar as something important to do.

**Comment by dhermes** [comment]
What do you think I should do about this issue? There's not really anything we can act on.

**Comment by pcostell** [comment]
If you'd like you can open an issue on
GoogleCloudPlatform/google-cloud-datastore and close this as a dup of that
one.

**Comment by dhermes** [comment]
GoogleCloudPlatform/google-cloud-datastore#21 is already there

Closing out
