### ISSUE TITLE
Should we ship tests with our PyPI package

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#962]
Currently we just [send the whole `gcloud` directory][1]

```
graft gcloud
```

Should we also

```
global-exclude ^test_*.py$
```

@tseaver You are the resident packaging expert, so I'd love to hear what you have to say.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/bb25b9e924c12c648c3b5ac50d5bdc18409b2a5a/MANIFEST.in#L2

**Comment by tseaver** [comment]
I generally prefer to leave the tests in-place, to allow users to verify their installations.

**Comment by dhermes** [comment]
I've never heard of anyone checking an installation. I'd imagine anyone paranoid enough to do that would just check out the source and install from there via `python setup.py`.

**Comment by jgeewax** [comment]
I haven't seen it either -- however do we have a lot to lose by just tossing that in there?

If it's not really a size issue or anything like that, then I don't see an issue with including them...

**Comment by dhermes** [comment]
SGTM
