### ISSUE TITLE
Make dropdown inside the docs to link to "inside the docs" for other languages

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#966]
The dropdown you see here: https://googlecloudplatform.github.io/gcloud-python/latest/, when switching, links to the other-language-equivalent of http://googlecloudplatform.github.io/gcloud-python/

Could we have it link inside the docs of those other languages? 

ie:

Node: http://googlecloudplatform.github.io/gcloud-node/#/docs
Ruby: (we don't have this link yet, see https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/183)

**Comment by dhermes** [comment]
Keeping an eye on GoogleCloudPlatform/gcloud-node#702 too. Added Ruby to main page, forgot to do it within docs.

----

Can you elaborate by what you mean inside? Like to the specific API or service doc?

If we did this, it seems it would be very brittle. If any of the libraries changed the way their links work, it would break the others unintentionally.

**Comment by blowmage** [comment]
The Ruby URL should be http://googlecloudplatform.github.io/gcloud-ruby/docs/latest
