### ISSUE TITLE
Protobufs Dependencies Prevents Vendoring gcloud-python on GAE

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/gcloud-python#969]
GAE requires that you vendor all libraries within the sandbox, pip install -r requirements.txt -t lib/ is the current recommended approach. When you do this with gcloud-python as a dependency, it includes a package named google which contains the protobuf dependency. The problem is that you _also_ need to have the AppEngine SDK on your path which is also in a package named google, so if you put GAE first on your path, gcloud-python will fail to import protobufs, and if you put lib/ first, you can't import appengine SDK libs.

I think @jonparrott might have some more thoughts on how to resolve this (namespaced packages?)

**Comment by jonparrott** [comment]
namespaced packages would require modifications to both protobuf and some (probably crazy) changes to the GAE SDK's sandbox importer.

My question is whether or not gcloud-python is targeting GAE (sandboxed), and if so, what's the recommended way around this?

**Comment by dhermes** [comment]
@jonparrott and I chatted about getting `gcloud` [to work on GAE][1] awhile back

In particular, the [hack][2] for the `google` namespace is a bit of a pain, but not too big a deal.

Note that

1. We don't own the `protobuf` library (`google.protobuf`)
1. We need it to deal with protobuf services (datastore in this case). GAE users likely will be happy to just use `ndb` or `db`, which would mean they didn't need  the `gcloud.datastore` sub-package.
1. The `google` namespace makes me sad

[1]: https://github.com/dhermes/test-gcloud-on-gae
[2]: https://github.com/dhermes/test-gcloud-on-gae/blob/8a850fb8b5676ca03e07c4f9dcfba5efb8c77b0a/application/appengine_config.py#L11-L15

**Comment by waprin** [comment]
Ah ok, well thanks for the hacktastic solution.

**Comment by dhermes** [comment]
Indeed. We should all thank @simon-weber for writing
https://www.simonmweber.com/2013/06/18/python-protobuf-on-app-engine.html

Are we a go to close this out or is this something worth pursuing?

**Comment by jonparrott** [comment]
I'm good to close it out. That hack is both inspiring and depressing.

**Comment by dhermes** [comment]
:smile: :+1:

**Comment by simon-weber** [comment]
Glad I could help :grinning:

**Comment by jonparrott** [comment]
This strangely appears to be working without the hack... am I going crazy?

**Comment by dhermes** [comment]
Yes you're crazy :grinning:

But seriously it wouldn't be an issue if you never imported datastore. Care to give more details?

**Comment by jonparrott** [comment]
I forked [the flask skeleton](https://github.com/GoogleCloudPlatform/appengine-python-flask-skeleton), added pycrypto in app.yaml, added ``gcloud==0.7.1`` in requirements.txt, ran ``pip install -t lib -r requirements.txt``, and made main.py look like this:

```python
from flask import Flask
app = Flask(__name__)

from google.appengine.api import users
from gcloud import datastore
from google.appengine.api import memcache
import google

print dir(google)
# ['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'appengine', 'net', 'protobuf']

@app.route('/')
def hello():
    """Return a friendly HTTP greeting."""
    ds = datastore.Client()
    e = datastore.Entity(key=ds.key('test'))
    e['something'] = '123'
    ds.put(e)
    entities = list(ds.query(kind='test').fetch(10))
    return "User: {}\nEntities: {}".format(
        users.get_current_user(),
        entities
    ), 200, {'Content-Type': 'text/plain'}
```

Isn't this supposed to implode? It's working fine.

**Comment by dhermes** [comment]
Maybe `google.protobuf` ships with the SDK now? Is this in prod or locally?

**Comment by dhermes** [comment]
I just checked on an old app that had an interactive console, it's not in production GAE

**Comment by jonparrott** [comment]
Locally and in production. I was surprised to see it work locally, I was downright confused to see it run in production.

**Comment by jonparrott** [comment]
``google.protobuf`` gets installed transitively with ``gcloud``. It's ``google/__init__.py`` contains a namespace declaration, but the GAE SDK's ``google/__init__.py`` does not.

**Comment by dhermes** [comment]
How does the `gcloud` SDK change how production imports work? Are you using standard GAE or VM runtimes or container engine?

**Comment by jonparrott** [comment]
Standard runtime, though it appears to work with the VM runtime as well.

**Comment by dhermes** [comment]
When you `import google.protobuf`, what is `google.protobuf.__file__`? (Maybe I need to re-deploy that test app with the interactive console to actually see if things have changed.)

**Comment by jonparrott** [comment]
```
google.protobuf.__file__: /base/data/home/apps/s~redacted/20150831t093628.386825960903115845/lib/google/protobuf/__init__.pyc
google.appengine.__file__: /base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/__init__.pyc
google.__file__: /base/data/home/runtimes/python27/python27_lib/versions/1/google/__init__.pyc
```

**Comment by jonparrott** [comment]
```
google.__path__: ['/base/data/home/runtimes/python27/python27_lib/versions/1/google', '/base/data/home/apps/s~redacted/20150831t094105.386826042375743781/lib/google']
```

**Comment by dhermes** [comment]
If it's in `lib`, didn't you put it there?

**Comment by jonparrott** [comment]
yes, via pip:

```
pip install -t lib gcloud
```

**Comment by dhermes** [comment]
Ha. OK so we're all good then? :grin:

**Comment by jonparrott** [comment]
I think we're good, I just don't know *why* we're good. I can't think of a reason why I should be able to import both ``google.appengine`` and ``google.protobuf`` when the former is not a namespace package - does only one of the two have to be a namespace package?

**Comment by dhermes** [comment]
Maybe you have the hack in `appengine_config.py` that I suggested above or maybe GAE does it by default.

**Comment by jonparrott** [comment]
Nope, ``appengine_config.py``:

```
from google.appengine.ext import vendor

vendor.add('lib')
```

Seems like ``protobuf-3.0.0a1`` adds a ``.pth`` file in ``./lib`` that magically makes this work even though the SDK's ``google`` isn't a namespace package.

**Comment by dhermes** [comment]
Very nice! Way to go `protobuf`.

**Comment by jonparrott** [comment]
So what I'm trying to figure out is why this wasn't working before, as I can't seem to find the point in time where protobuf started working. :|

**Comment by dhermes** [comment]
I'll poke through the last few releases and look for the `.pth`:

https://pypi.python.org/packages/source/p/protobuf/protobuf-2.5.0.tar.gz#md5=338813f3629d59e9579fed9035ecd457
https://pypi.python.org/packages/source/p/protobuf/protobuf-2.6.0.tar.gz#md5=3a25a1efda4feba5427b96e9b34bc94a
https://pypi.python.org/packages/source/p/protobuf/protobuf-2.6.1.tar.gz#md5=6bf843912193f70073db7f22e2ea55e2
https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0-alpha-1.tar.gz#md5=7318fdb3dc43390b305dbc4f0df2aefa
https://pypi.python.org/packages/source/p/protobuf/protobuf-3.0.0a3.tar.gz#md5=6674fa7452ebf066b767075db96a7ee0

**Comment by dhermes** [comment]
OK it seems I don't understand what causes a `.pth` to be created during install. (Throws up hands)

**Comment by jonparrott** [comment]
[this commit](https://github.com/GoogleCloudPlatform/gcloud-python/commit/8913b72bcddfd8b0bd4e8d17ed60a449ea003d90) here likely caused it to be resolved for gcloud users.

@waprin do you still have the original app that caused that?

**Comment by jonparrott** [comment]
@dhermes thanks for your time here. I'm glad this works, I just want to understand why it works so that it doesn't randomly get broken in the future.

**Comment by dhermes** [comment]
Ditto

**Comment by waprin** [comment]
I'm not sure what the original app was, most likely just me using appengine-python-flask-skeleton, and yes it now imports correctly for me too without the hack.
