### ISSUE TITLE
Make "Fork me on Github" banner static positioned

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#97]
I don't want it to be hidden when you're scrolled far down the page.

**Comment by dhermes** [comment]
@jgeewax Has this been done in `gcloud-node`? We want the typical black ribbon in the top right corner? I feel like forking is not really our worry (if people don't know about forking, their contributions likely won't be high quality). #98 on the other hand is something we need ASAP

**Comment by jgeewax** [comment]
> (if people don't know about forking, their contributions likely won't be high quality)

Agreed. I'm fine with closing this out.

For #98 , I think it's important that if I scroll far down into a section of the docs, and see a problem with a specific thing (ie, say the note on http://googlecloudplatform.github.io/gcloud-python/storage-blobs.html#gcloud.storage.blob.Blob.upload_from_file), I shouldn't have to scroll all the way back up -- I'd want to click "edit" right there and be taken to the right place...

@dhermes : Feel free to close if you agree with all of that...

**Comment by dhermes** [comment]
I do. We could put the "file docs bug" in our Big Blue Bar(TM) at the top of each page.
