### ISSUE TITLE
Make it easy to open a documentation bug from the docs themselves

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#98]
Maybe we can add paragraph level "report bug" links that link to the issues/new page?

**Comment by dhermes** [comment]
@silvolu I seem to remember you doing something like this based on readthedocs ([example][1]):

![screen_shot_054](https://cloud.githubusercontent.com/assets/520669/5754010/5496012c-9c47-11e4-9927-1bb686d74b35.png)

Did this happen in `gcloud-node`? I know it was [brought up][2] but I'm not sure if it ever came to be.

[1]: http://docs.getpelican.com/en/3.5.0/
[2]: https://github.com/GoogleCloudPlatform/gcloud-node/pull/305#issuecomment-65839912

**Comment by jgeewax** [comment]
Doesn't appear that we've added this on gcloud-node yet either (
http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0/datastore/transaction
)

**Comment by stephenplusplus** [comment]
We have an "Edit on GitHub" link on the two pages that are generated from MD: https://googlecloudplatform.github.io/gcloud-node/#/faq and https://googlecloudplatform.github.io/gcloud-node/#/troubleshooting

**Comment by dhermes** [comment]
For reference, my [comment][1] on the version fix (for #472) points out where to put something like this.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/625#issuecomment-74167700

**Comment by jgeewax** [comment]
Made a comment on another bug, but putting it here for reference:

> I think it's important that if I scroll far down into a section of the docs, and see a problem with a specific thing (ie, say the note on http://googlecloudplatform.github.io/gcloud-python/storage-blobs.html#gcloud.storage.blob.Blob.upload_from_file), I shouldn't have to scroll all the way back up -- I'd want to click "edit" right there and be taken to the right place...

Any chance we can do that? Maybe have the issue body pre-filled with the method that has the issue?

**Comment by dhermes** [comment]
I'll also port over my comment:

> We could put the "file docs bug" in our Big Blue Bar(TM) which stays fixed at the top of each page.

As for pre-filling issue body, I'd have to learn a bit more about what GitHub allows.

**Comment by dhermes** [comment]
@jgeewax WDYT of:

![screen_shot_066](https://cloud.githubusercontent.com/assets/520669/6193858/0e94fd60-b374-11e4-8609-4e3dd267ba37.png)

This also drops "Python" from #538, though I noticed `Node.js` is the title in node land.

This becomes an issue when the nav gets collapsed when page width goes down i.e. for mobile (responsive web dev).

![screen_shot_067](https://cloud.githubusercontent.com/assets/520669/6193915/79232760-b374-11e4-9aef-7365333a5d83.png)

Would you like to see "Report an Issue" folded into the nav hamburger (3 stacked white bars on RHS) or somewhere else?

**Comment by jgeewax** [comment]
If we can't pre-populate the bug text with anything (ie, "method was ....") then this is great -- and we just need some responsive tweaks.

**Comment by dhermes** [comment]
Pre-populating will be possible. E.g.:

https://github.com/GoogleCloudPlatform/gcloud-python/issues/new?body=Commit%3A%2008fae45%0APage%3A%20http%3A%2F%2Fgooglecloudplatform.github.io%2Fgcloud-python%2Flatest%2Fdatastore-entities.html

Need to get #624 and #625 in before though so we don't have conflicting things flying by

**Comment by dhermes** [comment]
An [example][1] for getting the source path in our template:

```html
      {%- if show_source and has_source and sourcename %}
      |
      <a href="{{ pathto('_sources/' + sourcename, true)|e }}"
          rel="nofollow">{{ _('Page source') }}</a></li>
      {%- endif %}
```

[1]: https://github.com/bitprophet/alabaster/blob/a46b19cf8b612b8798e7f5961ff9e466e349f7bd/alabaster/layout.html#L18-L23
