### ISSUE TITLE
[Documentation Issue] Include doc for exclusion of GCE credentials for generate_signed_url

### ISSUE THREAD

**Issue by julienmarcbrown** [GoogleCloudPlatform/gcloud-python#983]
Page Name: storage-blobs
Release: 0.6.0

Since generate_signed_url parameter 'credentials' isn't supported currently by GCE, should include notice.

**Comment by dhermes** [comment]
Good call. Thanks! Related to #922

**Comment by julienmarcbrown** [comment]
any idea of a workaround? or if it will be supported in the future?

**Comment by dhermes** [comment]
Can you chime in on #922? I don't have visibility into internal feature development at Google. You can support it today by just using a service account via a JSON key file on GCE. Put it in your VM image or as a metadata value.
