### ISSUE TITLE
Unify ACL handling between storage and bigquery

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#999]
From: https://github.com/GoogleCloudPlatform/gcloud-python/pull/986#discussion_r34596696

The notion of ACLs might be pertinent for other discovery-based APIs, too (e.g., why does pubsub not have it?)

**Comment by dhermes** [comment]
@tseaver Is this ever going to happen? (I.e. is it feasible?)

**Comment by tseaver** [comment]
Because storage has separate APIs for its ACLs, it may not be feasible to unify the two.

**Comment by dhermes** [comment]
Can we move from "may not" to "will" or "won't" and then close this our (it it's "won't") or commit to it.

**Comment by tseaver** [comment]
I'd say "let's not".
